# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from genproto.common.v1 import common_pb2 as common_dot_v1_dot_common__pb2
from genproto.llm.v1 import llm_pb2 as llm_dot_v1_dot_llm__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in llm/v1/llm_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RagServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Answer = channel.unary_unary(
                '/rag.llm.v1.RagService/Answer',
                request_serializer=common_dot_v1_dot_common__pb2.RagRequest.SerializeToString,
                response_deserializer=common_dot_v1_dot_common__pb2.RagResponse.FromString,
                _registered_method=True)
        self.DocumentChunks = channel.unary_unary(
                '/rag.llm.v1.RagService/DocumentChunks',
                request_serializer=llm_dot_v1_dot_llm__pb2.DocumentChunksRequest.SerializeToString,
                response_deserializer=llm_dot_v1_dot_llm__pb2.DocumentChunksResponse.FromString,
                _registered_method=True)


class RagServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Answer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DocumentChunks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RagServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Answer': grpc.unary_unary_rpc_method_handler(
                    servicer.Answer,
                    request_deserializer=common_dot_v1_dot_common__pb2.RagRequest.FromString,
                    response_serializer=common_dot_v1_dot_common__pb2.RagResponse.SerializeToString,
            ),
            'DocumentChunks': grpc.unary_unary_rpc_method_handler(
                    servicer.DocumentChunks,
                    request_deserializer=llm_dot_v1_dot_llm__pb2.DocumentChunksRequest.FromString,
                    response_serializer=llm_dot_v1_dot_llm__pb2.DocumentChunksResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rag.llm.v1.RagService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rag.llm.v1.RagService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RagService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Answer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.llm.v1.RagService/Answer',
            common_dot_v1_dot_common__pb2.RagRequest.SerializeToString,
            common_dot_v1_dot_common__pb2.RagResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DocumentChunks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.llm.v1.RagService/DocumentChunks',
            llm_dot_v1_dot_llm__pb2.DocumentChunksRequest.SerializeToString,
            llm_dot_v1_dot_llm__pb2.DocumentChunksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
