# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from genproto.graph.v1 import graph_pb2 as graph_dot_v1_dot_graph__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in graph/v1/graph_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GraphComputeStub:
    """GraphCompute is a stateless graph/clustering engine. It reads document vectors
    from Qdrant, builds a kNN cosine graph, runs community detection (Leiden by
    default), and returns clusters with metrics, representatives and lineage.
    Orchestrators (cluster-worker, discovery-worker) call it; all durable state
    stays in Qdrant / Postgres / Valkey — this service holds none.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Cluster = channel.unary_unary(
                '/rag.graph.v1.GraphCompute/Cluster',
                request_serializer=graph_dot_v1_dot_graph__pb2.ClusterRequest.SerializeToString,
                response_deserializer=graph_dot_v1_dot_graph__pb2.ClusterResponse.FromString,
                _registered_method=True)
        self.ScoreBridges = channel.unary_unary(
                '/rag.graph.v1.GraphCompute/ScoreBridges',
                request_serializer=graph_dot_v1_dot_graph__pb2.BridgeRequest.SerializeToString,
                response_deserializer=graph_dot_v1_dot_graph__pb2.BridgeResponse.FromString,
                _registered_method=True)
        self.Rank = channel.unary_unary(
                '/rag.graph.v1.GraphCompute/Rank',
                request_serializer=graph_dot_v1_dot_graph__pb2.RankRequest.SerializeToString,
                response_deserializer=graph_dot_v1_dot_graph__pb2.RankResponse.FromString,
                _registered_method=True)
        self.Paths = channel.unary_unary(
                '/rag.graph.v1.GraphCompute/Paths',
                request_serializer=graph_dot_v1_dot_graph__pb2.PathRequest.SerializeToString,
                response_deserializer=graph_dot_v1_dot_graph__pb2.PathResponse.FromString,
                _registered_method=True)


class GraphComputeServicer:
    """GraphCompute is a stateless graph/clustering engine. It reads document vectors
    from Qdrant, builds a kNN cosine graph, runs community detection (Leiden by
    default), and returns clusters with metrics, representatives and lineage.
    Orchestrators (cluster-worker, discovery-worker) call it; all durable state
    stays in Qdrant / Postgres / Valkey — this service holds none.
    """

    def Cluster(self, request, context):
        """Cluster scrolls the collection, pools chunks into document vectors and
        returns the community partition with metrics/representatives/lineage.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScoreBridges(self, request, context):
        """Discovery layer (Фаза 3): score cross-community "bridges" — distant-but-affine
        theme pairs (structural holes) with ABC mediators — for hypothesis generation.
        Reuses the same kNN + Leiden graph as Cluster.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Rank(self, request, context):
        """Graph-reasoning layer (Фаза 4): Personalized PageRank over the same kNN graph
        — the HippoRAG-2 substrate. The caller resolves a query to seed nodes; PPR
        propagates relevance from those seeds across the graph and ranks the corpus.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Paths(self, request, context):
        """Graph-reasoning layer (Фаза 4): PathRAG — pruned connecting paths between two
        node sets. Returns the top reasoning chains linking sources to targets, scored
        by edge-weight flow with a length penalty.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GraphComputeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Cluster': grpc.unary_unary_rpc_method_handler(
                    servicer.Cluster,
                    request_deserializer=graph_dot_v1_dot_graph__pb2.ClusterRequest.FromString,
                    response_serializer=graph_dot_v1_dot_graph__pb2.ClusterResponse.SerializeToString,
            ),
            'ScoreBridges': grpc.unary_unary_rpc_method_handler(
                    servicer.ScoreBridges,
                    request_deserializer=graph_dot_v1_dot_graph__pb2.BridgeRequest.FromString,
                    response_serializer=graph_dot_v1_dot_graph__pb2.BridgeResponse.SerializeToString,
            ),
            'Rank': grpc.unary_unary_rpc_method_handler(
                    servicer.Rank,
                    request_deserializer=graph_dot_v1_dot_graph__pb2.RankRequest.FromString,
                    response_serializer=graph_dot_v1_dot_graph__pb2.RankResponse.SerializeToString,
            ),
            'Paths': grpc.unary_unary_rpc_method_handler(
                    servicer.Paths,
                    request_deserializer=graph_dot_v1_dot_graph__pb2.PathRequest.FromString,
                    response_serializer=graph_dot_v1_dot_graph__pb2.PathResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rag.graph.v1.GraphCompute', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rag.graph.v1.GraphCompute', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GraphCompute:
    """GraphCompute is a stateless graph/clustering engine. It reads document vectors
    from Qdrant, builds a kNN cosine graph, runs community detection (Leiden by
    default), and returns clusters with metrics, representatives and lineage.
    Orchestrators (cluster-worker, discovery-worker) call it; all durable state
    stays in Qdrant / Postgres / Valkey — this service holds none.
    """

    @staticmethod
    def Cluster(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.graph.v1.GraphCompute/Cluster',
            graph_dot_v1_dot_graph__pb2.ClusterRequest.SerializeToString,
            graph_dot_v1_dot_graph__pb2.ClusterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScoreBridges(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.graph.v1.GraphCompute/ScoreBridges',
            graph_dot_v1_dot_graph__pb2.BridgeRequest.SerializeToString,
            graph_dot_v1_dot_graph__pb2.BridgeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Rank(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.graph.v1.GraphCompute/Rank',
            graph_dot_v1_dot_graph__pb2.RankRequest.SerializeToString,
            graph_dot_v1_dot_graph__pb2.RankResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Paths(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.graph.v1.GraphCompute/Paths',
            graph_dot_v1_dot_graph__pb2.PathRequest.SerializeToString,
            graph_dot_v1_dot_graph__pb2.PathResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
