// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: graph/v1/graph.proto

package graphv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ClusterConfig mirrors the knobs the Python cluster-worker used, so output stays
// compatible with the existing clusters `params` JSON.
type ClusterConfig struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	KnnK              uint32                 `protobuf:"varint,1,opt,name=knn_k,json=knnK,proto3" json:"knn_k,omitempty"`                                            // default 6
	KnnBlockSize      uint32                 `protobuf:"varint,2,opt,name=knn_block_size,json=knnBlockSize,proto3" json:"knn_block_size,omitempty"`                  // default 512
	Resolution        float64                `protobuf:"fixed64,3,opt,name=resolution,proto3" json:"resolution,omitempty"`                                           // default 1.0 (Leiden semantics differ from Louvain)
	MinSize           uint32                 `protobuf:"varint,4,opt,name=min_size,json=minSize,proto3" json:"min_size,omitempty"`                                   // default 2 (drop smaller communities)
	SimThreshold      float64                `protobuf:"fixed64,5,opt,name=sim_threshold,json=simThreshold,proto3" json:"sim_threshold,omitempty"`                   // default 0.0 (drop edges below this cosine)
	MutualKnn         bool                   `protobuf:"varint,6,opt,name=mutual_knn,json=mutualKnn,proto3" json:"mutual_knn,omitempty"`                             // default true (else union kNN)
	ChunkWeighting    bool                   `protobuf:"varint,7,opt,name=chunk_weighting,json=chunkWeighting,proto3" json:"chunk_weighting,omitempty"`              // default true
	ChunkLeadCount    uint32                 `protobuf:"varint,8,opt,name=chunk_lead_count,json=chunkLeadCount,proto3" json:"chunk_lead_count,omitempty"`            // default 2 (lead chunks boosted)
	ChunkWLead        float64                `protobuf:"fixed64,9,opt,name=chunk_w_lead,json=chunkWLead,proto3" json:"chunk_w_lead,omitempty"`                       // default 2.0
	ChunkWResults     float64                `protobuf:"fixed64,10,opt,name=chunk_w_results,json=chunkWResults,proto3" json:"chunk_w_results,omitempty"`             // default 1.5
	ChunkWRefs        float64                `protobuf:"fixed64,11,opt,name=chunk_w_refs,json=chunkWRefs,proto3" json:"chunk_w_refs,omitempty"`                      // default 0.05
	LineageOverlapMin float64                `protobuf:"fixed64,12,opt,name=lineage_overlap_min,json=lineageOverlapMin,proto3" json:"lineage_overlap_min,omitempty"` // default 0.3
	Algorithm         string                 `protobuf:"bytes,13,opt,name=algorithm,proto3" json:"algorithm,omitempty"`                                              // "leiden" (default) | "louvain"
	Seed              *uint64                `protobuf:"varint,14,opt,name=seed,proto3,oneof" json:"seed,omitempty"`                                                 // determinism (Python used 42)
	MaxIterations     *uint32                `protobuf:"varint,15,opt,name=max_iterations,json=maxIterations,proto3,oneof" json:"max_iterations,omitempty"`          // Leiden iteration cap
	// Clustering altitude. "document" (default, "") pools every chunk of a document
	// into one node — the existing theme-board behaviour. "chunk" SKIPS pooling and
	// clusters the raw chunk vectors directly (one node per Qdrant point), so the
	// returned cluster `members` are chunk point ids. Used by raptor-worker to build
	// the hierarchical RAPTOR summary layer over chunks.
	Granularity   string `protobuf:"bytes,16,opt,name=granularity,proto3" json:"granularity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterConfig) Reset() {
	*x = ClusterConfig{}
	mi := &file_graph_v1_graph_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterConfig) ProtoMessage() {}

func (x *ClusterConfig) ProtoReflect() protoreflect.Message {
	mi := &file_graph_v1_graph_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterConfig.ProtoReflect.Descriptor instead.
func (*ClusterConfig) Descriptor() ([]byte, []int) {
	return file_graph_v1_graph_proto_rawDescGZIP(), []int{0}
}

func (x *ClusterConfig) GetKnnK() uint32 {
	if x != nil {
		return x.KnnK
	}
	return 0
}

func (x *ClusterConfig) GetKnnBlockSize() uint32 {
	if x != nil {
		return x.KnnBlockSize
	}
	return 0
}

func (x *ClusterConfig) GetResolution() float64 {
	if x != nil {
		return x.Resolution
	}
	return 0
}

func (x *ClusterConfig) GetMinSize() uint32 {
	if x != nil {
		return x.MinSize
	}
	return 0
}

func (x *ClusterConfig) GetSimThreshold() float64 {
	if x != nil {
		return x.SimThreshold
	}
	return 0
}

func (x *ClusterConfig) GetMutualKnn() bool {
	if x != nil {
		return x.MutualKnn
	}
	return false
}

func (x *ClusterConfig) GetChunkWeighting() bool {
	if x != nil {
		return x.ChunkWeighting
	}
	return false
}

func (x *ClusterConfig) GetChunkLeadCount() uint32 {
	if x != nil {
		return x.ChunkLeadCount
	}
	return 0
}

func (x *ClusterConfig) GetChunkWLead() float64 {
	if x != nil {
		return x.ChunkWLead
	}
	return 0
}

func (x *ClusterConfig) GetChunkWResults() float64 {
	if x != nil {
		return x.ChunkWResults
	}
	return 0
}

func (x *ClusterConfig) GetChunkWRefs() float64 {
	if x != nil {
		return x.ChunkWRefs
	}
	return 0
}

func (x *ClusterConfig) GetLineageOverlapMin() float64 {
	if x != nil {
		return x.LineageOverlapMin
	}
	return 0
}

func (x *ClusterConfig) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *ClusterConfig) GetSeed() uint64 {
	if x != nil && x.Seed != nil {
		return *x.Seed
	}
	return 0
}

func (x *ClusterConfig) GetMaxIterations() uint32 {
	if x != nil && x.MaxIterations != nil {
		return *x.MaxIterations
	}
	return 0
}

func (x *ClusterConfig) GetGranularity() string {
	if x != nil {
		return x.Granularity
	}
	return ""
}

type DocumentRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentRef) Reset() {
	*x = DocumentRef{}
	mi := &file_graph_v1_graph_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentRef) ProtoMessage() {}

func (x *DocumentRef) ProtoReflect() protoreflect.Message {
	mi := &file_graph_v1_graph_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentRef.ProtoReflect.Descriptor instead.
func (*DocumentRef) Descriptor() ([]byte, []int) {
	return file_graph_v1_graph_proto_rawDescGZIP(), []int{1}
}

func (x *DocumentRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DocumentRef) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

// PreviousCluster carries the prior board membership for lineage computation.
type PreviousCluster struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Members       []string               `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"` // document ids
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviousCluster) Reset() {
	*x = PreviousCluster{}
	mi := &file_graph_v1_graph_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviousCluster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviousCluster) ProtoMessage() {}

func (x *PreviousCluster) ProtoReflect() protoreflect.Message {
	mi := &file_graph_v1_graph_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviousCluster.ProtoReflect.Descriptor instead.
func (*PreviousCluster) Descriptor() ([]byte, []int) {
	return file_graph_v1_graph_proto_rawDescGZIP(), []int{2}
}

func (x *PreviousCluster) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PreviousCluster) GetMembers() []string {
	if x != nil {
		return x.Members
	}
	return nil
}

type ClusterRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OwnerId          string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"` // "" = shared/global corpus
	Collection       string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`          // Qdrant collection, default "documents"
	Config           *ClusterConfig         `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	Documents        []*DocumentRef         `protobuf:"bytes,4,rep,name=documents,proto3" json:"documents,omitempty"`                                       // owner-scoped doc list (filename map + scoping)
	PreviousClusters []*PreviousCluster     `protobuf:"bytes,5,rep,name=previous_clusters,json=previousClusters,proto3" json:"previous_clusters,omitempty"` // for lineage; empty on first run
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ClusterRequest) Reset() {
	*x = ClusterRequest{}
	mi := &file_graph_v1_graph_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterRequest) ProtoMessage() {}

func (x *ClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graph_v1_graph_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterRequest.ProtoReflect.Descriptor instead.
func (*ClusterRequest) Descriptor() ([]byte, []int) {
	return file_graph_v1_graph_proto_rawDescGZIP(), []int{3}
}

func (x *ClusterRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *ClusterRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *ClusterRequest) GetConfig() *ClusterConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ClusterRequest) GetDocuments() []*DocumentRef {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *ClusterRequest) GetPreviousClusters() []*PreviousCluster {
	if x != nil {
		return x.PreviousClusters
	}
	return nil
}

type Representative struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	Snippet       string                 `protobuf:"bytes,3,opt,name=snippet,proto3" json:"snippet,omitempty"` // best prose snippet, <= 360 chars
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Representative) Reset() {
	*x = Representative{}
	mi := &file_graph_v1_graph_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Representative) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Representative) ProtoMessage() {}

func (x *Representative) ProtoReflect() protoreflect.Message {
	mi := &file_graph_v1_graph_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Representative.ProtoReflect.Descriptor instead.
func (*Representative) Descriptor() ([]byte, []int) {
	return file_graph_v1_graph_proto_rawDescGZIP(), []int{4}
}

func (x *Representative) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *Representative) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Representative) GetSnippet() string {
	if x != nil {
		return x.Snippet
	}
	return ""
}

type ClusterMetrics struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Size                   uint32                 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`                                                                    // member count
	AvgSimilarity          float64                `protobuf:"fixed64,2,opt,name=avg_similarity,json=avgSimilarity,proto3" json:"avg_similarity,omitempty"`                            // mean intra-cluster cosine
	Modularity             float64                `protobuf:"fixed64,3,opt,name=modularity,proto3" json:"modularity,omitempty"`                                                       // partition modularity Q
	ModularityContribution float64                `protobuf:"fixed64,4,opt,name=modularity_contribution,json=modularityContribution,proto3" json:"modularity_contribution,omitempty"` // this community's contribution to Q
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ClusterMetrics) Reset() {
	*x = ClusterMetrics{}
	mi := &file_graph_v1_graph_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterMetrics) ProtoMessage() {}

func (x *ClusterMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_graph_v1_graph_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterMetrics.ProtoReflect.Descriptor instead.
func (*ClusterMetrics) Descriptor() ([]byte, []int) {
	return file_graph_v1_graph_proto_rawDescGZIP(), []int{5}
}

func (x *ClusterMetrics) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ClusterMetrics) GetAvgSimilarity() float64 {
	if x != nil {
		return x.AvgSimilarity
	}
	return 0
}

func (x *ClusterMetrics) GetModularity() float64 {
	if x != nil {
		return x.Modularity
	}
	return 0
}

func (x *ClusterMetrics) GetModularityContribution() float64 {
	if x != nil {
		return x.ModularityContribution
	}
	return 0
}

type Lineage struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PreviousClusterId string                 `protobuf:"bytes,1,opt,name=previous_cluster_id,json=previousClusterId,proto3" json:"previous_cluster_id,omitempty"` // best Jaccard match
	Jaccard           float64                `protobuf:"fixed64,2,opt,name=jaccard,proto3" json:"jaccard,omitempty"`
	Stability         float64                `protobuf:"fixed64,3,opt,name=stability,proto3" json:"stability,omitempty"`                   // == jaccard
	MergedFrom        []string               `protobuf:"bytes,4,rep,name=merged_from,json=mergedFrom,proto3" json:"merged_from,omitempty"` // >=2 prior clusters folded in
	SplitFrom         string                 `protobuf:"bytes,5,opt,name=split_from,json=splitFrom,proto3" json:"split_from,omitempty"`    // set if the matched prior fed >=2 new clusters
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Lineage) Reset() {
	*x = Lineage{}
	mi := &file_graph_v1_graph_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lineage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lineage) ProtoMessage() {}

func (x *Lineage) ProtoReflect() protoreflect.Message {
	mi := &file_graph_v1_graph_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lineage.ProtoReflect.Descriptor instead.
func (*Lineage) Descriptor() ([]byte, []int) {
	return file_graph_v1_graph_proto_rawDescGZIP(), []int{6}
}

func (x *Lineage) GetPreviousClusterId() string {
	if x != nil {
		return x.PreviousClusterId
	}
	return ""
}

func (x *Lineage) GetJaccard() float64 {
	if x != nil {
		return x.Jaccard
	}
	return 0
}

func (x *Lineage) GetStability() float64 {
	if x != nil {
		return x.Stability
	}
	return 0
}

func (x *Lineage) GetMergedFrom() []string {
	if x != nil {
		return x.MergedFrom
	}
	return nil
}

func (x *Lineage) GetSplitFrom() string {
	if x != nil {
		return x.SplitFrom
	}
	return ""
}

type Cluster struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Members         []string               `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`         // document ids, sorted
	Fingerprint     string                 `protobuf:"bytes,2,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"` // sha1[:16] of sorted members
	Signals         []string               `protobuf:"bytes,3,rep,name=signals,proto3" json:"signals,omitempty"`         // representative texts for LLM labeling (Python step)
	ChunkCount      uint32                 `protobuf:"varint,4,opt,name=chunk_count,json=chunkCount,proto3" json:"chunk_count,omitempty"`
	Metrics         *ClusterMetrics        `protobuf:"bytes,5,opt,name=metrics,proto3" json:"metrics,omitempty"`
	Representatives []*Representative      `protobuf:"bytes,6,rep,name=representatives,proto3" json:"representatives,omitempty"`
	Lineage         *Lineage               `protobuf:"bytes,7,opt,name=lineage,proto3" json:"lineage,omitempty"` // unset/empty when no prior board
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Cluster) Reset() {
	*x = Cluster{}
	mi := &file_graph_v1_graph_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cluster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cluster) ProtoMessage() {}

func (x *Cluster) ProtoReflect() protoreflect.Message {
	mi := &file_graph_v1_graph_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cluster.ProtoReflect.Descriptor instead.
func (*Cluster) Descriptor() ([]byte, []int) {
	return file_graph_v1_graph_proto_rawDescGZIP(), []int{7}
}

func (x *Cluster) GetMembers() []string {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *Cluster) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *Cluster) GetSignals() []string {
	if x != nil {
		return x.Signals
	}
	return nil
}

func (x *Cluster) GetChunkCount() uint32 {
	if x != nil {
		return x.ChunkCount
	}
	return 0
}

func (x *Cluster) GetMetrics() *ClusterMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *Cluster) GetRepresentatives() []*Representative {
	if x != nil {
		return x.Representatives
	}
	return nil
}

func (x *Cluster) GetLineage() *Lineage {
	if x != nil {
		return x.Lineage
	}
	return nil
}

type ComputeStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentCount uint32                 `protobuf:"varint,1,opt,name=document_count,json=documentCount,proto3" json:"document_count,omitempty"`
	EdgeCount     uint32                 `protobuf:"varint,2,opt,name=edge_count,json=edgeCount,proto3" json:"edge_count,omitempty"`
	Modularity    float64                `protobuf:"fixed64,3,opt,name=modularity,proto3" json:"modularity,omitempty"` // whole-partition Q
	ComputeMs     uint64                 `protobuf:"varint,4,opt,name=compute_ms,json=computeMs,proto3" json:"compute_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComputeStats) Reset() {
	*x = ComputeStats{}
	mi := &file_graph_v1_graph_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeStats) ProtoMessage() {}

func (x *ComputeStats) ProtoReflect() protoreflect.Message {
	mi := &file_graph_v1_graph_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeStats.ProtoReflect.Descriptor instead.
func (*ComputeStats) Descriptor() ([]byte, []int) {
	return file_graph_v1_graph_proto_rawDescGZIP(), []int{8}
}

func (x *ComputeStats) GetDocumentCount() uint32 {
	if x != nil {
		return x.DocumentCount
	}
	return 0
}

func (x *ComputeStats) GetEdgeCount() uint32 {
	if x != nil {
		return x.EdgeCount
	}
	return 0
}

func (x *ComputeStats) GetModularity() float64 {
	if x != nil {
		return x.Modularity
	}
	return 0
}

func (x *ComputeStats) GetComputeMs() uint64 {
	if x != nil {
		return x.ComputeMs
	}
	return 0
}

type ClusterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clusters      []*Cluster             `protobuf:"bytes,1,rep,name=clusters,proto3" json:"clusters,omitempty"`
	Stats         *ComputeStats          `protobuf:"bytes,2,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterResponse) Reset() {
	*x = ClusterResponse{}
	mi := &file_graph_v1_graph_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterResponse) ProtoMessage() {}

func (x *ClusterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graph_v1_graph_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterResponse.ProtoReflect.Descriptor instead.
func (*ClusterResponse) Descriptor() ([]byte, []int) {
	return file_graph_v1_graph_proto_rawDescGZIP(), []int{9}
}

func (x *ClusterResponse) GetClusters() []*Cluster {
	if x != nil {
		return x.Clusters
	}
	return nil
}

func (x *ClusterResponse) GetStats() *ComputeStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type BridgeConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Cluster        *ClusterConfig         `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`                                      // builds the same kNN + Leiden graph/communities
	TopN           uint32                 `protobuf:"varint,2,opt,name=top_n,json=topN,proto3" json:"top_n,omitempty"`                               // max bridges returned (default 50)
	MinAffinity    float64                `protobuf:"fixed64,3,opt,name=min_affinity,json=minAffinity,proto3" json:"min_affinity,omitempty"`         // min centroid cosine to consider a pair (default 0.15)
	MaxMediators   uint32                 `protobuf:"varint,4,opt,name=max_mediators,json=maxMediators,proto3" json:"max_mediators,omitempty"`       // ABC mediators returned per bridge (default 3)
	MinConvergence uint32                 `protobuf:"varint,5,opt,name=min_convergence,json=minConvergence,proto3" json:"min_convergence,omitempty"` // drop bridges with fewer mediating nodes (default 1; >=2 = convergent)
	WMaverick      float64                `protobuf:"fixed64,6,opt,name=w_maverick,json=wMaverick,proto3" json:"w_maverick,omitempty"`               // composite weight: distant recombination (default 1.0)
	WBridging      float64                `protobuf:"fixed64,7,opt,name=w_bridging,json=wBridging,proto3" json:"w_bridging,omitempty"`               // composite weight: bridging-centrality (default 1.0)
	WVanguard      float64                `protobuf:"fixed64,8,opt,name=w_vanguard,json=wVanguard,proto3" json:"w_vanguard,omitempty"`               // composite weight: weak-tie reinforcement (default 0.5)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BridgeConfig) Reset() {
	*x = BridgeConfig{}
	mi := &file_graph_v1_graph_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BridgeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BridgeConfig) ProtoMessage() {}

func (x *BridgeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_graph_v1_graph_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BridgeConfig.ProtoReflect.Descriptor instead.
func (*BridgeConfig) Descriptor() ([]byte, []int) {
	return file_graph_v1_graph_proto_rawDescGZIP(), []int{10}
}

func (x *BridgeConfig) GetCluster() *ClusterConfig {
	if x != nil {
		return x.Cluster
	}
	return nil
}

func (x *BridgeConfig) GetTopN() uint32 {
	if x != nil {
		return x.TopN
	}
	return 0
}

func (x *BridgeConfig) GetMinAffinity() float64 {
	if x != nil {
		return x.MinAffinity
	}
	return 0
}

func (x *BridgeConfig) GetMaxMediators() uint32 {
	if x != nil {
		return x.MaxMediators
	}
	return 0
}

func (x *BridgeConfig) GetMinConvergence() uint32 {
	if x != nil {
		return x.MinConvergence
	}
	return 0
}

func (x *BridgeConfig) GetWMaverick() float64 {
	if x != nil {
		return x.WMaverick
	}
	return 0
}

func (x *BridgeConfig) GetWBridging() float64 {
	if x != nil {
		return x.WBridging
	}
	return 0
}

func (x *BridgeConfig) GetWVanguard() float64 {
	if x != nil {
		return x.WVanguard
	}
	return 0
}

type BridgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Collection    string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	Config        *BridgeConfig          `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	Documents     []*DocumentRef         `protobuf:"bytes,4,rep,name=documents,proto3" json:"documents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BridgeRequest) Reset() {
	*x = BridgeRequest{}
	mi := &file_graph_v1_graph_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BridgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BridgeRequest) ProtoMessage() {}

func (x *BridgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graph_v1_graph_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BridgeRequest.ProtoReflect.Descriptor instead.
func (*BridgeRequest) Descriptor() ([]byte, []int) {
	return file_graph_v1_graph_proto_rawDescGZIP(), []int{11}
}

func (x *BridgeRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *BridgeRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *BridgeRequest) GetConfig() *BridgeConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *BridgeRequest) GetDocuments() []*DocumentRef {
	if x != nil {
		return x.Documents
	}
	return nil
}

type Mediator struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	Snippet       string                 `protobuf:"bytes,3,opt,name=snippet,proto3" json:"snippet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mediator) Reset() {
	*x = Mediator{}
	mi := &file_graph_v1_graph_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mediator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mediator) ProtoMessage() {}

func (x *Mediator) ProtoReflect() protoreflect.Message {
	mi := &file_graph_v1_graph_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mediator.ProtoReflect.Descriptor instead.
func (*Mediator) Descriptor() ([]byte, []int) {
	return file_graph_v1_graph_proto_rawDescGZIP(), []int{12}
}

func (x *Mediator) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *Mediator) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Mediator) GetSnippet() string {
	if x != nil {
		return x.Snippet
	}
	return ""
}

type BridgeScores struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Affinity           float64                `protobuf:"fixed64,1,opt,name=affinity,proto3" json:"affinity,omitempty"`                                               // centroid cosine between the two communities
	LinkDensity        float64                `protobuf:"fixed64,2,opt,name=link_density,json=linkDensity,proto3" json:"link_density,omitempty"`                      // realized cross edges / (|A|*|B|)
	Maverick           float64                `protobuf:"fixed64,3,opt,name=maverick,proto3" json:"maverick,omitempty"`                                               // affinity * (1 - link_density): structural-hole recombination
	Vanguard           float64                `protobuf:"fixed64,4,opt,name=vanguard,proto3" json:"vanguard,omitempty"`                                               // weak-tie reinforcement (affine pair with a few weak links)
	BridgingCentrality float64                `protobuf:"fixed64,5,opt,name=bridging_centrality,json=bridgingCentrality,proto3" json:"bridging_centrality,omitempty"` // boundary betweenness * bridging coefficient
	Convergence        uint32                 `protobuf:"varint,6,opt,name=convergence,proto3" json:"convergence,omitempty"`                                          // number of mediating documents found
	Composite          float64                `protobuf:"fixed64,7,opt,name=composite,proto3" json:"composite,omitempty"`                                             // ranked score
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *BridgeScores) Reset() {
	*x = BridgeScores{}
	mi := &file_graph_v1_graph_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BridgeScores) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BridgeScores) ProtoMessage() {}

func (x *BridgeScores) ProtoReflect() protoreflect.Message {
	mi := &file_graph_v1_graph_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BridgeScores.ProtoReflect.Descriptor instead.
func (*BridgeScores) Descriptor() ([]byte, []int) {
	return file_graph_v1_graph_proto_rawDescGZIP(), []int{13}
}

func (x *BridgeScores) GetAffinity() float64 {
	if x != nil {
		return x.Affinity
	}
	return 0
}

func (x *BridgeScores) GetLinkDensity() float64 {
	if x != nil {
		return x.LinkDensity
	}
	return 0
}

func (x *BridgeScores) GetMaverick() float64 {
	if x != nil {
		return x.Maverick
	}
	return 0
}

func (x *BridgeScores) GetVanguard() float64 {
	if x != nil {
		return x.Vanguard
	}
	return 0
}

func (x *BridgeScores) GetBridgingCentrality() float64 {
	if x != nil {
		return x.BridgingCentrality
	}
	return 0
}

func (x *BridgeScores) GetConvergence() uint32 {
	if x != nil {
		return x.Convergence
	}
	return 0
}

func (x *BridgeScores) GetComposite() float64 {
	if x != nil {
		return x.Composite
	}
	return 0
}

type Bridge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fingerprint   string                 `protobuf:"bytes,1,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`                 // sha1[:16] of sorted (community_a, community_b)
	CommunityA    string                 `protobuf:"bytes,2,opt,name=community_a,json=communityA,proto3" json:"community_a,omitempty"` // fingerprint of community A
	CommunityB    string                 `protobuf:"bytes,3,opt,name=community_b,json=communityB,proto3" json:"community_b,omitempty"` // fingerprint of community B
	MembersA      []string               `protobuf:"bytes,4,rep,name=members_a,json=membersA,proto3" json:"members_a,omitempty"`       // document ids in A (sorted)
	MembersB      []string               `protobuf:"bytes,5,rep,name=members_b,json=membersB,proto3" json:"members_b,omitempty"`       // document ids in B (sorted)
	EndpointA     string                 `protobuf:"bytes,6,opt,name=endpoint_a,json=endpointA,proto3" json:"endpoint_a,omitempty"`    // anchor document in A (closest to B's centroid)
	EndpointB     string                 `protobuf:"bytes,7,opt,name=endpoint_b,json=endpointB,proto3" json:"endpoint_b,omitempty"`    // anchor document in B (closest to A's centroid)
	Mediators     []*Mediator            `protobuf:"bytes,8,rep,name=mediators,proto3" json:"mediators,omitempty"`                     // ABC "B" nodes connecting the endpoints
	Scores        *BridgeScores          `protobuf:"bytes,9,opt,name=scores,proto3" json:"scores,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bridge) Reset() {
	*x = Bridge{}
	mi := &file_graph_v1_graph_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bridge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bridge) ProtoMessage() {}

func (x *Bridge) ProtoReflect() protoreflect.Message {
	mi := &file_graph_v1_graph_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bridge.ProtoReflect.Descriptor instead.
func (*Bridge) Descriptor() ([]byte, []int) {
	return file_graph_v1_graph_proto_rawDescGZIP(), []int{14}
}

func (x *Bridge) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *Bridge) GetCommunityA() string {
	if x != nil {
		return x.CommunityA
	}
	return ""
}

func (x *Bridge) GetCommunityB() string {
	if x != nil {
		return x.CommunityB
	}
	return ""
}

func (x *Bridge) GetMembersA() []string {
	if x != nil {
		return x.MembersA
	}
	return nil
}

func (x *Bridge) GetMembersB() []string {
	if x != nil {
		return x.MembersB
	}
	return nil
}

func (x *Bridge) GetEndpointA() string {
	if x != nil {
		return x.EndpointA
	}
	return ""
}

func (x *Bridge) GetEndpointB() string {
	if x != nil {
		return x.EndpointB
	}
	return ""
}

func (x *Bridge) GetMediators() []*Mediator {
	if x != nil {
		return x.Mediators
	}
	return nil
}

func (x *Bridge) GetScores() *BridgeScores {
	if x != nil {
		return x.Scores
	}
	return nil
}

type BridgeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bridges       []*Bridge              `protobuf:"bytes,1,rep,name=bridges,proto3" json:"bridges,omitempty"`
	Stats         *ComputeStats          `protobuf:"bytes,2,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BridgeResponse) Reset() {
	*x = BridgeResponse{}
	mi := &file_graph_v1_graph_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BridgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BridgeResponse) ProtoMessage() {}

func (x *BridgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graph_v1_graph_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BridgeResponse.ProtoReflect.Descriptor instead.
func (*BridgeResponse) Descriptor() ([]byte, []int) {
	return file_graph_v1_graph_proto_rawDescGZIP(), []int{15}
}

func (x *BridgeResponse) GetBridges() []*Bridge {
	if x != nil {
		return x.Bridges
	}
	return nil
}

func (x *BridgeResponse) GetStats() *ComputeStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type RankRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`                    // "" = shared/global corpus
	Collection    string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`                             // Qdrant collection, default "documents"
	Config        *ClusterConfig         `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`                                     // builds the graph; honours `granularity` (document|chunk)
	SeedIds       []string               `protobuf:"bytes,4,rep,name=seed_ids,json=seedIds,proto3" json:"seed_ids,omitempty"`                    // point ids to personalize toward; empty = uniform PageRank
	TopN          uint32                 `protobuf:"varint,5,opt,name=top_n,json=topN,proto3" json:"top_n,omitempty"`                            // max ranked nodes returned (0 = all)
	Damping       float64                `protobuf:"fixed64,6,opt,name=damping,proto3" json:"damping,omitempty"`                                 // teleport/damping factor (default 0.85)
	MaxIterations uint32                 `protobuf:"varint,7,opt,name=max_iterations,json=maxIterations,proto3" json:"max_iterations,omitempty"` // power-iteration cap (default 100)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RankRequest) Reset() {
	*x = RankRequest{}
	mi := &file_graph_v1_graph_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankRequest) ProtoMessage() {}

func (x *RankRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graph_v1_graph_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankRequest.ProtoReflect.Descriptor instead.
func (*RankRequest) Descriptor() ([]byte, []int) {
	return file_graph_v1_graph_proto_rawDescGZIP(), []int{16}
}

func (x *RankRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *RankRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *RankRequest) GetConfig() *ClusterConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *RankRequest) GetSeedIds() []string {
	if x != nil {
		return x.SeedIds
	}
	return nil
}

func (x *RankRequest) GetTopN() uint32 {
	if x != nil {
		return x.TopN
	}
	return 0
}

func (x *RankRequest) GetDamping() float64 {
	if x != nil {
		return x.Damping
	}
	return 0
}

func (x *RankRequest) GetMaxIterations() uint32 {
	if x != nil {
		return x.MaxIterations
	}
	return 0
}

type RankedNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`         // node id (document id, or chunk point id under chunk granularity)
	Score         float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"` // Personalized PageRank mass (the full vector sums to 1)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RankedNode) Reset() {
	*x = RankedNode{}
	mi := &file_graph_v1_graph_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankedNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankedNode) ProtoMessage() {}

func (x *RankedNode) ProtoReflect() protoreflect.Message {
	mi := &file_graph_v1_graph_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankedNode.ProtoReflect.Descriptor instead.
func (*RankedNode) Descriptor() ([]byte, []int) {
	return file_graph_v1_graph_proto_rawDescGZIP(), []int{17}
}

func (x *RankedNode) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RankedNode) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type RankResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*RankedNode          `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"` // sorted by score desc, then id asc; truncated to top_n
	Stats         *ComputeStats          `protobuf:"bytes,2,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RankResponse) Reset() {
	*x = RankResponse{}
	mi := &file_graph_v1_graph_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankResponse) ProtoMessage() {}

func (x *RankResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graph_v1_graph_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankResponse.ProtoReflect.Descriptor instead.
func (*RankResponse) Descriptor() ([]byte, []int) {
	return file_graph_v1_graph_proto_rawDescGZIP(), []int{18}
}

func (x *RankResponse) GetNodes() []*RankedNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *RankResponse) GetStats() *ComputeStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type PathRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Collection    string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	Config        *ClusterConfig         `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`                        // builds the graph; honours `granularity`
	SourceIds     []string               `protobuf:"bytes,4,rep,name=source_ids,json=sourceIds,proto3" json:"source_ids,omitempty"` // path start nodes (point ids)
	TargetIds     []string               `protobuf:"bytes,5,rep,name=target_ids,json=targetIds,proto3" json:"target_ids,omitempty"` // path end nodes (point ids)
	MaxPaths      uint32                 `protobuf:"varint,6,opt,name=max_paths,json=maxPaths,proto3" json:"max_paths,omitempty"`   // max paths returned (default 10)
	MaxHops       uint32                 `protobuf:"varint,7,opt,name=max_hops,json=maxHops,proto3" json:"max_hops,omitempty"`      // max path length in edges (default 4)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PathRequest) Reset() {
	*x = PathRequest{}
	mi := &file_graph_v1_graph_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathRequest) ProtoMessage() {}

func (x *PathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graph_v1_graph_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathRequest.ProtoReflect.Descriptor instead.
func (*PathRequest) Descriptor() ([]byte, []int) {
	return file_graph_v1_graph_proto_rawDescGZIP(), []int{19}
}

func (x *PathRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *PathRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *PathRequest) GetConfig() *ClusterConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *PathRequest) GetSourceIds() []string {
	if x != nil {
		return x.SourceIds
	}
	return nil
}

func (x *PathRequest) GetTargetIds() []string {
	if x != nil {
		return x.TargetIds
	}
	return nil
}

func (x *PathRequest) GetMaxPaths() uint32 {
	if x != nil {
		return x.MaxPaths
	}
	return 0
}

func (x *PathRequest) GetMaxHops() uint32 {
	if x != nil {
		return x.MaxHops
	}
	return 0
}

type GraphPath struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeIds       []string               `protobuf:"bytes,1,rep,name=node_ids,json=nodeIds,proto3" json:"node_ids,omitempty"` // ordered node ids, source → target (inclusive)
	Score         float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`                  // flow/length score; higher = stronger, shorter chain
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphPath) Reset() {
	*x = GraphPath{}
	mi := &file_graph_v1_graph_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphPath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphPath) ProtoMessage() {}

func (x *GraphPath) ProtoReflect() protoreflect.Message {
	mi := &file_graph_v1_graph_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphPath.ProtoReflect.Descriptor instead.
func (*GraphPath) Descriptor() ([]byte, []int) {
	return file_graph_v1_graph_proto_rawDescGZIP(), []int{20}
}

func (x *GraphPath) GetNodeIds() []string {
	if x != nil {
		return x.NodeIds
	}
	return nil
}

func (x *GraphPath) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type PathResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paths         []*GraphPath           `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"` // sorted by score desc, then node_ids; truncated to max_paths
	Stats         *ComputeStats          `protobuf:"bytes,2,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PathResponse) Reset() {
	*x = PathResponse{}
	mi := &file_graph_v1_graph_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathResponse) ProtoMessage() {}

func (x *PathResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graph_v1_graph_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathResponse.ProtoReflect.Descriptor instead.
func (*PathResponse) Descriptor() ([]byte, []int) {
	return file_graph_v1_graph_proto_rawDescGZIP(), []int{21}
}

func (x *PathResponse) GetPaths() []*GraphPath {
	if x != nil {
		return x.Paths
	}
	return nil
}

func (x *PathResponse) GetStats() *ComputeStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

var File_graph_v1_graph_proto protoreflect.FileDescriptor

const file_graph_v1_graph_proto_rawDesc = "" +
	"\n" +
	"\x14graph/v1/graph.proto\x12\frag.graph.v1\"\xd9\x04\n" +
	"\rClusterConfig\x12\x13\n" +
	"\x05knn_k\x18\x01 \x01(\rR\x04knnK\x12$\n" +
	"\x0eknn_block_size\x18\x02 \x01(\rR\fknnBlockSize\x12\x1e\n" +
	"\n" +
	"resolution\x18\x03 \x01(\x01R\n" +
	"resolution\x12\x19\n" +
	"\bmin_size\x18\x04 \x01(\rR\aminSize\x12#\n" +
	"\rsim_threshold\x18\x05 \x01(\x01R\fsimThreshold\x12\x1d\n" +
	"\n" +
	"mutual_knn\x18\x06 \x01(\bR\tmutualKnn\x12'\n" +
	"\x0fchunk_weighting\x18\a \x01(\bR\x0echunkWeighting\x12(\n" +
	"\x10chunk_lead_count\x18\b \x01(\rR\x0echunkLeadCount\x12 \n" +
	"\fchunk_w_lead\x18\t \x01(\x01R\n" +
	"chunkWLead\x12&\n" +
	"\x0fchunk_w_results\x18\n" +
	" \x01(\x01R\rchunkWResults\x12 \n" +
	"\fchunk_w_refs\x18\v \x01(\x01R\n" +
	"chunkWRefs\x12.\n" +
	"\x13lineage_overlap_min\x18\f \x01(\x01R\x11lineageOverlapMin\x12\x1c\n" +
	"\talgorithm\x18\r \x01(\tR\talgorithm\x12\x17\n" +
	"\x04seed\x18\x0e \x01(\x04H\x00R\x04seed\x88\x01\x01\x12*\n" +
	"\x0emax_iterations\x18\x0f \x01(\rH\x01R\rmaxIterations\x88\x01\x01\x12 \n" +
	"\vgranularity\x18\x10 \x01(\tR\vgranularityB\a\n" +
	"\x05_seedB\x11\n" +
	"\x0f_max_iterations\"9\n" +
	"\vDocumentRef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\";\n" +
	"\x0fPreviousCluster\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\amembers\x18\x02 \x03(\tR\amembers\"\x85\x02\n" +
	"\x0eClusterRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\x123\n" +
	"\x06config\x18\x03 \x01(\v2\x1b.rag.graph.v1.ClusterConfigR\x06config\x127\n" +
	"\tdocuments\x18\x04 \x03(\v2\x19.rag.graph.v1.DocumentRefR\tdocuments\x12J\n" +
	"\x11previous_clusters\x18\x05 \x03(\v2\x1d.rag.graph.v1.PreviousClusterR\x10previousClusters\"g\n" +
	"\x0eRepresentative\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x18\n" +
	"\asnippet\x18\x03 \x01(\tR\asnippet\"\xa4\x01\n" +
	"\x0eClusterMetrics\x12\x12\n" +
	"\x04size\x18\x01 \x01(\rR\x04size\x12%\n" +
	"\x0eavg_similarity\x18\x02 \x01(\x01R\ravgSimilarity\x12\x1e\n" +
	"\n" +
	"modularity\x18\x03 \x01(\x01R\n" +
	"modularity\x127\n" +
	"\x17modularity_contribution\x18\x04 \x01(\x01R\x16modularityContribution\"\xb1\x01\n" +
	"\aLineage\x12.\n" +
	"\x13previous_cluster_id\x18\x01 \x01(\tR\x11previousClusterId\x12\x18\n" +
	"\ajaccard\x18\x02 \x01(\x01R\ajaccard\x12\x1c\n" +
	"\tstability\x18\x03 \x01(\x01R\tstability\x12\x1f\n" +
	"\vmerged_from\x18\x04 \x03(\tR\n" +
	"mergedFrom\x12\x1d\n" +
	"\n" +
	"split_from\x18\x05 \x01(\tR\tsplitFrom\"\xb1\x02\n" +
	"\aCluster\x12\x18\n" +
	"\amembers\x18\x01 \x03(\tR\amembers\x12 \n" +
	"\vfingerprint\x18\x02 \x01(\tR\vfingerprint\x12\x18\n" +
	"\asignals\x18\x03 \x03(\tR\asignals\x12\x1f\n" +
	"\vchunk_count\x18\x04 \x01(\rR\n" +
	"chunkCount\x126\n" +
	"\ametrics\x18\x05 \x01(\v2\x1c.rag.graph.v1.ClusterMetricsR\ametrics\x12F\n" +
	"\x0frepresentatives\x18\x06 \x03(\v2\x1c.rag.graph.v1.RepresentativeR\x0frepresentatives\x12/\n" +
	"\alineage\x18\a \x01(\v2\x15.rag.graph.v1.LineageR\alineage\"\x93\x01\n" +
	"\fComputeStats\x12%\n" +
	"\x0edocument_count\x18\x01 \x01(\rR\rdocumentCount\x12\x1d\n" +
	"\n" +
	"edge_count\x18\x02 \x01(\rR\tedgeCount\x12\x1e\n" +
	"\n" +
	"modularity\x18\x03 \x01(\x01R\n" +
	"modularity\x12\x1d\n" +
	"\n" +
	"compute_ms\x18\x04 \x01(\x04R\tcomputeMs\"v\n" +
	"\x0fClusterResponse\x121\n" +
	"\bclusters\x18\x01 \x03(\v2\x15.rag.graph.v1.ClusterR\bclusters\x120\n" +
	"\x05stats\x18\x02 \x01(\v2\x1a.rag.graph.v1.ComputeStatsR\x05stats\"\xa8\x02\n" +
	"\fBridgeConfig\x125\n" +
	"\acluster\x18\x01 \x01(\v2\x1b.rag.graph.v1.ClusterConfigR\acluster\x12\x13\n" +
	"\x05top_n\x18\x02 \x01(\rR\x04topN\x12!\n" +
	"\fmin_affinity\x18\x03 \x01(\x01R\vminAffinity\x12#\n" +
	"\rmax_mediators\x18\x04 \x01(\rR\fmaxMediators\x12'\n" +
	"\x0fmin_convergence\x18\x05 \x01(\rR\x0eminConvergence\x12\x1d\n" +
	"\n" +
	"w_maverick\x18\x06 \x01(\x01R\twMaverick\x12\x1d\n" +
	"\n" +
	"w_bridging\x18\a \x01(\x01R\twBridging\x12\x1d\n" +
	"\n" +
	"w_vanguard\x18\b \x01(\x01R\twVanguard\"\xb7\x01\n" +
	"\rBridgeRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\x122\n" +
	"\x06config\x18\x03 \x01(\v2\x1a.rag.graph.v1.BridgeConfigR\x06config\x127\n" +
	"\tdocuments\x18\x04 \x03(\v2\x19.rag.graph.v1.DocumentRefR\tdocuments\"a\n" +
	"\bMediator\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x18\n" +
	"\asnippet\x18\x03 \x01(\tR\asnippet\"\xf6\x01\n" +
	"\fBridgeScores\x12\x1a\n" +
	"\baffinity\x18\x01 \x01(\x01R\baffinity\x12!\n" +
	"\flink_density\x18\x02 \x01(\x01R\vlinkDensity\x12\x1a\n" +
	"\bmaverick\x18\x03 \x01(\x01R\bmaverick\x12\x1a\n" +
	"\bvanguard\x18\x04 \x01(\x01R\bvanguard\x12/\n" +
	"\x13bridging_centrality\x18\x05 \x01(\x01R\x12bridgingCentrality\x12 \n" +
	"\vconvergence\x18\x06 \x01(\rR\vconvergence\x12\x1c\n" +
	"\tcomposite\x18\a \x01(\x01R\tcomposite\"\xce\x02\n" +
	"\x06Bridge\x12 \n" +
	"\vfingerprint\x18\x01 \x01(\tR\vfingerprint\x12\x1f\n" +
	"\vcommunity_a\x18\x02 \x01(\tR\n" +
	"communityA\x12\x1f\n" +
	"\vcommunity_b\x18\x03 \x01(\tR\n" +
	"communityB\x12\x1b\n" +
	"\tmembers_a\x18\x04 \x03(\tR\bmembersA\x12\x1b\n" +
	"\tmembers_b\x18\x05 \x03(\tR\bmembersB\x12\x1d\n" +
	"\n" +
	"endpoint_a\x18\x06 \x01(\tR\tendpointA\x12\x1d\n" +
	"\n" +
	"endpoint_b\x18\a \x01(\tR\tendpointB\x124\n" +
	"\tmediators\x18\b \x03(\v2\x16.rag.graph.v1.MediatorR\tmediators\x122\n" +
	"\x06scores\x18\t \x01(\v2\x1a.rag.graph.v1.BridgeScoresR\x06scores\"r\n" +
	"\x0eBridgeResponse\x12.\n" +
	"\abridges\x18\x01 \x03(\v2\x14.rag.graph.v1.BridgeR\abridges\x120\n" +
	"\x05stats\x18\x02 \x01(\v2\x1a.rag.graph.v1.ComputeStatsR\x05stats\"\xee\x01\n" +
	"\vRankRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\x123\n" +
	"\x06config\x18\x03 \x01(\v2\x1b.rag.graph.v1.ClusterConfigR\x06config\x12\x19\n" +
	"\bseed_ids\x18\x04 \x03(\tR\aseedIds\x12\x13\n" +
	"\x05top_n\x18\x05 \x01(\rR\x04topN\x12\x18\n" +
	"\adamping\x18\x06 \x01(\x01R\adamping\x12%\n" +
	"\x0emax_iterations\x18\a \x01(\rR\rmaxIterations\"2\n" +
	"\n" +
	"RankedNode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\"p\n" +
	"\fRankResponse\x12.\n" +
	"\x05nodes\x18\x01 \x03(\v2\x18.rag.graph.v1.RankedNodeR\x05nodes\x120\n" +
	"\x05stats\x18\x02 \x01(\v2\x1a.rag.graph.v1.ComputeStatsR\x05stats\"\xf3\x01\n" +
	"\vPathRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\x123\n" +
	"\x06config\x18\x03 \x01(\v2\x1b.rag.graph.v1.ClusterConfigR\x06config\x12\x1d\n" +
	"\n" +
	"source_ids\x18\x04 \x03(\tR\tsourceIds\x12\x1d\n" +
	"\n" +
	"target_ids\x18\x05 \x03(\tR\ttargetIds\x12\x1b\n" +
	"\tmax_paths\x18\x06 \x01(\rR\bmaxPaths\x12\x19\n" +
	"\bmax_hops\x18\a \x01(\rR\amaxHops\"<\n" +
	"\tGraphPath\x12\x19\n" +
	"\bnode_ids\x18\x01 \x03(\tR\anodeIds\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\"o\n" +
	"\fPathResponse\x12-\n" +
	"\x05paths\x18\x01 \x03(\v2\x17.rag.graph.v1.GraphPathR\x05paths\x120\n" +
	"\x05stats\x18\x02 \x01(\v2\x1a.rag.graph.v1.ComputeStatsR\x05stats2\xa0\x02\n" +
	"\fGraphCompute\x12F\n" +
	"\aCluster\x12\x1c.rag.graph.v1.ClusterRequest\x1a\x1d.rag.graph.v1.ClusterResponse\x12I\n" +
	"\fScoreBridges\x12\x1b.rag.graph.v1.BridgeRequest\x1a\x1c.rag.graph.v1.BridgeResponse\x12=\n" +
	"\x04Rank\x12\x19.rag.graph.v1.RankRequest\x1a\x1a.rag.graph.v1.RankResponse\x12>\n" +
	"\x05Paths\x12\x19.rag.graph.v1.PathRequest\x1a\x1a.rag.graph.v1.PathResponseB:Z8github.com/example/rag-mvp/pkg/genproto/graph/v1;graphv1b\x06proto3"

var (
	file_graph_v1_graph_proto_rawDescOnce sync.Once
	file_graph_v1_graph_proto_rawDescData []byte
)

func file_graph_v1_graph_proto_rawDescGZIP() []byte {
	file_graph_v1_graph_proto_rawDescOnce.Do(func() {
		file_graph_v1_graph_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_graph_v1_graph_proto_rawDesc), len(file_graph_v1_graph_proto_rawDesc)))
	})
	return file_graph_v1_graph_proto_rawDescData
}

var file_graph_v1_graph_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_graph_v1_graph_proto_goTypes = []any{
	(*ClusterConfig)(nil),   // 0: rag.graph.v1.ClusterConfig
	(*DocumentRef)(nil),     // 1: rag.graph.v1.DocumentRef
	(*PreviousCluster)(nil), // 2: rag.graph.v1.PreviousCluster
	(*ClusterRequest)(nil),  // 3: rag.graph.v1.ClusterRequest
	(*Representative)(nil),  // 4: rag.graph.v1.Representative
	(*ClusterMetrics)(nil),  // 5: rag.graph.v1.ClusterMetrics
	(*Lineage)(nil),         // 6: rag.graph.v1.Lineage
	(*Cluster)(nil),         // 7: rag.graph.v1.Cluster
	(*ComputeStats)(nil),    // 8: rag.graph.v1.ComputeStats
	(*ClusterResponse)(nil), // 9: rag.graph.v1.ClusterResponse
	(*BridgeConfig)(nil),    // 10: rag.graph.v1.BridgeConfig
	(*BridgeRequest)(nil),   // 11: rag.graph.v1.BridgeRequest
	(*Mediator)(nil),        // 12: rag.graph.v1.Mediator
	(*BridgeScores)(nil),    // 13: rag.graph.v1.BridgeScores
	(*Bridge)(nil),          // 14: rag.graph.v1.Bridge
	(*BridgeResponse)(nil),  // 15: rag.graph.v1.BridgeResponse
	(*RankRequest)(nil),     // 16: rag.graph.v1.RankRequest
	(*RankedNode)(nil),      // 17: rag.graph.v1.RankedNode
	(*RankResponse)(nil),    // 18: rag.graph.v1.RankResponse
	(*PathRequest)(nil),     // 19: rag.graph.v1.PathRequest
	(*GraphPath)(nil),       // 20: rag.graph.v1.GraphPath
	(*PathResponse)(nil),    // 21: rag.graph.v1.PathResponse
}
var file_graph_v1_graph_proto_depIdxs = []int32{
	0,  // 0: rag.graph.v1.ClusterRequest.config:type_name -> rag.graph.v1.ClusterConfig
	1,  // 1: rag.graph.v1.ClusterRequest.documents:type_name -> rag.graph.v1.DocumentRef
	2,  // 2: rag.graph.v1.ClusterRequest.previous_clusters:type_name -> rag.graph.v1.PreviousCluster
	5,  // 3: rag.graph.v1.Cluster.metrics:type_name -> rag.graph.v1.ClusterMetrics
	4,  // 4: rag.graph.v1.Cluster.representatives:type_name -> rag.graph.v1.Representative
	6,  // 5: rag.graph.v1.Cluster.lineage:type_name -> rag.graph.v1.Lineage
	7,  // 6: rag.graph.v1.ClusterResponse.clusters:type_name -> rag.graph.v1.Cluster
	8,  // 7: rag.graph.v1.ClusterResponse.stats:type_name -> rag.graph.v1.ComputeStats
	0,  // 8: rag.graph.v1.BridgeConfig.cluster:type_name -> rag.graph.v1.ClusterConfig
	10, // 9: rag.graph.v1.BridgeRequest.config:type_name -> rag.graph.v1.BridgeConfig
	1,  // 10: rag.graph.v1.BridgeRequest.documents:type_name -> rag.graph.v1.DocumentRef
	12, // 11: rag.graph.v1.Bridge.mediators:type_name -> rag.graph.v1.Mediator
	13, // 12: rag.graph.v1.Bridge.scores:type_name -> rag.graph.v1.BridgeScores
	14, // 13: rag.graph.v1.BridgeResponse.bridges:type_name -> rag.graph.v1.Bridge
	8,  // 14: rag.graph.v1.BridgeResponse.stats:type_name -> rag.graph.v1.ComputeStats
	0,  // 15: rag.graph.v1.RankRequest.config:type_name -> rag.graph.v1.ClusterConfig
	17, // 16: rag.graph.v1.RankResponse.nodes:type_name -> rag.graph.v1.RankedNode
	8,  // 17: rag.graph.v1.RankResponse.stats:type_name -> rag.graph.v1.ComputeStats
	0,  // 18: rag.graph.v1.PathRequest.config:type_name -> rag.graph.v1.ClusterConfig
	20, // 19: rag.graph.v1.PathResponse.paths:type_name -> rag.graph.v1.GraphPath
	8,  // 20: rag.graph.v1.PathResponse.stats:type_name -> rag.graph.v1.ComputeStats
	3,  // 21: rag.graph.v1.GraphCompute.Cluster:input_type -> rag.graph.v1.ClusterRequest
	11, // 22: rag.graph.v1.GraphCompute.ScoreBridges:input_type -> rag.graph.v1.BridgeRequest
	16, // 23: rag.graph.v1.GraphCompute.Rank:input_type -> rag.graph.v1.RankRequest
	19, // 24: rag.graph.v1.GraphCompute.Paths:input_type -> rag.graph.v1.PathRequest
	9,  // 25: rag.graph.v1.GraphCompute.Cluster:output_type -> rag.graph.v1.ClusterResponse
	15, // 26: rag.graph.v1.GraphCompute.ScoreBridges:output_type -> rag.graph.v1.BridgeResponse
	18, // 27: rag.graph.v1.GraphCompute.Rank:output_type -> rag.graph.v1.RankResponse
	21, // 28: rag.graph.v1.GraphCompute.Paths:output_type -> rag.graph.v1.PathResponse
	25, // [25:29] is the sub-list for method output_type
	21, // [21:25] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_graph_v1_graph_proto_init() }
func file_graph_v1_graph_proto_init() {
	if File_graph_v1_graph_proto != nil {
		return
	}
	file_graph_v1_graph_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_graph_v1_graph_proto_rawDesc), len(file_graph_v1_graph_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_graph_v1_graph_proto_goTypes,
		DependencyIndexes: file_graph_v1_graph_proto_depIdxs,
		MessageInfos:      file_graph_v1_graph_proto_msgTypes,
	}.Build()
	File_graph_v1_graph_proto = out.File
	file_graph_v1_graph_proto_goTypes = nil
	file_graph_v1_graph_proto_depIdxs = nil
}
