// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: graph/v1/graph.proto

package graphv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GraphCompute_Cluster_FullMethodName      = "/rag.graph.v1.GraphCompute/Cluster"
	GraphCompute_ScoreBridges_FullMethodName = "/rag.graph.v1.GraphCompute/ScoreBridges"
	GraphCompute_Rank_FullMethodName         = "/rag.graph.v1.GraphCompute/Rank"
	GraphCompute_Paths_FullMethodName        = "/rag.graph.v1.GraphCompute/Paths"
)

// GraphComputeClient is the client API for GraphCompute service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GraphCompute is a stateless graph/clustering engine. It reads document vectors
// from Qdrant, builds a kNN cosine graph, runs community detection (Leiden by
// default), and returns clusters with metrics, representatives and lineage.
// Orchestrators (cluster-worker, discovery-worker) call it; all durable state
// stays in Qdrant / Postgres / Valkey — this service holds none.
type GraphComputeClient interface {
	// Cluster scrolls the collection, pools chunks into document vectors and
	// returns the community partition with metrics/representatives/lineage.
	Cluster(ctx context.Context, in *ClusterRequest, opts ...grpc.CallOption) (*ClusterResponse, error)
	// Discovery layer (Фаза 3): score cross-community "bridges" — distant-but-affine
	// theme pairs (structural holes) with ABC mediators — for hypothesis generation.
	// Reuses the same kNN + Leiden graph as Cluster.
	ScoreBridges(ctx context.Context, in *BridgeRequest, opts ...grpc.CallOption) (*BridgeResponse, error)
	// Graph-reasoning layer (Фаза 4): Personalized PageRank over the same kNN graph
	// — the HippoRAG-2 substrate. The caller resolves a query to seed nodes; PPR
	// propagates relevance from those seeds across the graph and ranks the corpus.
	Rank(ctx context.Context, in *RankRequest, opts ...grpc.CallOption) (*RankResponse, error)
	// Graph-reasoning layer (Фаза 4): PathRAG — pruned connecting paths between two
	// node sets. Returns the top reasoning chains linking sources to targets, scored
	// by edge-weight flow with a length penalty.
	Paths(ctx context.Context, in *PathRequest, opts ...grpc.CallOption) (*PathResponse, error)
}

type graphComputeClient struct {
	cc grpc.ClientConnInterface
}

func NewGraphComputeClient(cc grpc.ClientConnInterface) GraphComputeClient {
	return &graphComputeClient{cc}
}

func (c *graphComputeClient) Cluster(ctx context.Context, in *ClusterRequest, opts ...grpc.CallOption) (*ClusterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClusterResponse)
	err := c.cc.Invoke(ctx, GraphCompute_Cluster_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graphComputeClient) ScoreBridges(ctx context.Context, in *BridgeRequest, opts ...grpc.CallOption) (*BridgeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BridgeResponse)
	err := c.cc.Invoke(ctx, GraphCompute_ScoreBridges_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graphComputeClient) Rank(ctx context.Context, in *RankRequest, opts ...grpc.CallOption) (*RankResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RankResponse)
	err := c.cc.Invoke(ctx, GraphCompute_Rank_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graphComputeClient) Paths(ctx context.Context, in *PathRequest, opts ...grpc.CallOption) (*PathResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PathResponse)
	err := c.cc.Invoke(ctx, GraphCompute_Paths_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GraphComputeServer is the server API for GraphCompute service.
// All implementations must embed UnimplementedGraphComputeServer
// for forward compatibility.
//
// GraphCompute is a stateless graph/clustering engine. It reads document vectors
// from Qdrant, builds a kNN cosine graph, runs community detection (Leiden by
// default), and returns clusters with metrics, representatives and lineage.
// Orchestrators (cluster-worker, discovery-worker) call it; all durable state
// stays in Qdrant / Postgres / Valkey — this service holds none.
type GraphComputeServer interface {
	// Cluster scrolls the collection, pools chunks into document vectors and
	// returns the community partition with metrics/representatives/lineage.
	Cluster(context.Context, *ClusterRequest) (*ClusterResponse, error)
	// Discovery layer (Фаза 3): score cross-community "bridges" — distant-but-affine
	// theme pairs (structural holes) with ABC mediators — for hypothesis generation.
	// Reuses the same kNN + Leiden graph as Cluster.
	ScoreBridges(context.Context, *BridgeRequest) (*BridgeResponse, error)
	// Graph-reasoning layer (Фаза 4): Personalized PageRank over the same kNN graph
	// — the HippoRAG-2 substrate. The caller resolves a query to seed nodes; PPR
	// propagates relevance from those seeds across the graph and ranks the corpus.
	Rank(context.Context, *RankRequest) (*RankResponse, error)
	// Graph-reasoning layer (Фаза 4): PathRAG — pruned connecting paths between two
	// node sets. Returns the top reasoning chains linking sources to targets, scored
	// by edge-weight flow with a length penalty.
	Paths(context.Context, *PathRequest) (*PathResponse, error)
	mustEmbedUnimplementedGraphComputeServer()
}

// UnimplementedGraphComputeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGraphComputeServer struct{}

func (UnimplementedGraphComputeServer) Cluster(context.Context, *ClusterRequest) (*ClusterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Cluster not implemented")
}
func (UnimplementedGraphComputeServer) ScoreBridges(context.Context, *BridgeRequest) (*BridgeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ScoreBridges not implemented")
}
func (UnimplementedGraphComputeServer) Rank(context.Context, *RankRequest) (*RankResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Rank not implemented")
}
func (UnimplementedGraphComputeServer) Paths(context.Context, *PathRequest) (*PathResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Paths not implemented")
}
func (UnimplementedGraphComputeServer) mustEmbedUnimplementedGraphComputeServer() {}
func (UnimplementedGraphComputeServer) testEmbeddedByValue()                      {}

// UnsafeGraphComputeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GraphComputeServer will
// result in compilation errors.
type UnsafeGraphComputeServer interface {
	mustEmbedUnimplementedGraphComputeServer()
}

func RegisterGraphComputeServer(s grpc.ServiceRegistrar, srv GraphComputeServer) {
	// If the following call panics, it indicates UnimplementedGraphComputeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GraphCompute_ServiceDesc, srv)
}

func _GraphCompute_Cluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphComputeServer).Cluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphCompute_Cluster_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphComputeServer).Cluster(ctx, req.(*ClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GraphCompute_ScoreBridges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BridgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphComputeServer).ScoreBridges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphCompute_ScoreBridges_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphComputeServer).ScoreBridges(ctx, req.(*BridgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GraphCompute_Rank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RankRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphComputeServer).Rank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphCompute_Rank_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphComputeServer).Rank(ctx, req.(*RankRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GraphCompute_Paths_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphComputeServer).Paths(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphCompute_Paths_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphComputeServer).Paths(ctx, req.(*PathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GraphCompute_ServiceDesc is the grpc.ServiceDesc for GraphCompute service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GraphCompute_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rag.graph.v1.GraphCompute",
	HandlerType: (*GraphComputeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Cluster",
			Handler:    _GraphCompute_Cluster_Handler,
		},
		{
			MethodName: "ScoreBridges",
			Handler:    _GraphCompute_ScoreBridges_Handler,
		},
		{
			MethodName: "Rank",
			Handler:    _GraphCompute_Rank_Handler,
		},
		{
			MethodName: "Paths",
			Handler:    _GraphCompute_Paths_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "graph/v1/graph.proto",
}
