// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chats.sql

package sqlcgen

import (
	"context"
	"time"
)

const addMessage = `-- name: AddMessage :exec
INSERT INTO chat_messages (id, chat_id, role, content, sources, meta, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type AddMessageParams struct {
	ID        string
	ChatID    string
	Role      string
	Content   string
	Sources   []byte
	Meta      []byte
	CreatedAt time.Time
}

func (q *Queries) AddMessage(ctx context.Context, arg AddMessageParams) error {
	_, err := q.db.Exec(ctx, addMessage,
		arg.ID,
		arg.ChatID,
		arg.Role,
		arg.Content,
		arg.Sources,
		arg.Meta,
		arg.CreatedAt,
	)
	return err
}

const countChats = `-- name: CountChats :one
SELECT count(*) FROM chats
`

func (q *Queries) CountChats(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countChats)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countChatsByOwner = `-- name: CountChatsByOwner :one
SELECT count(*) FROM chats WHERE owner_id = $1
`

func (q *Queries) CountChatsByOwner(ctx context.Context, ownerID string) (int64, error) {
	row := q.db.QueryRow(ctx, countChatsByOwner, ownerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createChat = `-- name: CreateChat :exec
INSERT INTO chats (id, owner_id, title, source, created_at) VALUES ($1, $2, $3, $4, $5)
`

type CreateChatParams struct {
	ID        string
	OwnerID   string
	Title     string
	Source    string
	CreatedAt time.Time
}

func (q *Queries) CreateChat(ctx context.Context, arg CreateChatParams) error {
	_, err := q.db.Exec(ctx, createChat,
		arg.ID,
		arg.OwnerID,
		arg.Title,
		arg.Source,
		arg.CreatedAt,
	)
	return err
}

const getChat = `-- name: GetChat :one
SELECT id, owner_id, title, created_at, source FROM chats WHERE id = $1
`

func (q *Queries) GetChat(ctx context.Context, id string) (Chat, error) {
	row := q.db.QueryRow(ctx, getChat, id)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.CreatedAt,
		&i.Source,
	)
	return i, err
}

const listChatsAll = `-- name: ListChatsAll :many
SELECT c.id, c.owner_id, c.title, c.source, c.created_at,
       coalesce(u.username, '') AS owner_username
FROM chats c
LEFT JOIN users u ON u.id = c.owner_id
ORDER BY c.created_at DESC
LIMIT $1 OFFSET $2
`

type ListChatsAllParams struct {
	Limit  int32
	Offset int32
}

type ListChatsAllRow struct {
	ID            string
	OwnerID       string
	Title         string
	Source        string
	CreatedAt     time.Time
	OwnerUsername string
}

func (q *Queries) ListChatsAll(ctx context.Context, arg ListChatsAllParams) ([]ListChatsAllRow, error) {
	rows, err := q.db.Query(ctx, listChatsAll, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChatsAllRow{}
	for rows.Next() {
		var i ListChatsAllRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.Source,
			&i.CreatedAt,
			&i.OwnerUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChatsByOwner = `-- name: ListChatsByOwner :many
SELECT c.id, c.owner_id, c.title, c.source, c.created_at,
       coalesce(u.username, '') AS owner_username
FROM chats c
LEFT JOIN users u ON u.id = c.owner_id
WHERE c.owner_id = $1
ORDER BY c.created_at DESC
LIMIT $2 OFFSET $3
`

type ListChatsByOwnerParams struct {
	OwnerID string
	Limit   int32
	Offset  int32
}

type ListChatsByOwnerRow struct {
	ID            string
	OwnerID       string
	Title         string
	Source        string
	CreatedAt     time.Time
	OwnerUsername string
}

func (q *Queries) ListChatsByOwner(ctx context.Context, arg ListChatsByOwnerParams) ([]ListChatsByOwnerRow, error) {
	rows, err := q.db.Query(ctx, listChatsByOwner, arg.OwnerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChatsByOwnerRow{}
	for rows.Next() {
		var i ListChatsByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.Source,
			&i.CreatedAt,
			&i.OwnerUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesByChat = `-- name: ListMessagesByChat :many
SELECT id, chat_id, role, content, sources, created_at, meta FROM chat_messages WHERE chat_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListMessagesByChat(ctx context.Context, chatID string) ([]ChatMessage, error) {
	rows, err := q.db.Query(ctx, listMessagesByChat, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatMessage{}
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.Role,
			&i.Content,
			&i.Sources,
			&i.CreatedAt,
			&i.Meta,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
