// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clusters.sql

package sqlcgen

import (
	"context"
	"time"
)

const createCluster = `-- name: CreateCluster :exec
INSERT INTO clusters
  (id, owner_id, label, summary, keywords, method, chunk_count, document_count,
   representatives, params, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
`

type CreateClusterParams struct {
	ID              string
	OwnerID         string
	Label           string
	Summary         string
	Keywords        []string
	Method          string
	ChunkCount      int32
	DocumentCount   int32
	Representatives []byte
	Params          []byte
	Status          string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) CreateCluster(ctx context.Context, arg CreateClusterParams) error {
	_, err := q.db.Exec(ctx, createCluster,
		arg.ID,
		arg.OwnerID,
		arg.Label,
		arg.Summary,
		arg.Keywords,
		arg.Method,
		arg.ChunkCount,
		arg.DocumentCount,
		arg.Representatives,
		arg.Params,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteClustersByOwner = `-- name: DeleteClustersByOwner :execrows
DELETE FROM clusters WHERE owner_id = $1
`

func (q *Queries) DeleteClustersByOwner(ctx context.Context, ownerID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteClustersByOwner, ownerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCluster = `-- name: GetCluster :one
SELECT id, owner_id, label, summary, keywords, method, chunk_count, document_count, representatives, params, status, created_at, updated_at FROM clusters WHERE id = $1
`

func (q *Queries) GetCluster(ctx context.Context, id string) (Cluster, error) {
	row := q.db.QueryRow(ctx, getCluster, id)
	var i Cluster
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Label,
		&i.Summary,
		&i.Keywords,
		&i.Method,
		&i.ChunkCount,
		&i.DocumentCount,
		&i.Representatives,
		&i.Params,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listClustersByOwner = `-- name: ListClustersByOwner :many
SELECT id, owner_id, label, summary, keywords, method, chunk_count, document_count, representatives, params, status, created_at, updated_at FROM clusters WHERE owner_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListClustersByOwner(ctx context.Context, ownerID string) ([]Cluster, error) {
	rows, err := q.db.Query(ctx, listClustersByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cluster{}
	for rows.Next() {
		var i Cluster
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Label,
			&i.Summary,
			&i.Keywords,
			&i.Method,
			&i.ChunkCount,
			&i.DocumentCount,
			&i.Representatives,
			&i.Params,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCluster = `-- name: UpdateCluster :execrows
UPDATE clusters
SET label = $2, summary = $3, keywords = $4, method = $5, chunk_count = $6,
    document_count = $7, representatives = $8, params = $9, status = $10,
    updated_at = now()
WHERE id = $1
`

type UpdateClusterParams struct {
	ID              string
	Label           string
	Summary         string
	Keywords        []string
	Method          string
	ChunkCount      int32
	DocumentCount   int32
	Representatives []byte
	Params          []byte
	Status          string
}

func (q *Queries) UpdateCluster(ctx context.Context, arg UpdateClusterParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCluster,
		arg.ID,
		arg.Label,
		arg.Summary,
		arg.Keywords,
		arg.Method,
		arg.ChunkCount,
		arg.DocumentCount,
		arg.Representatives,
		arg.Params,
		arg.Status,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
