// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package sqlcgen

import (
	"context"
	"time"
)

const createDocument = `-- name: CreateDocument :exec
INSERT INTO documents
  (id, owner_id, filename, mime_type, size, object_key, status, status_msg,
   chunk_count, created_at, updated_at, content_hash)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type CreateDocumentParams struct {
	ID          string
	OwnerID     string
	Filename    string
	MimeType    string
	Size        int64
	ObjectKey   string
	Status      string
	StatusMsg   string
	ChunkCount  int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
	ContentHash string
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) error {
	_, err := q.db.Exec(ctx, createDocument,
		arg.ID,
		arg.OwnerID,
		arg.Filename,
		arg.MimeType,
		arg.Size,
		arg.ObjectKey,
		arg.Status,
		arg.StatusMsg,
		arg.ChunkCount,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ContentHash,
	)
	return err
}

const findDocumentByHash = `-- name: FindDocumentByHash :one
SELECT id, owner_id, filename, mime_type, size, object_key, status, status_msg, chunk_count, created_at, updated_at, content_hash, title, author, published_at, source_ref, kind FROM documents
WHERE content_hash = $1
  AND ($2::text = '' OR owner_id = $2)
  AND status <> 'failed'
ORDER BY chunk_count DESC, created_at ASC
LIMIT 1
`

type FindDocumentByHashParams struct {
	ContentHash string
	OwnerID     string
}

func (q *Queries) FindDocumentByHash(ctx context.Context, arg FindDocumentByHashParams) (Document, error) {
	row := q.db.QueryRow(ctx, findDocumentByHash, arg.ContentHash, arg.OwnerID)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Filename,
		&i.MimeType,
		&i.Size,
		&i.ObjectKey,
		&i.Status,
		&i.StatusMsg,
		&i.ChunkCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContentHash,
		&i.Title,
		&i.Author,
		&i.PublishedAt,
		&i.SourceRef,
		&i.Kind,
	)
	return i, err
}

const getDocument = `-- name: GetDocument :one
SELECT id, owner_id, filename, mime_type, size, object_key, status, status_msg, chunk_count, created_at, updated_at, content_hash, title, author, published_at, source_ref, kind FROM documents WHERE id = $1
`

func (q *Queries) GetDocument(ctx context.Context, id string) (Document, error) {
	row := q.db.QueryRow(ctx, getDocument, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Filename,
		&i.MimeType,
		&i.Size,
		&i.ObjectKey,
		&i.Status,
		&i.StatusMsg,
		&i.ChunkCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContentHash,
		&i.Title,
		&i.Author,
		&i.PublishedAt,
		&i.SourceRef,
		&i.Kind,
	)
	return i, err
}

const listDocumentsByOwner = `-- name: ListDocumentsByOwner :many
SELECT id, owner_id, filename, mime_type, size, object_key, status, status_msg, chunk_count, created_at, updated_at, content_hash, title, author, published_at, source_ref, kind FROM documents
WHERE ($1::text = '' OR owner_id = $1)
ORDER BY created_at DESC
`

func (q *Queries) ListDocumentsByOwner(ctx context.Context, ownerID string) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocumentsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Filename,
			&i.MimeType,
			&i.Size,
			&i.ObjectKey,
			&i.Status,
			&i.StatusMsg,
			&i.ChunkCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContentHash,
			&i.Title,
			&i.Author,
			&i.PublishedAt,
			&i.SourceRef,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocumentKind = `-- name: UpdateDocumentKind :exec
UPDATE documents
SET kind = $1,
    updated_at = now()
WHERE id = $2
`

type UpdateDocumentKindParams struct {
	Kind string
	ID   string
}

func (q *Queries) UpdateDocumentKind(ctx context.Context, arg UpdateDocumentKindParams) error {
	_, err := q.db.Exec(ctx, updateDocumentKind, arg.Kind, arg.ID)
	return err
}

const updateDocumentMeta = `-- name: UpdateDocumentMeta :exec
UPDATE documents
SET author = $1,
    published_at = $2,
    source_ref = $3,
    updated_at = now()
WHERE id = $4
`

type UpdateDocumentMetaParams struct {
	Author      string
	PublishedAt string
	SourceRef   string
	ID          string
}

func (q *Queries) UpdateDocumentMeta(ctx context.Context, arg UpdateDocumentMetaParams) error {
	_, err := q.db.Exec(ctx, updateDocumentMeta,
		arg.Author,
		arg.PublishedAt,
		arg.SourceRef,
		arg.ID,
	)
	return err
}

const updateDocumentStatus = `-- name: UpdateDocumentStatus :exec
UPDATE documents
SET status = $1,
    status_msg = $2,
    chunk_count = COALESCE($3, chunk_count),
    updated_at = now()
WHERE id = $4
`

type UpdateDocumentStatusParams struct {
	Status     string
	StatusMsg  string
	ChunkCount *int32
	ID         string
}

func (q *Queries) UpdateDocumentStatus(ctx context.Context, arg UpdateDocumentStatusParams) error {
	_, err := q.db.Exec(ctx, updateDocumentStatus,
		arg.Status,
		arg.StatusMsg,
		arg.ChunkCount,
		arg.ID,
	)
	return err
}

const updateDocumentTitle = `-- name: UpdateDocumentTitle :exec
UPDATE documents
SET title = $1,
    updated_at = now()
WHERE id = $2
`

type UpdateDocumentTitleParams struct {
	Title string
	ID    string
}

func (q *Queries) UpdateDocumentTitle(ctx context.Context, arg UpdateDocumentTitleParams) error {
	_, err := q.db.Exec(ctx, updateDocumentTitle, arg.Title, arg.ID)
	return err
}
