// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hypotheses.sql

package sqlcgen

import (
	"context"
	"time"
)

const getHypothesis = `-- name: GetHypothesis :one
SELECT id, owner_id, run_id, title, statement, rationale, method, status, kpi_id, primary_cluster_id, trl, novelty_score, risk_score, value_score, confidence_score, composite_score, measurable, organization, function_area, source_type, location, tags, assessment, detail, generation, created_at, updated_at FROM hypotheses WHERE id = $1
`

func (q *Queries) GetHypothesis(ctx context.Context, id string) (Hypothesis, error) {
	row := q.db.QueryRow(ctx, getHypothesis, id)
	var i Hypothesis
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.RunID,
		&i.Title,
		&i.Statement,
		&i.Rationale,
		&i.Method,
		&i.Status,
		&i.KpiID,
		&i.PrimaryClusterID,
		&i.Trl,
		&i.NoveltyScore,
		&i.RiskScore,
		&i.ValueScore,
		&i.ConfidenceScore,
		&i.CompositeScore,
		&i.Measurable,
		&i.Organization,
		&i.FunctionArea,
		&i.SourceType,
		&i.Location,
		&i.Tags,
		&i.Assessment,
		&i.Detail,
		&i.Generation,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertEvidence = `-- name: InsertEvidence :exec
INSERT INTO hypothesis_evidence
  (id, hypothesis_id, document_id, chunk_id, filename, snippet, stance, score, ord, created_at,
   relation, page_start, page_end, section_heading, origin)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
`

type InsertEvidenceParams struct {
	ID             string
	HypothesisID   string
	DocumentID     *string
	ChunkID        string
	Filename       string
	Snippet        string
	Stance         string
	Score          *float64
	Ord            int32
	CreatedAt      time.Time
	Relation       string
	PageStart      int32
	PageEnd        int32
	SectionHeading string
	Origin         string
}

func (q *Queries) InsertEvidence(ctx context.Context, arg InsertEvidenceParams) error {
	_, err := q.db.Exec(ctx, insertEvidence,
		arg.ID,
		arg.HypothesisID,
		arg.DocumentID,
		arg.ChunkID,
		arg.Filename,
		arg.Snippet,
		arg.Stance,
		arg.Score,
		arg.Ord,
		arg.CreatedAt,
		arg.Relation,
		arg.PageStart,
		arg.PageEnd,
		arg.SectionHeading,
		arg.Origin,
	)
	return err
}

const insertHypothesis = `-- name: InsertHypothesis :exec
INSERT INTO hypotheses
  (id, owner_id, run_id, title, statement, rationale, method, status, kpi_id,
   primary_cluster_id, trl, novelty_score, risk_score, value_score, confidence_score,
   composite_score, measurable, organization, function_area, source_type, location,
   tags, assessment, detail, generation, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17,
        $18, $19, $20, $21, $22, $23, $24, $25, $26, $27)
`

type InsertHypothesisParams struct {
	ID               string
	OwnerID          string
	RunID            string
	Title            string
	Statement        string
	Rationale        string
	Method           string
	Status           string
	KpiID            *string
	PrimaryClusterID *string
	Trl              *int16
	NoveltyScore     *float64
	RiskScore        *float64
	ValueScore       *float64
	ConfidenceScore  *float64
	CompositeScore   *float64
	Measurable       bool
	Organization     string
	FunctionArea     string
	SourceType       string
	Location         string
	Tags             []string
	Assessment       []byte
	Detail           []byte
	Generation       []byte
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

func (q *Queries) InsertHypothesis(ctx context.Context, arg InsertHypothesisParams) error {
	_, err := q.db.Exec(ctx, insertHypothesis,
		arg.ID,
		arg.OwnerID,
		arg.RunID,
		arg.Title,
		arg.Statement,
		arg.Rationale,
		arg.Method,
		arg.Status,
		arg.KpiID,
		arg.PrimaryClusterID,
		arg.Trl,
		arg.NoveltyScore,
		arg.RiskScore,
		arg.ValueScore,
		arg.ConfidenceScore,
		arg.CompositeScore,
		arg.Measurable,
		arg.Organization,
		arg.FunctionArea,
		arg.SourceType,
		arg.Location,
		arg.Tags,
		arg.Assessment,
		arg.Detail,
		arg.Generation,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertRevision = `-- name: InsertRevision :one
INSERT INTO hypothesis_revisions
  (id, hypothesis_id, revision_no, editor_id, action, summary, patch, created_at)
VALUES ($1, $2,
        (SELECT COALESCE(MAX(revision_no), 0) + 1 FROM hypothesis_revisions WHERE hypothesis_id = $2),
        $3, $4, $5, $6, $7)
RETURNING revision_no
`

type InsertRevisionParams struct {
	ID           string
	HypothesisID string
	EditorID     string
	Action       string
	Summary      string
	Patch        []byte
	CreatedAt    time.Time
}

func (q *Queries) InsertRevision(ctx context.Context, arg InsertRevisionParams) (int32, error) {
	row := q.db.QueryRow(ctx, insertRevision,
		arg.ID,
		arg.HypothesisID,
		arg.EditorID,
		arg.Action,
		arg.Summary,
		arg.Patch,
		arg.CreatedAt,
	)
	var revision_no int32
	err := row.Scan(&revision_no)
	return revision_no, err
}

const listEvidenceByHypothesis = `-- name: ListEvidenceByHypothesis :many
SELECT id, hypothesis_id, document_id, chunk_id, filename, snippet, stance, score, ord, created_at, relation, page_start, page_end, section_heading, origin FROM hypothesis_evidence WHERE hypothesis_id = $1 ORDER BY ord ASC
`

func (q *Queries) ListEvidenceByHypothesis(ctx context.Context, hypothesisID string) ([]HypothesisEvidence, error) {
	rows, err := q.db.Query(ctx, listEvidenceByHypothesis, hypothesisID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HypothesisEvidence{}
	for rows.Next() {
		var i HypothesisEvidence
		if err := rows.Scan(
			&i.ID,
			&i.HypothesisID,
			&i.DocumentID,
			&i.ChunkID,
			&i.Filename,
			&i.Snippet,
			&i.Stance,
			&i.Score,
			&i.Ord,
			&i.CreatedAt,
			&i.Relation,
			&i.PageStart,
			&i.PageEnd,
			&i.SectionHeading,
			&i.Origin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHypotheses = `-- name: ListHypotheses :many
SELECT id, owner_id, run_id, title, statement, rationale, method, status, kpi_id, primary_cluster_id, trl, novelty_score, risk_score, value_score, confidence_score, composite_score, measurable, organization, function_area, source_type, location, tags, assessment, detail, generation, created_at, updated_at FROM hypotheses
WHERE ($1::text = '' OR owner_id = $1)
  AND ($2::text = '' OR status = $2)
  AND ($3::text = '' OR kpi_id = $3)
  AND ($4::text = '' OR primary_cluster_id = $4)
  AND ($5::text = '' OR function_area = $5)
  AND ($6::text = '' OR source_type = $6)
  AND ($7::text = '' OR organization = $7)
  AND ($8::int = 0 OR trl >= $8::int)
  AND ($9::int = 0 OR trl <= $9::int)
  AND (cardinality($10::text[]) = 0 OR tags @> $10::text[])
  AND (cardinality($11::text[]) = 0 OR EXISTS (
    SELECT 1 FROM hypothesis_evidence e
    WHERE e.hypothesis_id = hypotheses.id
      AND e.document_id = ANY($11::text[])))
ORDER BY
  CASE WHEN $12::text = 'created_at' THEN extract(epoch FROM created_at) END DESC NULLS LAST,
  CASE WHEN $12::text = 'trl' THEN trl::double precision END DESC NULLS LAST,
  CASE WHEN $12::text = 'novelty' THEN novelty_score END DESC NULLS LAST,
  CASE WHEN $12::text = 'value' THEN value_score END DESC NULLS LAST,
  CASE WHEN $12::text NOT IN ('created_at', 'trl', 'novelty', 'value')
       THEN composite_score END DESC NULLS LAST,
  created_at DESC
LIMIT CASE WHEN $14::int <= 0 THEN NULL ELSE $14::int END
OFFSET $13::int
`

type ListHypothesesParams struct {
	OwnerID      string
	Status       string
	KpiID        string
	ClusterID    string
	FunctionArea string
	SourceType   string
	Organization string
	MinTrl       int32
	MaxTrl       int32
	Tags         []string
	DocumentIds  []string
	OrderBy      string
	Off          int32
	Lim          int32
}

func (q *Queries) ListHypotheses(ctx context.Context, arg ListHypothesesParams) ([]Hypothesis, error) {
	rows, err := q.db.Query(ctx, listHypotheses,
		arg.OwnerID,
		arg.Status,
		arg.KpiID,
		arg.ClusterID,
		arg.FunctionArea,
		arg.SourceType,
		arg.Organization,
		arg.MinTrl,
		arg.MaxTrl,
		arg.Tags,
		arg.DocumentIds,
		arg.OrderBy,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Hypothesis{}
	for rows.Next() {
		var i Hypothesis
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.RunID,
			&i.Title,
			&i.Statement,
			&i.Rationale,
			&i.Method,
			&i.Status,
			&i.KpiID,
			&i.PrimaryClusterID,
			&i.Trl,
			&i.NoveltyScore,
			&i.RiskScore,
			&i.ValueScore,
			&i.ConfidenceScore,
			&i.CompositeScore,
			&i.Measurable,
			&i.Organization,
			&i.FunctionArea,
			&i.SourceType,
			&i.Location,
			&i.Tags,
			&i.Assessment,
			&i.Detail,
			&i.Generation,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRevisionsByHypothesis = `-- name: ListRevisionsByHypothesis :many
SELECT id, hypothesis_id, revision_no, editor_id, action, summary, patch, created_at FROM hypothesis_revisions WHERE hypothesis_id = $1 ORDER BY revision_no ASC
`

func (q *Queries) ListRevisionsByHypothesis(ctx context.Context, hypothesisID string) ([]HypothesisRevision, error) {
	rows, err := q.db.Query(ctx, listRevisionsByHypothesis, hypothesisID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HypothesisRevision{}
	for rows.Next() {
		var i HypothesisRevision
		if err := rows.Scan(
			&i.ID,
			&i.HypothesisID,
			&i.RevisionNo,
			&i.EditorID,
			&i.Action,
			&i.Summary,
			&i.Patch,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHypothesis = `-- name: UpdateHypothesis :execrows
UPDATE hypotheses
SET title = $2, statement = $3, rationale = $4, method = $5, status = $6,
    kpi_id = $7, primary_cluster_id = $8, trl = $9, novelty_score = $10,
    risk_score = $11, value_score = $12, confidence_score = $13, composite_score = $14,
    measurable = $15, organization = $16, function_area = $17, source_type = $18,
    location = $19, tags = $20, assessment = $21, detail = $22, generation = $23,
    updated_at = now()
WHERE id = $1
`

type UpdateHypothesisParams struct {
	ID               string
	Title            string
	Statement        string
	Rationale        string
	Method           string
	Status           string
	KpiID            *string
	PrimaryClusterID *string
	Trl              *int16
	NoveltyScore     *float64
	RiskScore        *float64
	ValueScore       *float64
	ConfidenceScore  *float64
	CompositeScore   *float64
	Measurable       bool
	Organization     string
	FunctionArea     string
	SourceType       string
	Location         string
	Tags             []string
	Assessment       []byte
	Detail           []byte
	Generation       []byte
}

func (q *Queries) UpdateHypothesis(ctx context.Context, arg UpdateHypothesisParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateHypothesis,
		arg.ID,
		arg.Title,
		arg.Statement,
		arg.Rationale,
		arg.Method,
		arg.Status,
		arg.KpiID,
		arg.PrimaryClusterID,
		arg.Trl,
		arg.NoveltyScore,
		arg.RiskScore,
		arg.ValueScore,
		arg.ConfidenceScore,
		arg.CompositeScore,
		arg.Measurable,
		arg.Organization,
		arg.FunctionArea,
		arg.SourceType,
		arg.Location,
		arg.Tags,
		arg.Assessment,
		arg.Detail,
		arg.Generation,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
