// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: kpi_documents.sql

package sqlcgen

import (
	"context"
	"time"
)

const attachKpiDocument = `-- name: AttachKpiDocument :exec
INSERT INTO kpi_documents (kpi_id, document_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (kpi_id, document_id) DO UPDATE SET role = EXCLUDED.role
`

type AttachKpiDocumentParams struct {
	KpiID      string
	DocumentID string
	Role       string
}

func (q *Queries) AttachKpiDocument(ctx context.Context, arg AttachKpiDocumentParams) error {
	_, err := q.db.Exec(ctx, attachKpiDocument, arg.KpiID, arg.DocumentID, arg.Role)
	return err
}

const detachKpiDocument = `-- name: DetachKpiDocument :exec
DELETE FROM kpi_documents WHERE kpi_id = $1 AND document_id = $2
`

type DetachKpiDocumentParams struct {
	KpiID      string
	DocumentID string
}

func (q *Queries) DetachKpiDocument(ctx context.Context, arg DetachKpiDocumentParams) error {
	_, err := q.db.Exec(ctx, detachKpiDocument, arg.KpiID, arg.DocumentID)
	return err
}

const listKpiDocuments = `-- name: ListKpiDocuments :many
SELECT d.id, d.owner_id, d.filename, d.mime_type, d.size, d.object_key, d.status, d.status_msg, d.chunk_count, d.created_at, d.updated_at, d.content_hash, d.title, d.author, d.published_at, d.source_ref, d.kind, kd.role, kd.created_at AS attached_at
FROM kpi_documents kd
JOIN documents d ON d.id = kd.document_id
WHERE kd.kpi_id = $1
ORDER BY kd.created_at ASC
`

type ListKpiDocumentsRow struct {
	Document   Document
	Role       string
	AttachedAt time.Time
}

func (q *Queries) ListKpiDocuments(ctx context.Context, kpiID string) ([]ListKpiDocumentsRow, error) {
	rows, err := q.db.Query(ctx, listKpiDocuments, kpiID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListKpiDocumentsRow{}
	for rows.Next() {
		var i ListKpiDocumentsRow
		if err := rows.Scan(
			&i.Document.ID,
			&i.Document.OwnerID,
			&i.Document.Filename,
			&i.Document.MimeType,
			&i.Document.Size,
			&i.Document.ObjectKey,
			&i.Document.Status,
			&i.Document.StatusMsg,
			&i.Document.ChunkCount,
			&i.Document.CreatedAt,
			&i.Document.UpdatedAt,
			&i.Document.ContentHash,
			&i.Document.Title,
			&i.Document.Author,
			&i.Document.PublishedAt,
			&i.Document.SourceRef,
			&i.Document.Kind,
			&i.Role,
			&i.AttachedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
