// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: kpis.sql

package sqlcgen

import (
	"context"
	"time"
)

const createKPI = `-- name: CreateKPI :exec
INSERT INTO kpis
  (id, owner_id, title, description, metric, unit, direction, baseline, target,
   function_area, status, detail, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
`

type CreateKPIParams struct {
	ID           string
	OwnerID      string
	Title        string
	Description  string
	Metric       string
	Unit         string
	Direction    string
	Baseline     *float64
	Target       *float64
	FunctionArea string
	Status       string
	Detail       []byte
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) CreateKPI(ctx context.Context, arg CreateKPIParams) error {
	_, err := q.db.Exec(ctx, createKPI,
		arg.ID,
		arg.OwnerID,
		arg.Title,
		arg.Description,
		arg.Metric,
		arg.Unit,
		arg.Direction,
		arg.Baseline,
		arg.Target,
		arg.FunctionArea,
		arg.Status,
		arg.Detail,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteKPI = `-- name: DeleteKPI :execrows
DELETE FROM kpis WHERE id = $1
`

func (q *Queries) DeleteKPI(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteKPI, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getKPI = `-- name: GetKPI :one
SELECT id, owner_id, title, description, metric, unit, direction, baseline, target, function_area, status, detail, created_at, updated_at FROM kpis WHERE id = $1
`

func (q *Queries) GetKPI(ctx context.Context, id string) (Kpi, error) {
	row := q.db.QueryRow(ctx, getKPI, id)
	var i Kpi
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.Metric,
		&i.Unit,
		&i.Direction,
		&i.Baseline,
		&i.Target,
		&i.FunctionArea,
		&i.Status,
		&i.Detail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listKPIsByOwner = `-- name: ListKPIsByOwner :many
SELECT id, owner_id, title, description, metric, unit, direction, baseline, target, function_area, status, detail, created_at, updated_at FROM kpis WHERE owner_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListKPIsByOwner(ctx context.Context, ownerID string) ([]Kpi, error) {
	rows, err := q.db.Query(ctx, listKPIsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Kpi{}
	for rows.Next() {
		var i Kpi
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.Description,
			&i.Metric,
			&i.Unit,
			&i.Direction,
			&i.Baseline,
			&i.Target,
			&i.FunctionArea,
			&i.Status,
			&i.Detail,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateKPI = `-- name: UpdateKPI :execrows
UPDATE kpis
SET title = $2, description = $3, metric = $4, unit = $5, direction = $6,
    baseline = $7, target = $8, function_area = $9, status = $10, detail = $11,
    updated_at = now()
WHERE id = $1
`

type UpdateKPIParams struct {
	ID           string
	Title        string
	Description  string
	Metric       string
	Unit         string
	Direction    string
	Baseline     *float64
	Target       *float64
	FunctionArea string
	Status       string
	Detail       []byte
}

func (q *Queries) UpdateKPI(ctx context.Context, arg UpdateKPIParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateKPI,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Metric,
		arg.Unit,
		arg.Direction,
		arg.Baseline,
		arg.Target,
		arg.FunctionArea,
		arg.Status,
		arg.Detail,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
