// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: llm_usage.sql

package sqlcgen

import (
	"context"
	"time"
)

const listLLMUsageDaily = `-- name: ListLLMUsageDaily :many
SELECT day, model, operation, requests, prompt_tokens, completion_tokens, cost_nano_usd
FROM llm_usage_daily
WHERE day >= $1 AND day <= $2
ORDER BY day, model, operation
`

type ListLLMUsageDailyParams struct {
	FromDay time.Time
	ToDay   time.Time
}

type ListLLMUsageDailyRow struct {
	Day              time.Time
	Model            string
	Operation        string
	Requests         int64
	PromptTokens     int64
	CompletionTokens int64
	CostNanoUsd      int64
}

// The durable ledger for a date range, oldest first, for the Metrics dashboard.
func (q *Queries) ListLLMUsageDaily(ctx context.Context, arg ListLLMUsageDailyParams) ([]ListLLMUsageDailyRow, error) {
	rows, err := q.db.Query(ctx, listLLMUsageDaily, arg.FromDay, arg.ToDay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLLMUsageDailyRow{}
	for rows.Next() {
		var i ListLLMUsageDailyRow
		if err := rows.Scan(
			&i.Day,
			&i.Model,
			&i.Operation,
			&i.Requests,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.CostNanoUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setLLMUsageDaily = `-- name: SetLLMUsageDaily :exec
INSERT INTO llm_usage_daily
  (day, model, operation, requests, prompt_tokens, completion_tokens, cost_nano_usd, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, now())
ON CONFLICT (day, model, operation) DO UPDATE SET
  requests          = excluded.requests,
  prompt_tokens     = excluded.prompt_tokens,
  completion_tokens = excluded.completion_tokens,
  cost_nano_usd     = excluded.cost_nano_usd,
  updated_at        = now()
`

type SetLLMUsageDailyParams struct {
	Day              time.Time
	Model            string
	Operation        string
	Requests         int64
	PromptTokens     int64
	CompletionTokens int64
	CostNanoUsd      int64
}

// Mirror the running daily total for one (day, model, operation) from the Valkey
// hot-hash into the durable ledger. SET (not add) on conflict so re-flushing the
// same day is idempotent — Valkey holds the authoritative running total.
func (q *Queries) SetLLMUsageDaily(ctx context.Context, arg SetLLMUsageDailyParams) error {
	_, err := q.db.Exec(ctx, setLLMUsageDaily,
		arg.Day,
		arg.Model,
		arg.Operation,
		arg.Requests,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.CostNanoUsd,
	)
	return err
}
