// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: models.sql

package sqlcgen

import (
	"context"
)

const listModels = `-- name: ListModels :many
SELECT id, name, role, backend FROM models ORDER BY id
`

func (q *Queries) ListModels(ctx context.Context) ([]Model, error) {
	rows, err := q.db.Query(ctx, listModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Model{}
	for rows.Next() {
		var i Model
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Role,
			&i.Backend,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertModel = `-- name: UpsertModel :exec
INSERT INTO models (id, name, role, backend) VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE
  SET name = EXCLUDED.name, role = EXCLUDED.role, backend = EXCLUDED.backend
`

type UpsertModelParams struct {
	ID      string
	Name    string
	Role    string
	Backend string
}

func (q *Queries) UpsertModel(ctx context.Context, arg UpsertModelParams) error {
	_, err := q.db.Exec(ctx, upsertModel,
		arg.ID,
		arg.Name,
		arg.Role,
		arg.Backend,
	)
	return err
}
