// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"
)

type AppSetting struct {
	Key       string
	Value     string
	UpdatedAt time.Time
}

type Chat struct {
	ID        string
	OwnerID   string
	Title     string
	CreatedAt time.Time
	Source    string
}

type ChatMessage struct {
	ID        string
	ChatID    string
	Role      string
	Content   string
	Sources   []byte
	CreatedAt time.Time
	Meta      []byte
}

type Cluster struct {
	ID              string
	OwnerID         string
	Label           string
	Summary         string
	Keywords        []string
	Method          string
	ChunkCount      int32
	DocumentCount   int32
	Representatives []byte
	Params          []byte
	Status          string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type Document struct {
	ID          string
	OwnerID     string
	Filename    string
	MimeType    string
	Size        int64
	ObjectKey   string
	Status      string
	StatusMsg   string
	ChunkCount  int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
	ContentHash string
	Title       string
	Author      string
	PublishedAt string
	SourceRef   string
	Kind        string
}

type Hypothesis struct {
	ID               string
	OwnerID          string
	RunID            string
	Title            string
	Statement        string
	Rationale        string
	Method           string
	Status           string
	KpiID            *string
	PrimaryClusterID *string
	Trl              *int16
	NoveltyScore     *float64
	RiskScore        *float64
	ValueScore       *float64
	ConfidenceScore  *float64
	CompositeScore   *float64
	Measurable       bool
	Organization     string
	FunctionArea     string
	SourceType       string
	Location         string
	Tags             []string
	Assessment       []byte
	Detail           []byte
	Generation       []byte
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type HypothesisEvidence struct {
	ID             string
	HypothesisID   string
	DocumentID     *string
	ChunkID        string
	Filename       string
	Snippet        string
	Stance         string
	Score          *float64
	Ord            int32
	CreatedAt      time.Time
	Relation       string
	PageStart      int32
	PageEnd        int32
	SectionHeading string
	Origin         string
}

type HypothesisRevision struct {
	ID           string
	HypothesisID string
	RevisionNo   int32
	EditorID     string
	Action       string
	Summary      string
	Patch        []byte
	CreatedAt    time.Time
}

type Kpi struct {
	ID           string
	OwnerID      string
	Title        string
	Description  string
	Metric       string
	Unit         string
	Direction    string
	Baseline     *float64
	Target       *float64
	FunctionArea string
	Status       string
	Detail       []byte
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type KpiDocument struct {
	KpiID      string
	DocumentID string
	Role       string
	CreatedAt  time.Time
}

type LlmUsageDaily struct {
	Day              time.Time
	Model            string
	Operation        string
	Requests         int64
	PromptTokens     int64
	CompletionTokens int64
	CostNanoUsd      int64
	UpdatedAt        time.Time
}

type Model struct {
	ID      string
	Name    string
	Role    string
	Backend string
}

type User struct {
	ID           string
	Username     string
	PasswordHash string
	Roles        []string
	CreatedAt    time.Time
}
