// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	AddMessage(ctx context.Context, arg AddMessageParams) error
	AttachKpiDocument(ctx context.Context, arg AttachKpiDocumentParams) error
	CountChats(ctx context.Context) (int64, error)
	CountChatsByOwner(ctx context.Context, ownerID string) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateChat(ctx context.Context, arg CreateChatParams) error
	CreateCluster(ctx context.Context, arg CreateClusterParams) error
	CreateDocument(ctx context.Context, arg CreateDocumentParams) error
	CreateKPI(ctx context.Context, arg CreateKPIParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteAppSetting(ctx context.Context, key string) error
	DeleteClustersByOwner(ctx context.Context, ownerID string) (int64, error)
	DeleteKPI(ctx context.Context, id string) (int64, error)
	DetachKpiDocument(ctx context.Context, arg DetachKpiDocumentParams) error
	FindDocumentByHash(ctx context.Context, arg FindDocumentByHashParams) (Document, error)
	GetChat(ctx context.Context, id string) (Chat, error)
	GetCluster(ctx context.Context, id string) (Cluster, error)
	GetDocument(ctx context.Context, id string) (Document, error)
	GetHypothesis(ctx context.Context, id string) (Hypothesis, error)
	GetKPI(ctx context.Context, id string) (Kpi, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	InsertEvidence(ctx context.Context, arg InsertEvidenceParams) error
	InsertHypothesis(ctx context.Context, arg InsertHypothesisParams) error
	InsertRevision(ctx context.Context, arg InsertRevisionParams) (int32, error)
	ListAppSettings(ctx context.Context) ([]AppSetting, error)
	ListChatsAll(ctx context.Context, arg ListChatsAllParams) ([]ListChatsAllRow, error)
	ListChatsByOwner(ctx context.Context, arg ListChatsByOwnerParams) ([]ListChatsByOwnerRow, error)
	ListClustersByOwner(ctx context.Context, ownerID string) ([]Cluster, error)
	ListDocumentsByOwner(ctx context.Context, ownerID string) ([]Document, error)
	ListEvidenceByHypothesis(ctx context.Context, hypothesisID string) ([]HypothesisEvidence, error)
	ListHypotheses(ctx context.Context, arg ListHypothesesParams) ([]Hypothesis, error)
	ListKPIsByOwner(ctx context.Context, ownerID string) ([]Kpi, error)
	ListKpiDocuments(ctx context.Context, kpiID string) ([]ListKpiDocumentsRow, error)
	// The durable ledger for a date range, oldest first, for the Metrics dashboard.
	ListLLMUsageDaily(ctx context.Context, arg ListLLMUsageDailyParams) ([]ListLLMUsageDailyRow, error)
	ListMessagesByChat(ctx context.Context, chatID string) ([]ChatMessage, error)
	ListModels(ctx context.Context) ([]Model, error)
	ListRevisionsByHypothesis(ctx context.Context, hypothesisID string) ([]HypothesisRevision, error)
	ListUsers(ctx context.Context) ([]User, error)
	// Mirror the running daily total for one (day, model, operation) from the Valkey
	// hot-hash into the durable ledger. SET (not add) on conflict so re-flushing the
	// same day is idempotent — Valkey holds the authoritative running total.
	SetLLMUsageDaily(ctx context.Context, arg SetLLMUsageDailyParams) error
	UpdateCluster(ctx context.Context, arg UpdateClusterParams) (int64, error)
	UpdateDocumentKind(ctx context.Context, arg UpdateDocumentKindParams) error
	UpdateDocumentMeta(ctx context.Context, arg UpdateDocumentMetaParams) error
	UpdateDocumentStatus(ctx context.Context, arg UpdateDocumentStatusParams) error
	UpdateDocumentTitle(ctx context.Context, arg UpdateDocumentTitleParams) error
	UpdateHypothesis(ctx context.Context, arg UpdateHypothesisParams) (int64, error)
	UpdateKPI(ctx context.Context, arg UpdateKPIParams) (int64, error)
	UpsertAppSetting(ctx context.Context, arg UpsertAppSettingParams) error
	UpsertModel(ctx context.Context, arg UpsertModelParams) error
}

var _ Querier = (*Queries)(nil)
