// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: common/v1/common.proto

// Package rag.common.v1 holds every type that crosses a service boundary: the
// DTOs returned by db-service, the RAG request/response, and the ingestion
// events that travel as protobuf binary over RabbitMQ. Timestamps are RFC3339
// strings and statuses are strings (mirroring the DB) to keep JSON at the REST
// edge stable and avoid enum<->string churn.

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	PasswordHash  string                 `protobuf:"bytes,3,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"` // populated only on the internal credential lookup
	Roles         []string               `protobuf:"bytes,4,rep,name=roles,proto3" json:"roles,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_common_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

func (x *User) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *User) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type Document struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Id         string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId    string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Filename   string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	MimeType   string                 `protobuf:"bytes,4,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Size       int64                  `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	ObjectKey  string                 `protobuf:"bytes,6,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	Status     string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	StatusMsg  string                 `protobuf:"bytes,8,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
	ChunkCount int32                  `protobuf:"varint,9,opt,name=chunk_count,json=chunkCount,proto3" json:"chunk_count,omitempty"`
	CreatedAt  string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt  string                 `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// BLAKE3-256 hex содержимого файла — основа дедупликации: совпадающий хеш
	// означает байт-в-байт тот же документ, и он не индексируется повторно.
	ContentHash string `protobuf:"bytes,12,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	// Настоящее название статьи, извлечённое из текста при индексации (LLM).
	// Пустая строка — заголовок ещё не извлечён; UI показывает имя файла.
	Title string `protobuf:"bytes,13,opt,name=title,proto3" json:"title,omitempty"`
	// Метаданные из парсера (email-заголовки, PDF docinfo); "" — не извлечено.
	Author      string `protobuf:"bytes,14,opt,name=author,proto3" json:"author,omitempty"`
	PublishedAt string `protobuf:"bytes,15,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	SourceRef   string `protobuf:"bytes,16,opt,name=source_ref,json=sourceRef,proto3" json:"source_ref,omitempty"`
	// Класс документа, определённый при индексации: "" — обычный документ,
	// "hypotheses" — готовые гипотезы/идеи (итоги мозгового штурма). Такие
	// документы не участвуют в retrieval генерации и проверки гипотез.
	Kind          string `protobuf:"bytes,17,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_common_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *Document) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Document) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Document) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Document) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *Document) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Document) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *Document) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Document) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *Document) GetChunkCount() int32 {
	if x != nil {
		return x.ChunkCount
	}
	return 0
}

func (x *Document) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Document) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Document) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

func (x *Document) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Document) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Document) GetPublishedAt() string {
	if x != nil {
		return x.PublishedAt
	}
	return ""
}

func (x *Document) GetSourceRef() string {
	if x != nil {
		return x.SourceRef
	}
	return ""
}

func (x *Document) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type Chat struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId   string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Title     string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	CreatedAt string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Page the conversation started from ("search"); "" on legacy rows.
	Source string `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	// Owner username resolved on reads for history views; not stored on the row.
	OwnerUsername string `protobuf:"bytes,6,opt,name=owner_username,json=ownerUsername,proto3" json:"owner_username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chat) Reset() {
	*x = Chat{}
	mi := &file_common_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chat) ProtoMessage() {}

func (x *Chat) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chat.ProtoReflect.Descriptor instead.
func (*Chat) Descriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *Chat) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Chat) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Chat) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Chat) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Chat) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Chat) GetOwnerUsername() string {
	if x != nil {
		return x.OwnerUsername
	}
	return ""
}

type Source struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	DocumentId string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Filename   string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	ChunkId    string                 `protobuf:"bytes,3,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	Snippet    string                 `protobuf:"bytes,4,opt,name=snippet,proto3" json:"snippet,omitempty"`
	Score      float64                `protobuf:"fixed64,5,opt,name=score,proto3" json:"score,omitempty"`
	// Span provenance for grounded citations. char_start/char_end are 0-based
	// [start, end) rune offsets of the chunk within the document's extracted text,
	// populated by chunk-splitter (which owns the splitting and therefore the
	// offsets). page_start/page_end and section_heading are reserved for
	// structured-parse output and stay 0 / "" until a parser supplies document
	// structure. All additive (fields 6-10) — old payloads simply read as zero.
	CharStart      int32  `protobuf:"varint,6,opt,name=char_start,json=charStart,proto3" json:"char_start,omitempty"`
	CharEnd        int32  `protobuf:"varint,7,opt,name=char_end,json=charEnd,proto3" json:"char_end,omitempty"`
	PageStart      int32  `protobuf:"varint,8,opt,name=page_start,json=pageStart,proto3" json:"page_start,omitempty"`
	PageEnd        int32  `protobuf:"varint,9,opt,name=page_end,json=pageEnd,proto3" json:"page_end,omitempty"`
	SectionHeading string `protobuf:"bytes,10,opt,name=section_heading,json=sectionHeading,proto3" json:"section_heading,omitempty"`
	// Retrieval provenance (additive): which retriever surfaced the chunk
	// ("dense" | "bm25" | "both") and, when the chunk was materialized by
	// expanding a RAPTOR summary node, the id of that summary point.
	Origin          string `protobuf:"bytes,11,opt,name=origin,proto3" json:"origin,omitempty"`
	RaptorSummaryId string `protobuf:"bytes,12,opt,name=raptor_summary_id,json=raptorSummaryId,proto3" json:"raptor_summary_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Source) Reset() {
	*x = Source{}
	mi := &file_common_v1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Source) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Source) ProtoMessage() {}

func (x *Source) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Source.ProtoReflect.Descriptor instead.
func (*Source) Descriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *Source) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *Source) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Source) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *Source) GetSnippet() string {
	if x != nil {
		return x.Snippet
	}
	return ""
}

func (x *Source) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Source) GetCharStart() int32 {
	if x != nil {
		return x.CharStart
	}
	return 0
}

func (x *Source) GetCharEnd() int32 {
	if x != nil {
		return x.CharEnd
	}
	return 0
}

func (x *Source) GetPageStart() int32 {
	if x != nil {
		return x.PageStart
	}
	return 0
}

func (x *Source) GetPageEnd() int32 {
	if x != nil {
		return x.PageEnd
	}
	return 0
}

func (x *Source) GetSectionHeading() string {
	if x != nil {
		return x.SectionHeading
	}
	return ""
}

func (x *Source) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *Source) GetRaptorSummaryId() string {
	if x != nil {
		return x.RaptorSummaryId
	}
	return ""
}

type Message struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ChatId    string                 `protobuf:"bytes,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Role      string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	Content   string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Sources   []*Source              `protobuf:"bytes,5,rep,name=sources,proto3" json:"sources,omitempty"`
	CreatedAt string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Raw-JSON envelope for answer provenance ({model, cached, trace}), stored
	// as chat_messages.meta; "" for user messages and legacy rows.
	Meta          string `protobuf:"bytes,7,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_common_v1_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{4}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetSources() []*Source {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *Message) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Message) GetMeta() string {
	if x != nil {
		return x.Meta
	}
	return ""
}

type Model struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	Backend       string                 `protobuf:"bytes,4,opt,name=backend,proto3" json:"backend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Model) Reset() {
	*x = Model{}
	mi := &file_common_v1_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Model) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Model) ProtoMessage() {}

func (x *Model) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Model.ProtoReflect.Descriptor instead.
func (*Model) Descriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{5}
}

func (x *Model) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Model) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Model) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Model) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

type DocumentUploaded struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	DocumentId string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	OwnerId    string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	ObjectKey  string                 `protobuf:"bytes,3,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	Filename   string                 `protobuf:"bytes,4,opt,name=filename,proto3" json:"filename,omitempty"`
	MimeType   string                 `protobuf:"bytes,5,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Size       int64                  `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`
	TraceId    string                 `protobuf:"bytes,7,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// Глубина вложенности для документов, извлечённых из архивов: 0 — обычная
	// загрузка, 1 — файл из архива, 2 — файл из архива внутри архива.
	// archive-worker не распаковывает архивы глубже двух уровней.
	ArchiveDepth  int32 `protobuf:"varint,8,opt,name=archive_depth,json=archiveDepth,proto3" json:"archive_depth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentUploaded) Reset() {
	*x = DocumentUploaded{}
	mi := &file_common_v1_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentUploaded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentUploaded) ProtoMessage() {}

func (x *DocumentUploaded) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentUploaded.ProtoReflect.Descriptor instead.
func (*DocumentUploaded) Descriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{6}
}

func (x *DocumentUploaded) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *DocumentUploaded) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *DocumentUploaded) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *DocumentUploaded) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *DocumentUploaded) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *DocumentUploaded) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *DocumentUploaded) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *DocumentUploaded) GetArchiveDepth() int32 {
	if x != nil {
		return x.ArchiveDepth
	}
	return 0
}

type DocumentParsed struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	DocumentId string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	OwnerId    string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	ObjectKey  string                 `protobuf:"bytes,3,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	Filename   string                 `protobuf:"bytes,4,opt,name=filename,proto3" json:"filename,omitempty"`
	MimeType   string                 `protobuf:"bytes,5,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Source     string                 `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"` // email|office|pdf|ocr|vlm|text
	Text       string                 `protobuf:"bytes,7,opt,name=text,proto3" json:"text,omitempty"`
	Metadata   map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TraceId    string                 `protobuf:"bytes,9,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// Claim check: when the extracted text is too large for an AMQP body, the
	// parser stores it in S3 and sends the object key instead of `text`.
	TextObjectKey string `protobuf:"bytes,10,opt,name=text_object_key,json=textObjectKey,proto3" json:"text_object_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentParsed) Reset() {
	*x = DocumentParsed{}
	mi := &file_common_v1_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentParsed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentParsed) ProtoMessage() {}

func (x *DocumentParsed) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentParsed.ProtoReflect.Descriptor instead.
func (*DocumentParsed) Descriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{7}
}

func (x *DocumentParsed) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *DocumentParsed) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *DocumentParsed) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *DocumentParsed) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *DocumentParsed) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *DocumentParsed) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *DocumentParsed) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *DocumentParsed) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *DocumentParsed) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *DocumentParsed) GetTextObjectKey() string {
	if x != nil {
		return x.TextObjectKey
	}
	return ""
}

type DocumentIndexed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	ChunkCount    int32                  `protobuf:"varint,3,opt,name=chunk_count,json=chunkCount,proto3" json:"chunk_count,omitempty"`
	TraceId       string                 `protobuf:"bytes,4,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentIndexed) Reset() {
	*x = DocumentIndexed{}
	mi := &file_common_v1_common_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentIndexed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentIndexed) ProtoMessage() {}

func (x *DocumentIndexed) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_common_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentIndexed.ProtoReflect.Descriptor instead.
func (*DocumentIndexed) Descriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{8}
}

func (x *DocumentIndexed) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *DocumentIndexed) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *DocumentIndexed) GetChunkCount() int32 {
	if x != nil {
		return x.ChunkCount
	}
	return 0
}

func (x *DocumentIndexed) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type IngestionEvent struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	DocumentId string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	OwnerId    string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Status     string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Message    string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp  string                 `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // RFC3339
	// Optional progress within the current stage (e.g. OCR pages, embed batches);
	// both stay 0 when a stage has no measurable progress.
	StageCurrent  int32 `protobuf:"varint,6,opt,name=stage_current,json=stageCurrent,proto3" json:"stage_current,omitempty"`
	StageTotal    int32 `protobuf:"varint,7,opt,name=stage_total,json=stageTotal,proto3" json:"stage_total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestionEvent) Reset() {
	*x = IngestionEvent{}
	mi := &file_common_v1_common_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestionEvent) ProtoMessage() {}

func (x *IngestionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_common_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestionEvent.ProtoReflect.Descriptor instead.
func (*IngestionEvent) Descriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{9}
}

func (x *IngestionEvent) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *IngestionEvent) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *IngestionEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *IngestionEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *IngestionEvent) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *IngestionEvent) GetStageCurrent() int32 {
	if x != nil {
		return x.StageCurrent
	}
	return 0
}

func (x *IngestionEvent) GetStageTotal() int32 {
	if x != nil {
		return x.StageTotal
	}
	return 0
}

type RagRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	OwnerId string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Query   string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	TopK    int32                  `protobuf:"varint,3,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	Stream  bool                   `protobuf:"varint,4,opt,name=stream,proto3" json:"stream,omitempty"`
	// Optional generation prompt. When set, retrieval/rerank use `query` (kept
	// short) while the LLM generates from `prompt` — so a long instruction (e.g.
	// hypothesis generation) does not inflate the reranker input.
	Prompt string `protobuf:"bytes,5,opt,name=prompt,proto3" json:"prompt,omitempty"`
	// Optional retrieval scope: restrict to / exclude these document ids.
	ScopeDocumentIds   []string `protobuf:"bytes,6,rep,name=scope_document_ids,json=scopeDocumentIds,proto3" json:"scope_document_ids,omitempty"`
	ExcludeDocumentIds []string `protobuf:"bytes,7,rep,name=exclude_document_ids,json=excludeDocumentIds,proto3" json:"exclude_document_ids,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RagRequest) Reset() {
	*x = RagRequest{}
	mi := &file_common_v1_common_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RagRequest) ProtoMessage() {}

func (x *RagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_common_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RagRequest.ProtoReflect.Descriptor instead.
func (*RagRequest) Descriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{10}
}

func (x *RagRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *RagRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *RagRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *RagRequest) GetStream() bool {
	if x != nil {
		return x.Stream
	}
	return false
}

func (x *RagRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *RagRequest) GetScopeDocumentIds() []string {
	if x != nil {
		return x.ScopeDocumentIds
	}
	return nil
}

func (x *RagRequest) GetExcludeDocumentIds() []string {
	if x != nil {
		return x.ExcludeDocumentIds
	}
	return nil
}

// One timed step of the answer pipeline ("embed", "retrieve", "rerank",
// "generate", "total").
type RagStage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stage         string                 `protobuf:"bytes,1,opt,name=stage,proto3" json:"stage,omitempty"`
	Millis        int64                  `protobuf:"varint,2,opt,name=millis,proto3" json:"millis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RagStage) Reset() {
	*x = RagStage{}
	mi := &file_common_v1_common_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RagStage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RagStage) ProtoMessage() {}

func (x *RagStage) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_common_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RagStage.ProtoReflect.Descriptor instead.
func (*RagStage) Descriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{11}
}

func (x *RagStage) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *RagStage) GetMillis() int64 {
	if x != nil {
		return x.Millis
	}
	return 0
}

// RagTrace explains how an answer was produced: stage timings, candidate
// counts at each funnel step, degradation/abstain reasons and the citation
// report. It exists so the UI can show "how we searched" instead of a black
// box; every field is already computed inside llm-service.
type RagTrace struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Stages             []*RagStage            `protobuf:"bytes,1,rep,name=stages,proto3" json:"stages,omitempty"`
	CandidatesDense    int32                  `protobuf:"varint,2,opt,name=candidates_dense,json=candidatesDense,proto3" json:"candidates_dense,omitempty"`          // from Qdrant
	CandidatesLexical  int32                  `protobuf:"varint,3,opt,name=candidates_lexical,json=candidatesLexical,proto3" json:"candidates_lexical,omitempty"`    // from OpenSearch BM25
	CandidatesFused    int32                  `protobuf:"varint,4,opt,name=candidates_fused,json=candidatesFused,proto3" json:"candidates_fused,omitempty"`          // after RRF
	CandidatesReturned int32                  `protobuf:"varint,5,opt,name=candidates_returned,json=candidatesReturned,proto3" json:"candidates_returned,omitempty"` // final top-k after cap-per-doc
	Degraded           bool                   `protobuf:"varint,6,opt,name=degraded,proto3" json:"degraded,omitempty"`                                               // one of the retrieval/rerank legs failed
	DegradedReason     string                 `protobuf:"bytes,7,opt,name=degraded_reason,json=degradedReason,proto3" json:"degraded_reason,omitempty"`              // "" | "reranker_unavailable" | "dense_unavailable" | "lexical_unavailable" | "embed_unavailable"
	AbstainReason      string                 `protobuf:"bytes,8,opt,name=abstain_reason,json=abstainReason,proto3" json:"abstain_reason,omitempty"`                 // "" | "no_sources" | "weak_evidence"
	TopScore           float64                `protobuf:"fixed64,9,opt,name=top_score,json=topScore,proto3" json:"top_score,omitempty"`                              // best rerank score before the floor check
	ScoreFloor         float64                `protobuf:"fixed64,10,opt,name=score_floor,json=scoreFloor,proto3" json:"score_floor,omitempty"`
	Cited              []string               `protobuf:"bytes,11,rep,name=cited,proto3" json:"cited,omitempty"`                                          // [Sn] markers actually present in the answer
	UncitedRemoved     []string               `protobuf:"bytes,12,rep,name=uncited_removed,json=uncitedRemoved,proto3" json:"uncited_removed,omitempty"`  // hallucinated markers stripped by the sanitizer
	RaptorExpanded     int32                  `protobuf:"varint,13,opt,name=raptor_expanded,json=raptorExpanded,proto3" json:"raptor_expanded,omitempty"` // summary nodes expanded into leaf chunks
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RagTrace) Reset() {
	*x = RagTrace{}
	mi := &file_common_v1_common_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RagTrace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RagTrace) ProtoMessage() {}

func (x *RagTrace) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_common_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RagTrace.ProtoReflect.Descriptor instead.
func (*RagTrace) Descriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{12}
}

func (x *RagTrace) GetStages() []*RagStage {
	if x != nil {
		return x.Stages
	}
	return nil
}

func (x *RagTrace) GetCandidatesDense() int32 {
	if x != nil {
		return x.CandidatesDense
	}
	return 0
}

func (x *RagTrace) GetCandidatesLexical() int32 {
	if x != nil {
		return x.CandidatesLexical
	}
	return 0
}

func (x *RagTrace) GetCandidatesFused() int32 {
	if x != nil {
		return x.CandidatesFused
	}
	return 0
}

func (x *RagTrace) GetCandidatesReturned() int32 {
	if x != nil {
		return x.CandidatesReturned
	}
	return 0
}

func (x *RagTrace) GetDegraded() bool {
	if x != nil {
		return x.Degraded
	}
	return false
}

func (x *RagTrace) GetDegradedReason() string {
	if x != nil {
		return x.DegradedReason
	}
	return ""
}

func (x *RagTrace) GetAbstainReason() string {
	if x != nil {
		return x.AbstainReason
	}
	return ""
}

func (x *RagTrace) GetTopScore() float64 {
	if x != nil {
		return x.TopScore
	}
	return 0
}

func (x *RagTrace) GetScoreFloor() float64 {
	if x != nil {
		return x.ScoreFloor
	}
	return 0
}

func (x *RagTrace) GetCited() []string {
	if x != nil {
		return x.Cited
	}
	return nil
}

func (x *RagTrace) GetUncitedRemoved() []string {
	if x != nil {
		return x.UncitedRemoved
	}
	return nil
}

func (x *RagTrace) GetRaptorExpanded() int32 {
	if x != nil {
		return x.RaptorExpanded
	}
	return 0
}

type RagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answer        string                 `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
	Sources       []*Source              `protobuf:"bytes,2,rep,name=sources,proto3" json:"sources,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Cached        bool                   `protobuf:"varint,4,opt,name=cached,proto3" json:"cached,omitempty"`
	Trace         *RagTrace              `protobuf:"bytes,5,opt,name=trace,proto3" json:"trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RagResponse) Reset() {
	*x = RagResponse{}
	mi := &file_common_v1_common_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RagResponse) ProtoMessage() {}

func (x *RagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_common_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RagResponse.ProtoReflect.Descriptor instead.
func (*RagResponse) Descriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{13}
}

func (x *RagResponse) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *RagResponse) GetSources() []*Source {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *RagResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *RagResponse) GetCached() bool {
	if x != nil {
		return x.Cached
	}
	return false
}

func (x *RagResponse) GetTrace() *RagTrace {
	if x != nil {
		return x.Trace
	}
	return nil
}

type KPI struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Metric        string                 `protobuf:"bytes,5,opt,name=metric,proto3" json:"metric,omitempty"` // measured quantity
	Unit          string                 `protobuf:"bytes,6,opt,name=unit,proto3" json:"unit,omitempty"`
	Direction     string                 `protobuf:"bytes,7,opt,name=direction,proto3" json:"direction,omitempty"`       // increase | decrease | maintain
	Baseline      *float64               `protobuf:"fixed64,8,opt,name=baseline,proto3,oneof" json:"baseline,omitempty"` // unset = unknown / qualitative
	Target        *float64               `protobuf:"fixed64,9,opt,name=target,proto3,oneof" json:"target,omitempty"`
	FunctionArea  string                 `protobuf:"bytes,10,opt,name=function_area,json=functionArea,proto3" json:"function_area,omitempty"`
	Status        string                 `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"` // active | archived
	Detail        string                 `protobuf:"bytes,12,opt,name=detail,proto3" json:"detail,omitempty"` // raw JSON object
	CreatedAt     string                 `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KPI) Reset() {
	*x = KPI{}
	mi := &file_common_v1_common_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KPI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KPI) ProtoMessage() {}

func (x *KPI) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_common_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KPI.ProtoReflect.Descriptor instead.
func (*KPI) Descriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{14}
}

func (x *KPI) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *KPI) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *KPI) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *KPI) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *KPI) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *KPI) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *KPI) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *KPI) GetBaseline() float64 {
	if x != nil && x.Baseline != nil {
		return *x.Baseline
	}
	return 0
}

func (x *KPI) GetTarget() float64 {
	if x != nil && x.Target != nil {
		return *x.Target
	}
	return 0
}

func (x *KPI) GetFunctionArea() string {
	if x != nil {
		return x.FunctionArea
	}
	return ""
}

func (x *KPI) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *KPI) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *KPI) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *KPI) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type Cluster struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId         string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Label           string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	Summary         string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	Keywords        []string               `protobuf:"bytes,5,rep,name=keywords,proto3" json:"keywords,omitempty"`
	Method          string                 `protobuf:"bytes,6,opt,name=method,proto3" json:"method,omitempty"`
	ChunkCount      int32                  `protobuf:"varint,7,opt,name=chunk_count,json=chunkCount,proto3" json:"chunk_count,omitempty"`
	DocumentCount   int32                  `protobuf:"varint,8,opt,name=document_count,json=documentCount,proto3" json:"document_count,omitempty"`
	Representatives string                 `protobuf:"bytes,9,opt,name=representatives,proto3" json:"representatives,omitempty"` // raw JSON array
	Params          string                 `protobuf:"bytes,10,opt,name=params,proto3" json:"params,omitempty"`                  // raw JSON object
	Status          string                 `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       string                 `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Cluster) Reset() {
	*x = Cluster{}
	mi := &file_common_v1_common_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cluster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cluster) ProtoMessage() {}

func (x *Cluster) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_common_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cluster.ProtoReflect.Descriptor instead.
func (*Cluster) Descriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{15}
}

func (x *Cluster) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Cluster) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Cluster) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Cluster) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Cluster) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

func (x *Cluster) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Cluster) GetChunkCount() int32 {
	if x != nil {
		return x.ChunkCount
	}
	return 0
}

func (x *Cluster) GetDocumentCount() int32 {
	if x != nil {
		return x.DocumentCount
	}
	return 0
}

func (x *Cluster) GetRepresentatives() string {
	if x != nil {
		return x.Representatives
	}
	return ""
}

func (x *Cluster) GetParams() string {
	if x != nil {
		return x.Params
	}
	return ""
}

func (x *Cluster) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Cluster) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Cluster) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type HypothesisEvidence struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	HypothesisId   string                 `protobuf:"bytes,2,opt,name=hypothesis_id,json=hypothesisId,proto3" json:"hypothesis_id,omitempty"`
	DocumentId     *string                `protobuf:"bytes,3,opt,name=document_id,json=documentId,proto3,oneof" json:"document_id,omitempty"` // unset once the source document is deleted
	ChunkId        string                 `protobuf:"bytes,4,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`                // Qdrant/OpenSearch id; "" = document-level
	Filename       string                 `protobuf:"bytes,5,opt,name=filename,proto3" json:"filename,omitempty"`
	Snippet        string                 `protobuf:"bytes,6,opt,name=snippet,proto3" json:"snippet,omitempty"`
	Stance         string                 `protobuf:"bytes,7,opt,name=stance,proto3" json:"stance,omitempty"` // supports | contradicts | context
	Score          *float64               `protobuf:"fixed64,8,opt,name=score,proto3,oneof" json:"score,omitempty"`
	Ord            int32                  `protobuf:"varint,9,opt,name=ord,proto3" json:"ord,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Relation       string                 `protobuf:"bytes,11,opt,name=relation,proto3" json:"relation,omitempty"`                     // how the fragment relates to the hypothesis (conditions → effect, with numbers)
	PageStart      int32                  `protobuf:"varint,12,opt,name=page_start,json=pageStart,proto3" json:"page_start,omitempty"` // 1-based page span in the source document; 0 = unknown
	PageEnd        int32                  `protobuf:"varint,13,opt,name=page_end,json=pageEnd,proto3" json:"page_end,omitempty"`
	SectionHeading string                 `protobuf:"bytes,14,opt,name=section_heading,json=sectionHeading,proto3" json:"section_heading,omitempty"` // enclosing section, when the parser supplied structure
	Origin         string                 `protobuf:"bytes,15,opt,name=origin,proto3" json:"origin,omitempty"`                                       // "" | input | knowledge | web
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HypothesisEvidence) Reset() {
	*x = HypothesisEvidence{}
	mi := &file_common_v1_common_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HypothesisEvidence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HypothesisEvidence) ProtoMessage() {}

func (x *HypothesisEvidence) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_common_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HypothesisEvidence.ProtoReflect.Descriptor instead.
func (*HypothesisEvidence) Descriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{16}
}

func (x *HypothesisEvidence) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HypothesisEvidence) GetHypothesisId() string {
	if x != nil {
		return x.HypothesisId
	}
	return ""
}

func (x *HypothesisEvidence) GetDocumentId() string {
	if x != nil && x.DocumentId != nil {
		return *x.DocumentId
	}
	return ""
}

func (x *HypothesisEvidence) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *HypothesisEvidence) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *HypothesisEvidence) GetSnippet() string {
	if x != nil {
		return x.Snippet
	}
	return ""
}

func (x *HypothesisEvidence) GetStance() string {
	if x != nil {
		return x.Stance
	}
	return ""
}

func (x *HypothesisEvidence) GetScore() float64 {
	if x != nil && x.Score != nil {
		return *x.Score
	}
	return 0
}

func (x *HypothesisEvidence) GetOrd() int32 {
	if x != nil {
		return x.Ord
	}
	return 0
}

func (x *HypothesisEvidence) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *HypothesisEvidence) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *HypothesisEvidence) GetPageStart() int32 {
	if x != nil {
		return x.PageStart
	}
	return 0
}

func (x *HypothesisEvidence) GetPageEnd() int32 {
	if x != nil {
		return x.PageEnd
	}
	return 0
}

func (x *HypothesisEvidence) GetSectionHeading() string {
	if x != nil {
		return x.SectionHeading
	}
	return ""
}

func (x *HypothesisEvidence) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

type HypothesisRevision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	HypothesisId  string                 `protobuf:"bytes,2,opt,name=hypothesis_id,json=hypothesisId,proto3" json:"hypothesis_id,omitempty"`
	RevisionNo    int32                  `protobuf:"varint,3,opt,name=revision_no,json=revisionNo,proto3" json:"revision_no,omitempty"` // assigned server-side on write
	EditorId      string                 `protobuf:"bytes,4,opt,name=editor_id,json=editorId,proto3" json:"editor_id,omitempty"`        // "" = system
	Action        string                 `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`                            // created | edited | status_changed | score_override | approved | rejected | commented
	Summary       string                 `protobuf:"bytes,6,opt,name=summary,proto3" json:"summary,omitempty"`
	Patch         string                 `protobuf:"bytes,7,opt,name=patch,proto3" json:"patch,omitempty"` // raw JSON object: {"before": ..., "after": ...}
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HypothesisRevision) Reset() {
	*x = HypothesisRevision{}
	mi := &file_common_v1_common_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HypothesisRevision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HypothesisRevision) ProtoMessage() {}

func (x *HypothesisRevision) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_common_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HypothesisRevision.ProtoReflect.Descriptor instead.
func (*HypothesisRevision) Descriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{17}
}

func (x *HypothesisRevision) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HypothesisRevision) GetHypothesisId() string {
	if x != nil {
		return x.HypothesisId
	}
	return ""
}

func (x *HypothesisRevision) GetRevisionNo() int32 {
	if x != nil {
		return x.RevisionNo
	}
	return 0
}

func (x *HypothesisRevision) GetEditorId() string {
	if x != nil {
		return x.EditorId
	}
	return ""
}

func (x *HypothesisRevision) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *HypothesisRevision) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *HypothesisRevision) GetPatch() string {
	if x != nil {
		return x.Patch
	}
	return ""
}

func (x *HypothesisRevision) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type Hypothesis struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId          string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	RunId            string                 `protobuf:"bytes,3,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Title            string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Statement        string                 `protobuf:"bytes,5,opt,name=statement,proto3" json:"statement,omitempty"`
	Rationale        string                 `protobuf:"bytes,6,opt,name=rationale,proto3" json:"rationale,omitempty"`
	Method           string                 `protobuf:"bytes,7,opt,name=method,proto3" json:"method,omitempty"` // cluster_kpi | transfer | gap | combination | manual
	Status           string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"` // draft | generated | under_review | approved | rejected | archived
	KpiId            *string                `protobuf:"bytes,9,opt,name=kpi_id,json=kpiId,proto3,oneof" json:"kpi_id,omitempty"`
	PrimaryClusterId *string                `protobuf:"bytes,10,opt,name=primary_cluster_id,json=primaryClusterId,proto3,oneof" json:"primary_cluster_id,omitempty"`
	Trl              *int32                 `protobuf:"varint,11,opt,name=trl,proto3,oneof" json:"trl,omitempty"` // 1..9
	NoveltyScore     *float64               `protobuf:"fixed64,12,opt,name=novelty_score,json=noveltyScore,proto3,oneof" json:"novelty_score,omitempty"`
	RiskScore        *float64               `protobuf:"fixed64,13,opt,name=risk_score,json=riskScore,proto3,oneof" json:"risk_score,omitempty"` // higher = riskier
	ValueScore       *float64               `protobuf:"fixed64,14,opt,name=value_score,json=valueScore,proto3,oneof" json:"value_score,omitempty"`
	ConfidenceScore  *float64               `protobuf:"fixed64,15,opt,name=confidence_score,json=confidenceScore,proto3,oneof" json:"confidence_score,omitempty"`
	CompositeScore   *float64               `protobuf:"fixed64,16,opt,name=composite_score,json=compositeScore,proto3,oneof" json:"composite_score,omitempty"` // ranking output
	Measurable       bool                   `protobuf:"varint,17,opt,name=measurable,proto3" json:"measurable,omitempty"`                                      // false = scientific hypothesis without a measurable effect
	Organization     string                 `protobuf:"bytes,18,opt,name=organization,proto3" json:"organization,omitempty"`
	FunctionArea     string                 `protobuf:"bytes,19,opt,name=function_area,json=functionArea,proto3" json:"function_area,omitempty"`
	SourceType       string                 `protobuf:"bytes,20,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	Location         string                 `protobuf:"bytes,21,opt,name=location,proto3" json:"location,omitempty"`
	Tags             []string               `protobuf:"bytes,22,rep,name=tags,proto3" json:"tags,omitempty"`
	Assessment       string                 `protobuf:"bytes,23,opt,name=assessment,proto3" json:"assessment,omitempty"` // raw JSON object
	Detail           string                 `protobuf:"bytes,24,opt,name=detail,proto3" json:"detail,omitempty"`         // raw JSON object
	Generation       string                 `protobuf:"bytes,25,opt,name=generation,proto3" json:"generation,omitempty"` // raw JSON object
	CreatedAt        string                 `protobuf:"bytes,26,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        string                 `protobuf:"bytes,27,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Evidence is populated by GetHypothesis and carried on CreateHypothesis;
	// ListHypotheses leaves it empty.
	Evidence      []*HypothesisEvidence `protobuf:"bytes,28,rep,name=evidence,proto3" json:"evidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hypothesis) Reset() {
	*x = Hypothesis{}
	mi := &file_common_v1_common_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hypothesis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hypothesis) ProtoMessage() {}

func (x *Hypothesis) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_common_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hypothesis.ProtoReflect.Descriptor instead.
func (*Hypothesis) Descriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{18}
}

func (x *Hypothesis) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Hypothesis) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Hypothesis) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *Hypothesis) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Hypothesis) GetStatement() string {
	if x != nil {
		return x.Statement
	}
	return ""
}

func (x *Hypothesis) GetRationale() string {
	if x != nil {
		return x.Rationale
	}
	return ""
}

func (x *Hypothesis) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Hypothesis) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Hypothesis) GetKpiId() string {
	if x != nil && x.KpiId != nil {
		return *x.KpiId
	}
	return ""
}

func (x *Hypothesis) GetPrimaryClusterId() string {
	if x != nil && x.PrimaryClusterId != nil {
		return *x.PrimaryClusterId
	}
	return ""
}

func (x *Hypothesis) GetTrl() int32 {
	if x != nil && x.Trl != nil {
		return *x.Trl
	}
	return 0
}

func (x *Hypothesis) GetNoveltyScore() float64 {
	if x != nil && x.NoveltyScore != nil {
		return *x.NoveltyScore
	}
	return 0
}

func (x *Hypothesis) GetRiskScore() float64 {
	if x != nil && x.RiskScore != nil {
		return *x.RiskScore
	}
	return 0
}

func (x *Hypothesis) GetValueScore() float64 {
	if x != nil && x.ValueScore != nil {
		return *x.ValueScore
	}
	return 0
}

func (x *Hypothesis) GetConfidenceScore() float64 {
	if x != nil && x.ConfidenceScore != nil {
		return *x.ConfidenceScore
	}
	return 0
}

func (x *Hypothesis) GetCompositeScore() float64 {
	if x != nil && x.CompositeScore != nil {
		return *x.CompositeScore
	}
	return 0
}

func (x *Hypothesis) GetMeasurable() bool {
	if x != nil {
		return x.Measurable
	}
	return false
}

func (x *Hypothesis) GetOrganization() string {
	if x != nil {
		return x.Organization
	}
	return ""
}

func (x *Hypothesis) GetFunctionArea() string {
	if x != nil {
		return x.FunctionArea
	}
	return ""
}

func (x *Hypothesis) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *Hypothesis) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Hypothesis) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Hypothesis) GetAssessment() string {
	if x != nil {
		return x.Assessment
	}
	return ""
}

func (x *Hypothesis) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *Hypothesis) GetGeneration() string {
	if x != nil {
		return x.Generation
	}
	return ""
}

func (x *Hypothesis) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Hypothesis) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Hypothesis) GetEvidence() []*HypothesisEvidence {
	if x != nil {
		return x.Evidence
	}
	return nil
}

var File_common_v1_common_proto protoreflect.FileDescriptor

const file_common_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x16common/v1/common.proto\x12\rrag.common.v1\"\x8c\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12#\n" +
	"\rpassword_hash\x18\x03 \x01(\tR\fpasswordHash\x12\x14\n" +
	"\x05roles\x18\x04 \x03(\tR\x05roles\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"\xde\x03\n" +
	"\bDocument\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\x12\x1b\n" +
	"\tmime_type\x18\x04 \x01(\tR\bmimeType\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x03R\x04size\x12\x1d\n" +
	"\n" +
	"object_key\x18\x06 \x01(\tR\tobjectKey\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"status_msg\x18\b \x01(\tR\tstatusMsg\x12\x1f\n" +
	"\vchunk_count\x18\t \x01(\x05R\n" +
	"chunkCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\tR\tupdatedAt\x12!\n" +
	"\fcontent_hash\x18\f \x01(\tR\vcontentHash\x12\x14\n" +
	"\x05title\x18\r \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x0e \x01(\tR\x06author\x12!\n" +
	"\fpublished_at\x18\x0f \x01(\tR\vpublishedAt\x12\x1d\n" +
	"\n" +
	"source_ref\x18\x10 \x01(\tR\tsourceRef\x12\x12\n" +
	"\x04kind\x18\x11 \x01(\tR\x04kind\"\xa5\x01\n" +
	"\x04Chat\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12%\n" +
	"\x0eowner_username\x18\x06 \x01(\tR\rownerUsername\"\xf1\x02\n" +
	"\x06Source\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x19\n" +
	"\bchunk_id\x18\x03 \x01(\tR\achunkId\x12\x18\n" +
	"\asnippet\x18\x04 \x01(\tR\asnippet\x12\x14\n" +
	"\x05score\x18\x05 \x01(\x01R\x05score\x12\x1d\n" +
	"\n" +
	"char_start\x18\x06 \x01(\x05R\tcharStart\x12\x19\n" +
	"\bchar_end\x18\a \x01(\x05R\acharEnd\x12\x1d\n" +
	"\n" +
	"page_start\x18\b \x01(\x05R\tpageStart\x12\x19\n" +
	"\bpage_end\x18\t \x01(\x05R\apageEnd\x12'\n" +
	"\x0fsection_heading\x18\n" +
	" \x01(\tR\x0esectionHeading\x12\x16\n" +
	"\x06origin\x18\v \x01(\tR\x06origin\x12*\n" +
	"\x11raptor_summary_id\x18\f \x01(\tR\x0fraptorSummaryId\"\xc4\x01\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\achat_id\x18\x02 \x01(\tR\x06chatId\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12/\n" +
	"\asources\x18\x05 \x03(\v2\x15.rag.common.v1.SourceR\asources\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x12\n" +
	"\x04meta\x18\a \x01(\tR\x04meta\"Y\n" +
	"\x05Model\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x18\n" +
	"\abackend\x18\x04 \x01(\tR\abackend\"\xfa\x01\n" +
	"\x10DocumentUploaded\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x1d\n" +
	"\n" +
	"object_key\x18\x03 \x01(\tR\tobjectKey\x12\x1a\n" +
	"\bfilename\x18\x04 \x01(\tR\bfilename\x12\x1b\n" +
	"\tmime_type\x18\x05 \x01(\tR\bmimeType\x12\x12\n" +
	"\x04size\x18\x06 \x01(\x03R\x04size\x12\x19\n" +
	"\btrace_id\x18\a \x01(\tR\atraceId\x12#\n" +
	"\rarchive_depth\x18\b \x01(\x05R\farchiveDepth\"\x99\x03\n" +
	"\x0eDocumentParsed\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x1d\n" +
	"\n" +
	"object_key\x18\x03 \x01(\tR\tobjectKey\x12\x1a\n" +
	"\bfilename\x18\x04 \x01(\tR\bfilename\x12\x1b\n" +
	"\tmime_type\x18\x05 \x01(\tR\bmimeType\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06source\x12\x12\n" +
	"\x04text\x18\a \x01(\tR\x04text\x12G\n" +
	"\bmetadata\x18\b \x03(\v2+.rag.common.v1.DocumentParsed.MetadataEntryR\bmetadata\x12\x19\n" +
	"\btrace_id\x18\t \x01(\tR\atraceId\x12&\n" +
	"\x0ftext_object_key\x18\n" +
	" \x01(\tR\rtextObjectKey\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x89\x01\n" +
	"\x0fDocumentIndexed\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x1f\n" +
	"\vchunk_count\x18\x03 \x01(\x05R\n" +
	"chunkCount\x12\x19\n" +
	"\btrace_id\x18\x04 \x01(\tR\atraceId\"\xe2\x01\n" +
	"\x0eIngestionEvent\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\tR\ttimestamp\x12#\n" +
	"\rstage_current\x18\x06 \x01(\x05R\fstageCurrent\x12\x1f\n" +
	"\vstage_total\x18\a \x01(\x05R\n" +
	"stageTotal\"\xe2\x01\n" +
	"\n" +
	"RagRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x13\n" +
	"\x05top_k\x18\x03 \x01(\x05R\x04topK\x12\x16\n" +
	"\x06stream\x18\x04 \x01(\bR\x06stream\x12\x16\n" +
	"\x06prompt\x18\x05 \x01(\tR\x06prompt\x12,\n" +
	"\x12scope_document_ids\x18\x06 \x03(\tR\x10scopeDocumentIds\x120\n" +
	"\x14exclude_document_ids\x18\a \x03(\tR\x12excludeDocumentIds\"8\n" +
	"\bRagStage\x12\x14\n" +
	"\x05stage\x18\x01 \x01(\tR\x05stage\x12\x16\n" +
	"\x06millis\x18\x02 \x01(\x03R\x06millis\"\x83\x04\n" +
	"\bRagTrace\x12/\n" +
	"\x06stages\x18\x01 \x03(\v2\x17.rag.common.v1.RagStageR\x06stages\x12)\n" +
	"\x10candidates_dense\x18\x02 \x01(\x05R\x0fcandidatesDense\x12-\n" +
	"\x12candidates_lexical\x18\x03 \x01(\x05R\x11candidatesLexical\x12)\n" +
	"\x10candidates_fused\x18\x04 \x01(\x05R\x0fcandidatesFused\x12/\n" +
	"\x13candidates_returned\x18\x05 \x01(\x05R\x12candidatesReturned\x12\x1a\n" +
	"\bdegraded\x18\x06 \x01(\bR\bdegraded\x12'\n" +
	"\x0fdegraded_reason\x18\a \x01(\tR\x0edegradedReason\x12%\n" +
	"\x0eabstain_reason\x18\b \x01(\tR\rabstainReason\x12\x1b\n" +
	"\ttop_score\x18\t \x01(\x01R\btopScore\x12\x1f\n" +
	"\vscore_floor\x18\n" +
	" \x01(\x01R\n" +
	"scoreFloor\x12\x14\n" +
	"\x05cited\x18\v \x03(\tR\x05cited\x12'\n" +
	"\x0funcited_removed\x18\f \x03(\tR\x0euncitedRemoved\x12'\n" +
	"\x0fraptor_expanded\x18\r \x01(\x05R\x0eraptorExpanded\"\xb3\x01\n" +
	"\vRagResponse\x12\x16\n" +
	"\x06answer\x18\x01 \x01(\tR\x06answer\x12/\n" +
	"\asources\x18\x02 \x03(\v2\x15.rag.common.v1.SourceR\asources\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x16\n" +
	"\x06cached\x18\x04 \x01(\bR\x06cached\x12-\n" +
	"\x05trace\x18\x05 \x01(\v2\x17.rag.common.v1.RagTraceR\x05trace\"\x9b\x03\n" +
	"\x03KPI\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06metric\x18\x05 \x01(\tR\x06metric\x12\x12\n" +
	"\x04unit\x18\x06 \x01(\tR\x04unit\x12\x1c\n" +
	"\tdirection\x18\a \x01(\tR\tdirection\x12\x1f\n" +
	"\bbaseline\x18\b \x01(\x01H\x00R\bbaseline\x88\x01\x01\x12\x1b\n" +
	"\x06target\x18\t \x01(\x01H\x01R\x06target\x88\x01\x01\x12#\n" +
	"\rfunction_area\x18\n" +
	" \x01(\tR\ffunctionArea\x12\x16\n" +
	"\x06status\x18\v \x01(\tR\x06status\x12\x16\n" +
	"\x06detail\x18\f \x01(\tR\x06detail\x12\x1d\n" +
	"\n" +
	"created_at\x18\r \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\tR\tupdatedAtB\v\n" +
	"\t_baselineB\t\n" +
	"\a_target\"\xf8\x02\n" +
	"\aCluster\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12\x1a\n" +
	"\bkeywords\x18\x05 \x03(\tR\bkeywords\x12\x16\n" +
	"\x06method\x18\x06 \x01(\tR\x06method\x12\x1f\n" +
	"\vchunk_count\x18\a \x01(\x05R\n" +
	"chunkCount\x12%\n" +
	"\x0edocument_count\x18\b \x01(\x05R\rdocumentCount\x12(\n" +
	"\x0frepresentatives\x18\t \x01(\tR\x0frepresentatives\x12\x16\n" +
	"\x06params\x18\n" +
	" \x01(\tR\x06params\x12\x16\n" +
	"\x06status\x18\v \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\r \x01(\tR\tupdatedAt\"\xd5\x03\n" +
	"\x12HypothesisEvidence\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rhypothesis_id\x18\x02 \x01(\tR\fhypothesisId\x12$\n" +
	"\vdocument_id\x18\x03 \x01(\tH\x00R\n" +
	"documentId\x88\x01\x01\x12\x19\n" +
	"\bchunk_id\x18\x04 \x01(\tR\achunkId\x12\x1a\n" +
	"\bfilename\x18\x05 \x01(\tR\bfilename\x12\x18\n" +
	"\asnippet\x18\x06 \x01(\tR\asnippet\x12\x16\n" +
	"\x06stance\x18\a \x01(\tR\x06stance\x12\x19\n" +
	"\x05score\x18\b \x01(\x01H\x01R\x05score\x88\x01\x01\x12\x10\n" +
	"\x03ord\x18\t \x01(\x05R\x03ord\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\x12\x1a\n" +
	"\brelation\x18\v \x01(\tR\brelation\x12\x1d\n" +
	"\n" +
	"page_start\x18\f \x01(\x05R\tpageStart\x12\x19\n" +
	"\bpage_end\x18\r \x01(\x05R\apageEnd\x12'\n" +
	"\x0fsection_heading\x18\x0e \x01(\tR\x0esectionHeading\x12\x16\n" +
	"\x06origin\x18\x0f \x01(\tR\x06originB\x0e\n" +
	"\f_document_idB\b\n" +
	"\x06_score\"\xee\x01\n" +
	"\x12HypothesisRevision\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rhypothesis_id\x18\x02 \x01(\tR\fhypothesisId\x12\x1f\n" +
	"\vrevision_no\x18\x03 \x01(\x05R\n" +
	"revisionNo\x12\x1b\n" +
	"\teditor_id\x18\x04 \x01(\tR\beditorId\x12\x16\n" +
	"\x06action\x18\x05 \x01(\tR\x06action\x12\x18\n" +
	"\asummary\x18\x06 \x01(\tR\asummary\x12\x14\n" +
	"\x05patch\x18\a \x01(\tR\x05patch\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\"\x9b\b\n" +
	"\n" +
	"Hypothesis\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x15\n" +
	"\x06run_id\x18\x03 \x01(\tR\x05runId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x1c\n" +
	"\tstatement\x18\x05 \x01(\tR\tstatement\x12\x1c\n" +
	"\trationale\x18\x06 \x01(\tR\trationale\x12\x16\n" +
	"\x06method\x18\a \x01(\tR\x06method\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x1a\n" +
	"\x06kpi_id\x18\t \x01(\tH\x00R\x05kpiId\x88\x01\x01\x121\n" +
	"\x12primary_cluster_id\x18\n" +
	" \x01(\tH\x01R\x10primaryClusterId\x88\x01\x01\x12\x15\n" +
	"\x03trl\x18\v \x01(\x05H\x02R\x03trl\x88\x01\x01\x12(\n" +
	"\rnovelty_score\x18\f \x01(\x01H\x03R\fnoveltyScore\x88\x01\x01\x12\"\n" +
	"\n" +
	"risk_score\x18\r \x01(\x01H\x04R\triskScore\x88\x01\x01\x12$\n" +
	"\vvalue_score\x18\x0e \x01(\x01H\x05R\n" +
	"valueScore\x88\x01\x01\x12.\n" +
	"\x10confidence_score\x18\x0f \x01(\x01H\x06R\x0fconfidenceScore\x88\x01\x01\x12,\n" +
	"\x0fcomposite_score\x18\x10 \x01(\x01H\aR\x0ecompositeScore\x88\x01\x01\x12\x1e\n" +
	"\n" +
	"measurable\x18\x11 \x01(\bR\n" +
	"measurable\x12\"\n" +
	"\forganization\x18\x12 \x01(\tR\forganization\x12#\n" +
	"\rfunction_area\x18\x13 \x01(\tR\ffunctionArea\x12\x1f\n" +
	"\vsource_type\x18\x14 \x01(\tR\n" +
	"sourceType\x12\x1a\n" +
	"\blocation\x18\x15 \x01(\tR\blocation\x12\x12\n" +
	"\x04tags\x18\x16 \x03(\tR\x04tags\x12\x1e\n" +
	"\n" +
	"assessment\x18\x17 \x01(\tR\n" +
	"assessment\x12\x16\n" +
	"\x06detail\x18\x18 \x01(\tR\x06detail\x12\x1e\n" +
	"\n" +
	"generation\x18\x19 \x01(\tR\n" +
	"generation\x12\x1d\n" +
	"\n" +
	"created_at\x18\x1a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x1b \x01(\tR\tupdatedAt\x12=\n" +
	"\bevidence\x18\x1c \x03(\v2!.rag.common.v1.HypothesisEvidenceR\bevidenceB\t\n" +
	"\a_kpi_idB\x15\n" +
	"\x13_primary_cluster_idB\x06\n" +
	"\x04_trlB\x10\n" +
	"\x0e_novelty_scoreB\r\n" +
	"\v_risk_scoreB\x0e\n" +
	"\f_value_scoreB\x13\n" +
	"\x11_confidence_scoreB\x12\n" +
	"\x10_composite_scoreB<Z:github.com/example/rag-mvp/pkg/genproto/common/v1;commonv1b\x06proto3"

var (
	file_common_v1_common_proto_rawDescOnce sync.Once
	file_common_v1_common_proto_rawDescData []byte
)

func file_common_v1_common_proto_rawDescGZIP() []byte {
	file_common_v1_common_proto_rawDescOnce.Do(func() {
		file_common_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_v1_common_proto_rawDesc), len(file_common_v1_common_proto_rawDesc)))
	})
	return file_common_v1_common_proto_rawDescData
}

var file_common_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_common_v1_common_proto_goTypes = []any{
	(*User)(nil),               // 0: rag.common.v1.User
	(*Document)(nil),           // 1: rag.common.v1.Document
	(*Chat)(nil),               // 2: rag.common.v1.Chat
	(*Source)(nil),             // 3: rag.common.v1.Source
	(*Message)(nil),            // 4: rag.common.v1.Message
	(*Model)(nil),              // 5: rag.common.v1.Model
	(*DocumentUploaded)(nil),   // 6: rag.common.v1.DocumentUploaded
	(*DocumentParsed)(nil),     // 7: rag.common.v1.DocumentParsed
	(*DocumentIndexed)(nil),    // 8: rag.common.v1.DocumentIndexed
	(*IngestionEvent)(nil),     // 9: rag.common.v1.IngestionEvent
	(*RagRequest)(nil),         // 10: rag.common.v1.RagRequest
	(*RagStage)(nil),           // 11: rag.common.v1.RagStage
	(*RagTrace)(nil),           // 12: rag.common.v1.RagTrace
	(*RagResponse)(nil),        // 13: rag.common.v1.RagResponse
	(*KPI)(nil),                // 14: rag.common.v1.KPI
	(*Cluster)(nil),            // 15: rag.common.v1.Cluster
	(*HypothesisEvidence)(nil), // 16: rag.common.v1.HypothesisEvidence
	(*HypothesisRevision)(nil), // 17: rag.common.v1.HypothesisRevision
	(*Hypothesis)(nil),         // 18: rag.common.v1.Hypothesis
	nil,                        // 19: rag.common.v1.DocumentParsed.MetadataEntry
}
var file_common_v1_common_proto_depIdxs = []int32{
	3,  // 0: rag.common.v1.Message.sources:type_name -> rag.common.v1.Source
	19, // 1: rag.common.v1.DocumentParsed.metadata:type_name -> rag.common.v1.DocumentParsed.MetadataEntry
	11, // 2: rag.common.v1.RagTrace.stages:type_name -> rag.common.v1.RagStage
	3,  // 3: rag.common.v1.RagResponse.sources:type_name -> rag.common.v1.Source
	12, // 4: rag.common.v1.RagResponse.trace:type_name -> rag.common.v1.RagTrace
	16, // 5: rag.common.v1.Hypothesis.evidence:type_name -> rag.common.v1.HypothesisEvidence
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_common_v1_common_proto_init() }
func file_common_v1_common_proto_init() {
	if File_common_v1_common_proto != nil {
		return
	}
	file_common_v1_common_proto_msgTypes[14].OneofWrappers = []any{}
	file_common_v1_common_proto_msgTypes[16].OneofWrappers = []any{}
	file_common_v1_common_proto_msgTypes[18].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_v1_common_proto_rawDesc), len(file_common_v1_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_v1_common_proto_goTypes,
		DependencyIndexes: file_common_v1_common_proto_depIdxs,
		MessageInfos:      file_common_v1_common_proto_msgTypes,
	}.Build()
	File_common_v1_common_proto = out.File
	file_common_v1_common_proto_goTypes = nil
	file_common_v1_common_proto_depIdxs = nil
}
