# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from genproto.common.v1 import common_pb2 as common_dot_v1_dot_common__pb2
from genproto.db.v1 import db_pb2 as db_dot_v1_dot_db__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in db/v1/db_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DbServiceStub:
    """DbService is the only owner of PostgreSQL. NotFound is reported via the
    standard gRPC codes.NotFound status.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUserByUsername = channel.unary_unary(
                '/rag.db.v1.DbService/GetUserByUsername',
                request_serializer=db_dot_v1_dot_db__pb2.GetUserByUsernameRequest.SerializeToString,
                response_deserializer=common_dot_v1_dot_common__pb2.User.FromString,
                _registered_method=True)
        self.CreateUser = channel.unary_unary(
                '/rag.db.v1.DbService/CreateUser',
                request_serializer=db_dot_v1_dot_db__pb2.CreateUserRequest.SerializeToString,
                response_deserializer=common_dot_v1_dot_common__pb2.User.FromString,
                _registered_method=True)
        self.ListUsers = channel.unary_unary(
                '/rag.db.v1.DbService/ListUsers',
                request_serializer=db_dot_v1_dot_db__pb2.ListUsersRequest.SerializeToString,
                response_deserializer=db_dot_v1_dot_db__pb2.ListUsersResponse.FromString,
                _registered_method=True)
        self.CreateDocument = channel.unary_unary(
                '/rag.db.v1.DbService/CreateDocument',
                request_serializer=db_dot_v1_dot_db__pb2.CreateDocumentRequest.SerializeToString,
                response_deserializer=common_dot_v1_dot_common__pb2.Document.FromString,
                _registered_method=True)
        self.GetDocument = channel.unary_unary(
                '/rag.db.v1.DbService/GetDocument',
                request_serializer=db_dot_v1_dot_db__pb2.GetDocumentRequest.SerializeToString,
                response_deserializer=common_dot_v1_dot_common__pb2.Document.FromString,
                _registered_method=True)
        self.FindDocumentByHash = channel.unary_unary(
                '/rag.db.v1.DbService/FindDocumentByHash',
                request_serializer=db_dot_v1_dot_db__pb2.FindDocumentByHashRequest.SerializeToString,
                response_deserializer=common_dot_v1_dot_common__pb2.Document.FromString,
                _registered_method=True)
        self.ListDocuments = channel.unary_unary(
                '/rag.db.v1.DbService/ListDocuments',
                request_serializer=db_dot_v1_dot_db__pb2.ListDocumentsRequest.SerializeToString,
                response_deserializer=db_dot_v1_dot_db__pb2.ListDocumentsResponse.FromString,
                _registered_method=True)
        self.UpdateDocumentStatus = channel.unary_unary(
                '/rag.db.v1.DbService/UpdateDocumentStatus',
                request_serializer=db_dot_v1_dot_db__pb2.UpdateDocumentStatusRequest.SerializeToString,
                response_deserializer=db_dot_v1_dot_db__pb2.UpdateDocumentStatusResponse.FromString,
                _registered_method=True)
        self.SetDocumentTitle = channel.unary_unary(
                '/rag.db.v1.DbService/SetDocumentTitle',
                request_serializer=db_dot_v1_dot_db__pb2.SetDocumentTitleRequest.SerializeToString,
                response_deserializer=db_dot_v1_dot_db__pb2.SetDocumentTitleResponse.FromString,
                _registered_method=True)
        self.SetDocumentMeta = channel.unary_unary(
                '/rag.db.v1.DbService/SetDocumentMeta',
                request_serializer=db_dot_v1_dot_db__pb2.SetDocumentMetaRequest.SerializeToString,
                response_deserializer=db_dot_v1_dot_db__pb2.SetDocumentMetaResponse.FromString,
                _registered_method=True)
        self.SetDocumentKind = channel.unary_unary(
                '/rag.db.v1.DbService/SetDocumentKind',
                request_serializer=db_dot_v1_dot_db__pb2.SetDocumentKindRequest.SerializeToString,
                response_deserializer=db_dot_v1_dot_db__pb2.SetDocumentKindResponse.FromString,
                _registered_method=True)
        self.CreateChat = channel.unary_unary(
                '/rag.db.v1.DbService/CreateChat',
                request_serializer=db_dot_v1_dot_db__pb2.CreateChatRequest.SerializeToString,
                response_deserializer=common_dot_v1_dot_common__pb2.Chat.FromString,
                _registered_method=True)
        self.GetChat = channel.unary_unary(
                '/rag.db.v1.DbService/GetChat',
                request_serializer=db_dot_v1_dot_db__pb2.GetChatRequest.SerializeToString,
                response_deserializer=common_dot_v1_dot_common__pb2.Chat.FromString,
                _registered_method=True)
        self.ListChats = channel.unary_unary(
                '/rag.db.v1.DbService/ListChats',
                request_serializer=db_dot_v1_dot_db__pb2.ListChatsRequest.SerializeToString,
                response_deserializer=db_dot_v1_dot_db__pb2.ListChatsResponse.FromString,
                _registered_method=True)
        self.AddMessage = channel.unary_unary(
                '/rag.db.v1.DbService/AddMessage',
                request_serializer=db_dot_v1_dot_db__pb2.AddMessageRequest.SerializeToString,
                response_deserializer=common_dot_v1_dot_common__pb2.Message.FromString,
                _registered_method=True)
        self.ListMessages = channel.unary_unary(
                '/rag.db.v1.DbService/ListMessages',
                request_serializer=db_dot_v1_dot_db__pb2.ListMessagesRequest.SerializeToString,
                response_deserializer=db_dot_v1_dot_db__pb2.ListMessagesResponse.FromString,
                _registered_method=True)
        self.ListModels = channel.unary_unary(
                '/rag.db.v1.DbService/ListModels',
                request_serializer=db_dot_v1_dot_db__pb2.ListModelsRequest.SerializeToString,
                response_deserializer=db_dot_v1_dot_db__pb2.ListModelsResponse.FromString,
                _registered_method=True)
        self.CreateKPI = channel.unary_unary(
                '/rag.db.v1.DbService/CreateKPI',
                request_serializer=db_dot_v1_dot_db__pb2.CreateKPIRequest.SerializeToString,
                response_deserializer=common_dot_v1_dot_common__pb2.KPI.FromString,
                _registered_method=True)
        self.GetKPI = channel.unary_unary(
                '/rag.db.v1.DbService/GetKPI',
                request_serializer=db_dot_v1_dot_db__pb2.GetKPIRequest.SerializeToString,
                response_deserializer=common_dot_v1_dot_common__pb2.KPI.FromString,
                _registered_method=True)
        self.ListKPIs = channel.unary_unary(
                '/rag.db.v1.DbService/ListKPIs',
                request_serializer=db_dot_v1_dot_db__pb2.ListKPIsRequest.SerializeToString,
                response_deserializer=db_dot_v1_dot_db__pb2.ListKPIsResponse.FromString,
                _registered_method=True)
        self.UpdateKPI = channel.unary_unary(
                '/rag.db.v1.DbService/UpdateKPI',
                request_serializer=db_dot_v1_dot_db__pb2.UpdateKPIRequest.SerializeToString,
                response_deserializer=db_dot_v1_dot_db__pb2.UpdateKPIResponse.FromString,
                _registered_method=True)
        self.DeleteKPI = channel.unary_unary(
                '/rag.db.v1.DbService/DeleteKPI',
                request_serializer=db_dot_v1_dot_db__pb2.DeleteKPIRequest.SerializeToString,
                response_deserializer=db_dot_v1_dot_db__pb2.DeleteKPIResponse.FromString,
                _registered_method=True)
        self.AttachKpiDocument = channel.unary_unary(
                '/rag.db.v1.DbService/AttachKpiDocument',
                request_serializer=db_dot_v1_dot_db__pb2.AttachKpiDocumentRequest.SerializeToString,
                response_deserializer=db_dot_v1_dot_db__pb2.AttachKpiDocumentResponse.FromString,
                _registered_method=True)
        self.ListKpiDocuments = channel.unary_unary(
                '/rag.db.v1.DbService/ListKpiDocuments',
                request_serializer=db_dot_v1_dot_db__pb2.ListKpiDocumentsRequest.SerializeToString,
                response_deserializer=db_dot_v1_dot_db__pb2.ListKpiDocumentsResponse.FromString,
                _registered_method=True)
        self.DetachKpiDocument = channel.unary_unary(
                '/rag.db.v1.DbService/DetachKpiDocument',
                request_serializer=db_dot_v1_dot_db__pb2.DetachKpiDocumentRequest.SerializeToString,
                response_deserializer=db_dot_v1_dot_db__pb2.DetachKpiDocumentResponse.FromString,
                _registered_method=True)
        self.CreateCluster = channel.unary_unary(
                '/rag.db.v1.DbService/CreateCluster',
                request_serializer=db_dot_v1_dot_db__pb2.CreateClusterRequest.SerializeToString,
                response_deserializer=common_dot_v1_dot_common__pb2.Cluster.FromString,
                _registered_method=True)
        self.GetCluster = channel.unary_unary(
                '/rag.db.v1.DbService/GetCluster',
                request_serializer=db_dot_v1_dot_db__pb2.GetClusterRequest.SerializeToString,
                response_deserializer=common_dot_v1_dot_common__pb2.Cluster.FromString,
                _registered_method=True)
        self.ListClusters = channel.unary_unary(
                '/rag.db.v1.DbService/ListClusters',
                request_serializer=db_dot_v1_dot_db__pb2.ListClustersRequest.SerializeToString,
                response_deserializer=db_dot_v1_dot_db__pb2.ListClustersResponse.FromString,
                _registered_method=True)
        self.UpdateCluster = channel.unary_unary(
                '/rag.db.v1.DbService/UpdateCluster',
                request_serializer=db_dot_v1_dot_db__pb2.UpdateClusterRequest.SerializeToString,
                response_deserializer=db_dot_v1_dot_db__pb2.UpdateClusterResponse.FromString,
                _registered_method=True)
        self.DeleteClusters = channel.unary_unary(
                '/rag.db.v1.DbService/DeleteClusters',
                request_serializer=db_dot_v1_dot_db__pb2.DeleteClustersRequest.SerializeToString,
                response_deserializer=db_dot_v1_dot_db__pb2.DeleteClustersResponse.FromString,
                _registered_method=True)
        self.CreateHypothesis = channel.unary_unary(
                '/rag.db.v1.DbService/CreateHypothesis',
                request_serializer=db_dot_v1_dot_db__pb2.CreateHypothesisRequest.SerializeToString,
                response_deserializer=common_dot_v1_dot_common__pb2.Hypothesis.FromString,
                _registered_method=True)
        self.GetHypothesis = channel.unary_unary(
                '/rag.db.v1.DbService/GetHypothesis',
                request_serializer=db_dot_v1_dot_db__pb2.GetHypothesisRequest.SerializeToString,
                response_deserializer=common_dot_v1_dot_common__pb2.Hypothesis.FromString,
                _registered_method=True)
        self.ListHypotheses = channel.unary_unary(
                '/rag.db.v1.DbService/ListHypotheses',
                request_serializer=db_dot_v1_dot_db__pb2.ListHypothesesRequest.SerializeToString,
                response_deserializer=db_dot_v1_dot_db__pb2.ListHypothesesResponse.FromString,
                _registered_method=True)
        self.UpdateHypothesis = channel.unary_unary(
                '/rag.db.v1.DbService/UpdateHypothesis',
                request_serializer=db_dot_v1_dot_db__pb2.UpdateHypothesisRequest.SerializeToString,
                response_deserializer=db_dot_v1_dot_db__pb2.UpdateHypothesisResponse.FromString,
                _registered_method=True)
        self.AddHypothesisRevision = channel.unary_unary(
                '/rag.db.v1.DbService/AddHypothesisRevision',
                request_serializer=db_dot_v1_dot_db__pb2.AddHypothesisRevisionRequest.SerializeToString,
                response_deserializer=common_dot_v1_dot_common__pb2.HypothesisRevision.FromString,
                _registered_method=True)
        self.ListHypothesisRevisions = channel.unary_unary(
                '/rag.db.v1.DbService/ListHypothesisRevisions',
                request_serializer=db_dot_v1_dot_db__pb2.ListHypothesisRevisionsRequest.SerializeToString,
                response_deserializer=db_dot_v1_dot_db__pb2.ListHypothesisRevisionsResponse.FromString,
                _registered_method=True)
        self.ListHypothesisEvidence = channel.unary_unary(
                '/rag.db.v1.DbService/ListHypothesisEvidence',
                request_serializer=db_dot_v1_dot_db__pb2.ListHypothesisEvidenceRequest.SerializeToString,
                response_deserializer=db_dot_v1_dot_db__pb2.ListHypothesisEvidenceResponse.FromString,
                _registered_method=True)
        self.SetLLMUsageDaily = channel.unary_unary(
                '/rag.db.v1.DbService/SetLLMUsageDaily',
                request_serializer=db_dot_v1_dot_db__pb2.SetLLMUsageDailyRequest.SerializeToString,
                response_deserializer=db_dot_v1_dot_db__pb2.SetLLMUsageDailyResponse.FromString,
                _registered_method=True)
        self.ListLLMUsageDaily = channel.unary_unary(
                '/rag.db.v1.DbService/ListLLMUsageDaily',
                request_serializer=db_dot_v1_dot_db__pb2.ListLLMUsageDailyRequest.SerializeToString,
                response_deserializer=db_dot_v1_dot_db__pb2.ListLLMUsageDailyResponse.FromString,
                _registered_method=True)
        self.ListAppSettings = channel.unary_unary(
                '/rag.db.v1.DbService/ListAppSettings',
                request_serializer=db_dot_v1_dot_db__pb2.ListAppSettingsRequest.SerializeToString,
                response_deserializer=db_dot_v1_dot_db__pb2.ListAppSettingsResponse.FromString,
                _registered_method=True)
        self.SetAppSetting = channel.unary_unary(
                '/rag.db.v1.DbService/SetAppSetting',
                request_serializer=db_dot_v1_dot_db__pb2.SetAppSettingRequest.SerializeToString,
                response_deserializer=db_dot_v1_dot_db__pb2.SetAppSettingResponse.FromString,
                _registered_method=True)
        self.DeleteAppSetting = channel.unary_unary(
                '/rag.db.v1.DbService/DeleteAppSetting',
                request_serializer=db_dot_v1_dot_db__pb2.DeleteAppSettingRequest.SerializeToString,
                response_deserializer=db_dot_v1_dot_db__pb2.DeleteAppSettingResponse.FromString,
                _registered_method=True)


class DbServiceServicer:
    """DbService is the only owner of PostgreSQL. NotFound is reported via the
    standard gRPC codes.NotFound status.
    """

    def GetUserByUsername(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindDocumentByHash(self, request, context):
        """FindDocumentByHash returns the newest non-failed document with the given
        content hash, or NotFound — the lookup behind deduplication.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDocuments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateDocumentStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetDocumentTitle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetDocumentMeta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetDocumentKind(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateChat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListChats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateKPI(self, request, context):
        """Hypothesis Factory.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetKPI(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListKPIs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateKPI(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteKPI(self, request, context):
        """DeleteKPI removes a goal; linked hypotheses survive with kpi_id nulled
        (FK ON DELETE SET NULL).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AttachKpiDocument(self, request, context):
        """Goal input documents: many-to-many link between a KPI and uploaded
        documents that describe the plant's own data for that goal.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListKpiDocuments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetachKpiDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCluster(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCluster(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListClusters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCluster(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteClusters(self, request, context):
        """DeleteClusters removes all of an owner's clusters (auto-reclustering replaces
        the board: delete-all then re-create). Hypotheses are kept (FK SET NULL).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateHypothesis(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHypothesis(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListHypotheses(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateHypothesis(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddHypothesisRevision(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListHypothesisRevisions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListHypothesisEvidence(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetLLMUsageDaily(self, request, context):
        """LLM/OpenRouter usage ledger (Metrics dashboard). SetLLMUsageDaily mirrors a
        running daily total (SET semantics); ListLLMUsageDaily reads a date range.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListLLMUsageDaily(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAppSettings(self, request, context):
        """Global runtime overrides for env-style settings (admin "Параметры системы").
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetAppSetting(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAppSetting(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DbServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUserByUsername': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserByUsername,
                    request_deserializer=db_dot_v1_dot_db__pb2.GetUserByUsernameRequest.FromString,
                    response_serializer=common_dot_v1_dot_common__pb2.User.SerializeToString,
            ),
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=db_dot_v1_dot_db__pb2.CreateUserRequest.FromString,
                    response_serializer=common_dot_v1_dot_common__pb2.User.SerializeToString,
            ),
            'ListUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUsers,
                    request_deserializer=db_dot_v1_dot_db__pb2.ListUsersRequest.FromString,
                    response_serializer=db_dot_v1_dot_db__pb2.ListUsersResponse.SerializeToString,
            ),
            'CreateDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDocument,
                    request_deserializer=db_dot_v1_dot_db__pb2.CreateDocumentRequest.FromString,
                    response_serializer=common_dot_v1_dot_common__pb2.Document.SerializeToString,
            ),
            'GetDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDocument,
                    request_deserializer=db_dot_v1_dot_db__pb2.GetDocumentRequest.FromString,
                    response_serializer=common_dot_v1_dot_common__pb2.Document.SerializeToString,
            ),
            'FindDocumentByHash': grpc.unary_unary_rpc_method_handler(
                    servicer.FindDocumentByHash,
                    request_deserializer=db_dot_v1_dot_db__pb2.FindDocumentByHashRequest.FromString,
                    response_serializer=common_dot_v1_dot_common__pb2.Document.SerializeToString,
            ),
            'ListDocuments': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDocuments,
                    request_deserializer=db_dot_v1_dot_db__pb2.ListDocumentsRequest.FromString,
                    response_serializer=db_dot_v1_dot_db__pb2.ListDocumentsResponse.SerializeToString,
            ),
            'UpdateDocumentStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateDocumentStatus,
                    request_deserializer=db_dot_v1_dot_db__pb2.UpdateDocumentStatusRequest.FromString,
                    response_serializer=db_dot_v1_dot_db__pb2.UpdateDocumentStatusResponse.SerializeToString,
            ),
            'SetDocumentTitle': grpc.unary_unary_rpc_method_handler(
                    servicer.SetDocumentTitle,
                    request_deserializer=db_dot_v1_dot_db__pb2.SetDocumentTitleRequest.FromString,
                    response_serializer=db_dot_v1_dot_db__pb2.SetDocumentTitleResponse.SerializeToString,
            ),
            'SetDocumentMeta': grpc.unary_unary_rpc_method_handler(
                    servicer.SetDocumentMeta,
                    request_deserializer=db_dot_v1_dot_db__pb2.SetDocumentMetaRequest.FromString,
                    response_serializer=db_dot_v1_dot_db__pb2.SetDocumentMetaResponse.SerializeToString,
            ),
            'SetDocumentKind': grpc.unary_unary_rpc_method_handler(
                    servicer.SetDocumentKind,
                    request_deserializer=db_dot_v1_dot_db__pb2.SetDocumentKindRequest.FromString,
                    response_serializer=db_dot_v1_dot_db__pb2.SetDocumentKindResponse.SerializeToString,
            ),
            'CreateChat': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateChat,
                    request_deserializer=db_dot_v1_dot_db__pb2.CreateChatRequest.FromString,
                    response_serializer=common_dot_v1_dot_common__pb2.Chat.SerializeToString,
            ),
            'GetChat': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChat,
                    request_deserializer=db_dot_v1_dot_db__pb2.GetChatRequest.FromString,
                    response_serializer=common_dot_v1_dot_common__pb2.Chat.SerializeToString,
            ),
            'ListChats': grpc.unary_unary_rpc_method_handler(
                    servicer.ListChats,
                    request_deserializer=db_dot_v1_dot_db__pb2.ListChatsRequest.FromString,
                    response_serializer=db_dot_v1_dot_db__pb2.ListChatsResponse.SerializeToString,
            ),
            'AddMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.AddMessage,
                    request_deserializer=db_dot_v1_dot_db__pb2.AddMessageRequest.FromString,
                    response_serializer=common_dot_v1_dot_common__pb2.Message.SerializeToString,
            ),
            'ListMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMessages,
                    request_deserializer=db_dot_v1_dot_db__pb2.ListMessagesRequest.FromString,
                    response_serializer=db_dot_v1_dot_db__pb2.ListMessagesResponse.SerializeToString,
            ),
            'ListModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModels,
                    request_deserializer=db_dot_v1_dot_db__pb2.ListModelsRequest.FromString,
                    response_serializer=db_dot_v1_dot_db__pb2.ListModelsResponse.SerializeToString,
            ),
            'CreateKPI': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateKPI,
                    request_deserializer=db_dot_v1_dot_db__pb2.CreateKPIRequest.FromString,
                    response_serializer=common_dot_v1_dot_common__pb2.KPI.SerializeToString,
            ),
            'GetKPI': grpc.unary_unary_rpc_method_handler(
                    servicer.GetKPI,
                    request_deserializer=db_dot_v1_dot_db__pb2.GetKPIRequest.FromString,
                    response_serializer=common_dot_v1_dot_common__pb2.KPI.SerializeToString,
            ),
            'ListKPIs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListKPIs,
                    request_deserializer=db_dot_v1_dot_db__pb2.ListKPIsRequest.FromString,
                    response_serializer=db_dot_v1_dot_db__pb2.ListKPIsResponse.SerializeToString,
            ),
            'UpdateKPI': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateKPI,
                    request_deserializer=db_dot_v1_dot_db__pb2.UpdateKPIRequest.FromString,
                    response_serializer=db_dot_v1_dot_db__pb2.UpdateKPIResponse.SerializeToString,
            ),
            'DeleteKPI': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteKPI,
                    request_deserializer=db_dot_v1_dot_db__pb2.DeleteKPIRequest.FromString,
                    response_serializer=db_dot_v1_dot_db__pb2.DeleteKPIResponse.SerializeToString,
            ),
            'AttachKpiDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.AttachKpiDocument,
                    request_deserializer=db_dot_v1_dot_db__pb2.AttachKpiDocumentRequest.FromString,
                    response_serializer=db_dot_v1_dot_db__pb2.AttachKpiDocumentResponse.SerializeToString,
            ),
            'ListKpiDocuments': grpc.unary_unary_rpc_method_handler(
                    servicer.ListKpiDocuments,
                    request_deserializer=db_dot_v1_dot_db__pb2.ListKpiDocumentsRequest.FromString,
                    response_serializer=db_dot_v1_dot_db__pb2.ListKpiDocumentsResponse.SerializeToString,
            ),
            'DetachKpiDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.DetachKpiDocument,
                    request_deserializer=db_dot_v1_dot_db__pb2.DetachKpiDocumentRequest.FromString,
                    response_serializer=db_dot_v1_dot_db__pb2.DetachKpiDocumentResponse.SerializeToString,
            ),
            'CreateCluster': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCluster,
                    request_deserializer=db_dot_v1_dot_db__pb2.CreateClusterRequest.FromString,
                    response_serializer=common_dot_v1_dot_common__pb2.Cluster.SerializeToString,
            ),
            'GetCluster': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCluster,
                    request_deserializer=db_dot_v1_dot_db__pb2.GetClusterRequest.FromString,
                    response_serializer=common_dot_v1_dot_common__pb2.Cluster.SerializeToString,
            ),
            'ListClusters': grpc.unary_unary_rpc_method_handler(
                    servicer.ListClusters,
                    request_deserializer=db_dot_v1_dot_db__pb2.ListClustersRequest.FromString,
                    response_serializer=db_dot_v1_dot_db__pb2.ListClustersResponse.SerializeToString,
            ),
            'UpdateCluster': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCluster,
                    request_deserializer=db_dot_v1_dot_db__pb2.UpdateClusterRequest.FromString,
                    response_serializer=db_dot_v1_dot_db__pb2.UpdateClusterResponse.SerializeToString,
            ),
            'DeleteClusters': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteClusters,
                    request_deserializer=db_dot_v1_dot_db__pb2.DeleteClustersRequest.FromString,
                    response_serializer=db_dot_v1_dot_db__pb2.DeleteClustersResponse.SerializeToString,
            ),
            'CreateHypothesis': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateHypothesis,
                    request_deserializer=db_dot_v1_dot_db__pb2.CreateHypothesisRequest.FromString,
                    response_serializer=common_dot_v1_dot_common__pb2.Hypothesis.SerializeToString,
            ),
            'GetHypothesis': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHypothesis,
                    request_deserializer=db_dot_v1_dot_db__pb2.GetHypothesisRequest.FromString,
                    response_serializer=common_dot_v1_dot_common__pb2.Hypothesis.SerializeToString,
            ),
            'ListHypotheses': grpc.unary_unary_rpc_method_handler(
                    servicer.ListHypotheses,
                    request_deserializer=db_dot_v1_dot_db__pb2.ListHypothesesRequest.FromString,
                    response_serializer=db_dot_v1_dot_db__pb2.ListHypothesesResponse.SerializeToString,
            ),
            'UpdateHypothesis': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateHypothesis,
                    request_deserializer=db_dot_v1_dot_db__pb2.UpdateHypothesisRequest.FromString,
                    response_serializer=db_dot_v1_dot_db__pb2.UpdateHypothesisResponse.SerializeToString,
            ),
            'AddHypothesisRevision': grpc.unary_unary_rpc_method_handler(
                    servicer.AddHypothesisRevision,
                    request_deserializer=db_dot_v1_dot_db__pb2.AddHypothesisRevisionRequest.FromString,
                    response_serializer=common_dot_v1_dot_common__pb2.HypothesisRevision.SerializeToString,
            ),
            'ListHypothesisRevisions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListHypothesisRevisions,
                    request_deserializer=db_dot_v1_dot_db__pb2.ListHypothesisRevisionsRequest.FromString,
                    response_serializer=db_dot_v1_dot_db__pb2.ListHypothesisRevisionsResponse.SerializeToString,
            ),
            'ListHypothesisEvidence': grpc.unary_unary_rpc_method_handler(
                    servicer.ListHypothesisEvidence,
                    request_deserializer=db_dot_v1_dot_db__pb2.ListHypothesisEvidenceRequest.FromString,
                    response_serializer=db_dot_v1_dot_db__pb2.ListHypothesisEvidenceResponse.SerializeToString,
            ),
            'SetLLMUsageDaily': grpc.unary_unary_rpc_method_handler(
                    servicer.SetLLMUsageDaily,
                    request_deserializer=db_dot_v1_dot_db__pb2.SetLLMUsageDailyRequest.FromString,
                    response_serializer=db_dot_v1_dot_db__pb2.SetLLMUsageDailyResponse.SerializeToString,
            ),
            'ListLLMUsageDaily': grpc.unary_unary_rpc_method_handler(
                    servicer.ListLLMUsageDaily,
                    request_deserializer=db_dot_v1_dot_db__pb2.ListLLMUsageDailyRequest.FromString,
                    response_serializer=db_dot_v1_dot_db__pb2.ListLLMUsageDailyResponse.SerializeToString,
            ),
            'ListAppSettings': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAppSettings,
                    request_deserializer=db_dot_v1_dot_db__pb2.ListAppSettingsRequest.FromString,
                    response_serializer=db_dot_v1_dot_db__pb2.ListAppSettingsResponse.SerializeToString,
            ),
            'SetAppSetting': grpc.unary_unary_rpc_method_handler(
                    servicer.SetAppSetting,
                    request_deserializer=db_dot_v1_dot_db__pb2.SetAppSettingRequest.FromString,
                    response_serializer=db_dot_v1_dot_db__pb2.SetAppSettingResponse.SerializeToString,
            ),
            'DeleteAppSetting': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAppSetting,
                    request_deserializer=db_dot_v1_dot_db__pb2.DeleteAppSettingRequest.FromString,
                    response_serializer=db_dot_v1_dot_db__pb2.DeleteAppSettingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rag.db.v1.DbService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rag.db.v1.DbService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DbService:
    """DbService is the only owner of PostgreSQL. NotFound is reported via the
    standard gRPC codes.NotFound status.
    """

    @staticmethod
    def GetUserByUsername(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.db.v1.DbService/GetUserByUsername',
            db_dot_v1_dot_db__pb2.GetUserByUsernameRequest.SerializeToString,
            common_dot_v1_dot_common__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.db.v1.DbService/CreateUser',
            db_dot_v1_dot_db__pb2.CreateUserRequest.SerializeToString,
            common_dot_v1_dot_common__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.db.v1.DbService/ListUsers',
            db_dot_v1_dot_db__pb2.ListUsersRequest.SerializeToString,
            db_dot_v1_dot_db__pb2.ListUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.db.v1.DbService/CreateDocument',
            db_dot_v1_dot_db__pb2.CreateDocumentRequest.SerializeToString,
            common_dot_v1_dot_common__pb2.Document.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.db.v1.DbService/GetDocument',
            db_dot_v1_dot_db__pb2.GetDocumentRequest.SerializeToString,
            common_dot_v1_dot_common__pb2.Document.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindDocumentByHash(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.db.v1.DbService/FindDocumentByHash',
            db_dot_v1_dot_db__pb2.FindDocumentByHashRequest.SerializeToString,
            common_dot_v1_dot_common__pb2.Document.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.db.v1.DbService/ListDocuments',
            db_dot_v1_dot_db__pb2.ListDocumentsRequest.SerializeToString,
            db_dot_v1_dot_db__pb2.ListDocumentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateDocumentStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.db.v1.DbService/UpdateDocumentStatus',
            db_dot_v1_dot_db__pb2.UpdateDocumentStatusRequest.SerializeToString,
            db_dot_v1_dot_db__pb2.UpdateDocumentStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetDocumentTitle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.db.v1.DbService/SetDocumentTitle',
            db_dot_v1_dot_db__pb2.SetDocumentTitleRequest.SerializeToString,
            db_dot_v1_dot_db__pb2.SetDocumentTitleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetDocumentMeta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.db.v1.DbService/SetDocumentMeta',
            db_dot_v1_dot_db__pb2.SetDocumentMetaRequest.SerializeToString,
            db_dot_v1_dot_db__pb2.SetDocumentMetaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetDocumentKind(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.db.v1.DbService/SetDocumentKind',
            db_dot_v1_dot_db__pb2.SetDocumentKindRequest.SerializeToString,
            db_dot_v1_dot_db__pb2.SetDocumentKindResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.db.v1.DbService/CreateChat',
            db_dot_v1_dot_db__pb2.CreateChatRequest.SerializeToString,
            common_dot_v1_dot_common__pb2.Chat.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.db.v1.DbService/GetChat',
            db_dot_v1_dot_db__pb2.GetChatRequest.SerializeToString,
            common_dot_v1_dot_common__pb2.Chat.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListChats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.db.v1.DbService/ListChats',
            db_dot_v1_dot_db__pb2.ListChatsRequest.SerializeToString,
            db_dot_v1_dot_db__pb2.ListChatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.db.v1.DbService/AddMessage',
            db_dot_v1_dot_db__pb2.AddMessageRequest.SerializeToString,
            common_dot_v1_dot_common__pb2.Message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.db.v1.DbService/ListMessages',
            db_dot_v1_dot_db__pb2.ListMessagesRequest.SerializeToString,
            db_dot_v1_dot_db__pb2.ListMessagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.db.v1.DbService/ListModels',
            db_dot_v1_dot_db__pb2.ListModelsRequest.SerializeToString,
            db_dot_v1_dot_db__pb2.ListModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateKPI(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.db.v1.DbService/CreateKPI',
            db_dot_v1_dot_db__pb2.CreateKPIRequest.SerializeToString,
            common_dot_v1_dot_common__pb2.KPI.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetKPI(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.db.v1.DbService/GetKPI',
            db_dot_v1_dot_db__pb2.GetKPIRequest.SerializeToString,
            common_dot_v1_dot_common__pb2.KPI.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListKPIs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.db.v1.DbService/ListKPIs',
            db_dot_v1_dot_db__pb2.ListKPIsRequest.SerializeToString,
            db_dot_v1_dot_db__pb2.ListKPIsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateKPI(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.db.v1.DbService/UpdateKPI',
            db_dot_v1_dot_db__pb2.UpdateKPIRequest.SerializeToString,
            db_dot_v1_dot_db__pb2.UpdateKPIResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteKPI(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.db.v1.DbService/DeleteKPI',
            db_dot_v1_dot_db__pb2.DeleteKPIRequest.SerializeToString,
            db_dot_v1_dot_db__pb2.DeleteKPIResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AttachKpiDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.db.v1.DbService/AttachKpiDocument',
            db_dot_v1_dot_db__pb2.AttachKpiDocumentRequest.SerializeToString,
            db_dot_v1_dot_db__pb2.AttachKpiDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListKpiDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.db.v1.DbService/ListKpiDocuments',
            db_dot_v1_dot_db__pb2.ListKpiDocumentsRequest.SerializeToString,
            db_dot_v1_dot_db__pb2.ListKpiDocumentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetachKpiDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.db.v1.DbService/DetachKpiDocument',
            db_dot_v1_dot_db__pb2.DetachKpiDocumentRequest.SerializeToString,
            db_dot_v1_dot_db__pb2.DetachKpiDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateCluster(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.db.v1.DbService/CreateCluster',
            db_dot_v1_dot_db__pb2.CreateClusterRequest.SerializeToString,
            common_dot_v1_dot_common__pb2.Cluster.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCluster(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.db.v1.DbService/GetCluster',
            db_dot_v1_dot_db__pb2.GetClusterRequest.SerializeToString,
            common_dot_v1_dot_common__pb2.Cluster.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListClusters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.db.v1.DbService/ListClusters',
            db_dot_v1_dot_db__pb2.ListClustersRequest.SerializeToString,
            db_dot_v1_dot_db__pb2.ListClustersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateCluster(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.db.v1.DbService/UpdateCluster',
            db_dot_v1_dot_db__pb2.UpdateClusterRequest.SerializeToString,
            db_dot_v1_dot_db__pb2.UpdateClusterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteClusters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.db.v1.DbService/DeleteClusters',
            db_dot_v1_dot_db__pb2.DeleteClustersRequest.SerializeToString,
            db_dot_v1_dot_db__pb2.DeleteClustersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateHypothesis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.db.v1.DbService/CreateHypothesis',
            db_dot_v1_dot_db__pb2.CreateHypothesisRequest.SerializeToString,
            common_dot_v1_dot_common__pb2.Hypothesis.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHypothesis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.db.v1.DbService/GetHypothesis',
            db_dot_v1_dot_db__pb2.GetHypothesisRequest.SerializeToString,
            common_dot_v1_dot_common__pb2.Hypothesis.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListHypotheses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.db.v1.DbService/ListHypotheses',
            db_dot_v1_dot_db__pb2.ListHypothesesRequest.SerializeToString,
            db_dot_v1_dot_db__pb2.ListHypothesesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateHypothesis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.db.v1.DbService/UpdateHypothesis',
            db_dot_v1_dot_db__pb2.UpdateHypothesisRequest.SerializeToString,
            db_dot_v1_dot_db__pb2.UpdateHypothesisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddHypothesisRevision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.db.v1.DbService/AddHypothesisRevision',
            db_dot_v1_dot_db__pb2.AddHypothesisRevisionRequest.SerializeToString,
            common_dot_v1_dot_common__pb2.HypothesisRevision.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListHypothesisRevisions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.db.v1.DbService/ListHypothesisRevisions',
            db_dot_v1_dot_db__pb2.ListHypothesisRevisionsRequest.SerializeToString,
            db_dot_v1_dot_db__pb2.ListHypothesisRevisionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListHypothesisEvidence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.db.v1.DbService/ListHypothesisEvidence',
            db_dot_v1_dot_db__pb2.ListHypothesisEvidenceRequest.SerializeToString,
            db_dot_v1_dot_db__pb2.ListHypothesisEvidenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetLLMUsageDaily(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.db.v1.DbService/SetLLMUsageDaily',
            db_dot_v1_dot_db__pb2.SetLLMUsageDailyRequest.SerializeToString,
            db_dot_v1_dot_db__pb2.SetLLMUsageDailyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListLLMUsageDaily(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.db.v1.DbService/ListLLMUsageDaily',
            db_dot_v1_dot_db__pb2.ListLLMUsageDailyRequest.SerializeToString,
            db_dot_v1_dot_db__pb2.ListLLMUsageDailyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAppSettings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.db.v1.DbService/ListAppSettings',
            db_dot_v1_dot_db__pb2.ListAppSettingsRequest.SerializeToString,
            db_dot_v1_dot_db__pb2.ListAppSettingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetAppSetting(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.db.v1.DbService/SetAppSetting',
            db_dot_v1_dot_db__pb2.SetAppSettingRequest.SerializeToString,
            db_dot_v1_dot_db__pb2.SetAppSettingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteAppSetting(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.db.v1.DbService/DeleteAppSetting',
            db_dot_v1_dot_db__pb2.DeleteAppSettingRequest.SerializeToString,
            db_dot_v1_dot_db__pb2.DeleteAppSettingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
