// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: db/v1/db.proto

// Package rag.db.v1 is db-service's gRPC contract — the BFF over PostgreSQL that
// auth, main-service and the workers call internally.

package dbv1

import (
	context "context"
	v1 "github.com/example/db-service/internal/platform/genproto/common/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DbService_GetUserByUsername_FullMethodName       = "/rag.db.v1.DbService/GetUserByUsername"
	DbService_CreateUser_FullMethodName              = "/rag.db.v1.DbService/CreateUser"
	DbService_ListUsers_FullMethodName               = "/rag.db.v1.DbService/ListUsers"
	DbService_CreateDocument_FullMethodName          = "/rag.db.v1.DbService/CreateDocument"
	DbService_GetDocument_FullMethodName             = "/rag.db.v1.DbService/GetDocument"
	DbService_FindDocumentByHash_FullMethodName      = "/rag.db.v1.DbService/FindDocumentByHash"
	DbService_ListDocuments_FullMethodName           = "/rag.db.v1.DbService/ListDocuments"
	DbService_UpdateDocumentStatus_FullMethodName    = "/rag.db.v1.DbService/UpdateDocumentStatus"
	DbService_SetDocumentTitle_FullMethodName        = "/rag.db.v1.DbService/SetDocumentTitle"
	DbService_SetDocumentMeta_FullMethodName         = "/rag.db.v1.DbService/SetDocumentMeta"
	DbService_SetDocumentKind_FullMethodName         = "/rag.db.v1.DbService/SetDocumentKind"
	DbService_CreateChat_FullMethodName              = "/rag.db.v1.DbService/CreateChat"
	DbService_GetChat_FullMethodName                 = "/rag.db.v1.DbService/GetChat"
	DbService_ListChats_FullMethodName               = "/rag.db.v1.DbService/ListChats"
	DbService_AddMessage_FullMethodName              = "/rag.db.v1.DbService/AddMessage"
	DbService_ListMessages_FullMethodName            = "/rag.db.v1.DbService/ListMessages"
	DbService_ListModels_FullMethodName              = "/rag.db.v1.DbService/ListModels"
	DbService_CreateKPI_FullMethodName               = "/rag.db.v1.DbService/CreateKPI"
	DbService_GetKPI_FullMethodName                  = "/rag.db.v1.DbService/GetKPI"
	DbService_ListKPIs_FullMethodName                = "/rag.db.v1.DbService/ListKPIs"
	DbService_UpdateKPI_FullMethodName               = "/rag.db.v1.DbService/UpdateKPI"
	DbService_DeleteKPI_FullMethodName               = "/rag.db.v1.DbService/DeleteKPI"
	DbService_AttachKpiDocument_FullMethodName       = "/rag.db.v1.DbService/AttachKpiDocument"
	DbService_ListKpiDocuments_FullMethodName        = "/rag.db.v1.DbService/ListKpiDocuments"
	DbService_DetachKpiDocument_FullMethodName       = "/rag.db.v1.DbService/DetachKpiDocument"
	DbService_CreateCluster_FullMethodName           = "/rag.db.v1.DbService/CreateCluster"
	DbService_GetCluster_FullMethodName              = "/rag.db.v1.DbService/GetCluster"
	DbService_ListClusters_FullMethodName            = "/rag.db.v1.DbService/ListClusters"
	DbService_UpdateCluster_FullMethodName           = "/rag.db.v1.DbService/UpdateCluster"
	DbService_DeleteClusters_FullMethodName          = "/rag.db.v1.DbService/DeleteClusters"
	DbService_CreateHypothesis_FullMethodName        = "/rag.db.v1.DbService/CreateHypothesis"
	DbService_GetHypothesis_FullMethodName           = "/rag.db.v1.DbService/GetHypothesis"
	DbService_ListHypotheses_FullMethodName          = "/rag.db.v1.DbService/ListHypotheses"
	DbService_UpdateHypothesis_FullMethodName        = "/rag.db.v1.DbService/UpdateHypothesis"
	DbService_AddHypothesisRevision_FullMethodName   = "/rag.db.v1.DbService/AddHypothesisRevision"
	DbService_ListHypothesisRevisions_FullMethodName = "/rag.db.v1.DbService/ListHypothesisRevisions"
	DbService_ListHypothesisEvidence_FullMethodName  = "/rag.db.v1.DbService/ListHypothesisEvidence"
	DbService_SetLLMUsageDaily_FullMethodName        = "/rag.db.v1.DbService/SetLLMUsageDaily"
	DbService_ListLLMUsageDaily_FullMethodName       = "/rag.db.v1.DbService/ListLLMUsageDaily"
	DbService_ListAppSettings_FullMethodName         = "/rag.db.v1.DbService/ListAppSettings"
	DbService_SetAppSetting_FullMethodName           = "/rag.db.v1.DbService/SetAppSetting"
	DbService_DeleteAppSetting_FullMethodName        = "/rag.db.v1.DbService/DeleteAppSetting"
)

// DbServiceClient is the client API for DbService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DbService is the only owner of PostgreSQL. NotFound is reported via the
// standard gRPC codes.NotFound status.
type DbServiceClient interface {
	GetUserByUsername(ctx context.Context, in *GetUserByUsernameRequest, opts ...grpc.CallOption) (*v1.User, error)
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*v1.User, error)
	ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error)
	CreateDocument(ctx context.Context, in *CreateDocumentRequest, opts ...grpc.CallOption) (*v1.Document, error)
	GetDocument(ctx context.Context, in *GetDocumentRequest, opts ...grpc.CallOption) (*v1.Document, error)
	// FindDocumentByHash returns the newest non-failed document with the given
	// content hash, or NotFound — the lookup behind deduplication.
	FindDocumentByHash(ctx context.Context, in *FindDocumentByHashRequest, opts ...grpc.CallOption) (*v1.Document, error)
	ListDocuments(ctx context.Context, in *ListDocumentsRequest, opts ...grpc.CallOption) (*ListDocumentsResponse, error)
	UpdateDocumentStatus(ctx context.Context, in *UpdateDocumentStatusRequest, opts ...grpc.CallOption) (*UpdateDocumentStatusResponse, error)
	SetDocumentTitle(ctx context.Context, in *SetDocumentTitleRequest, opts ...grpc.CallOption) (*SetDocumentTitleResponse, error)
	SetDocumentMeta(ctx context.Context, in *SetDocumentMetaRequest, opts ...grpc.CallOption) (*SetDocumentMetaResponse, error)
	SetDocumentKind(ctx context.Context, in *SetDocumentKindRequest, opts ...grpc.CallOption) (*SetDocumentKindResponse, error)
	CreateChat(ctx context.Context, in *CreateChatRequest, opts ...grpc.CallOption) (*v1.Chat, error)
	GetChat(ctx context.Context, in *GetChatRequest, opts ...grpc.CallOption) (*v1.Chat, error)
	ListChats(ctx context.Context, in *ListChatsRequest, opts ...grpc.CallOption) (*ListChatsResponse, error)
	AddMessage(ctx context.Context, in *AddMessageRequest, opts ...grpc.CallOption) (*v1.Message, error)
	ListMessages(ctx context.Context, in *ListMessagesRequest, opts ...grpc.CallOption) (*ListMessagesResponse, error)
	ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error)
	// Hypothesis Factory.
	CreateKPI(ctx context.Context, in *CreateKPIRequest, opts ...grpc.CallOption) (*v1.KPI, error)
	GetKPI(ctx context.Context, in *GetKPIRequest, opts ...grpc.CallOption) (*v1.KPI, error)
	ListKPIs(ctx context.Context, in *ListKPIsRequest, opts ...grpc.CallOption) (*ListKPIsResponse, error)
	UpdateKPI(ctx context.Context, in *UpdateKPIRequest, opts ...grpc.CallOption) (*UpdateKPIResponse, error)
	// DeleteKPI removes a goal; linked hypotheses survive with kpi_id nulled
	// (FK ON DELETE SET NULL).
	DeleteKPI(ctx context.Context, in *DeleteKPIRequest, opts ...grpc.CallOption) (*DeleteKPIResponse, error)
	// Goal input documents: many-to-many link between a KPI and uploaded
	// documents that describe the plant's own data for that goal.
	AttachKpiDocument(ctx context.Context, in *AttachKpiDocumentRequest, opts ...grpc.CallOption) (*AttachKpiDocumentResponse, error)
	ListKpiDocuments(ctx context.Context, in *ListKpiDocumentsRequest, opts ...grpc.CallOption) (*ListKpiDocumentsResponse, error)
	DetachKpiDocument(ctx context.Context, in *DetachKpiDocumentRequest, opts ...grpc.CallOption) (*DetachKpiDocumentResponse, error)
	CreateCluster(ctx context.Context, in *CreateClusterRequest, opts ...grpc.CallOption) (*v1.Cluster, error)
	GetCluster(ctx context.Context, in *GetClusterRequest, opts ...grpc.CallOption) (*v1.Cluster, error)
	ListClusters(ctx context.Context, in *ListClustersRequest, opts ...grpc.CallOption) (*ListClustersResponse, error)
	UpdateCluster(ctx context.Context, in *UpdateClusterRequest, opts ...grpc.CallOption) (*UpdateClusterResponse, error)
	// DeleteClusters removes all of an owner's clusters (auto-reclustering replaces
	// the board: delete-all then re-create). Hypotheses are kept (FK SET NULL).
	DeleteClusters(ctx context.Context, in *DeleteClustersRequest, opts ...grpc.CallOption) (*DeleteClustersResponse, error)
	CreateHypothesis(ctx context.Context, in *CreateHypothesisRequest, opts ...grpc.CallOption) (*v1.Hypothesis, error)
	GetHypothesis(ctx context.Context, in *GetHypothesisRequest, opts ...grpc.CallOption) (*v1.Hypothesis, error)
	ListHypotheses(ctx context.Context, in *ListHypothesesRequest, opts ...grpc.CallOption) (*ListHypothesesResponse, error)
	UpdateHypothesis(ctx context.Context, in *UpdateHypothesisRequest, opts ...grpc.CallOption) (*UpdateHypothesisResponse, error)
	AddHypothesisRevision(ctx context.Context, in *AddHypothesisRevisionRequest, opts ...grpc.CallOption) (*v1.HypothesisRevision, error)
	ListHypothesisRevisions(ctx context.Context, in *ListHypothesisRevisionsRequest, opts ...grpc.CallOption) (*ListHypothesisRevisionsResponse, error)
	ListHypothesisEvidence(ctx context.Context, in *ListHypothesisEvidenceRequest, opts ...grpc.CallOption) (*ListHypothesisEvidenceResponse, error)
	// LLM/OpenRouter usage ledger (Metrics dashboard). SetLLMUsageDaily mirrors a
	// running daily total (SET semantics); ListLLMUsageDaily reads a date range.
	SetLLMUsageDaily(ctx context.Context, in *SetLLMUsageDailyRequest, opts ...grpc.CallOption) (*SetLLMUsageDailyResponse, error)
	ListLLMUsageDaily(ctx context.Context, in *ListLLMUsageDailyRequest, opts ...grpc.CallOption) (*ListLLMUsageDailyResponse, error)
	// Global runtime overrides for env-style settings (admin "Параметры системы").
	ListAppSettings(ctx context.Context, in *ListAppSettingsRequest, opts ...grpc.CallOption) (*ListAppSettingsResponse, error)
	SetAppSetting(ctx context.Context, in *SetAppSettingRequest, opts ...grpc.CallOption) (*SetAppSettingResponse, error)
	DeleteAppSetting(ctx context.Context, in *DeleteAppSettingRequest, opts ...grpc.CallOption) (*DeleteAppSettingResponse, error)
}

type dbServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDbServiceClient(cc grpc.ClientConnInterface) DbServiceClient {
	return &dbServiceClient{cc}
}

func (c *dbServiceClient) GetUserByUsername(ctx context.Context, in *GetUserByUsernameRequest, opts ...grpc.CallOption) (*v1.User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.User)
	err := c.cc.Invoke(ctx, DbService_GetUserByUsername_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*v1.User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.User)
	err := c.cc.Invoke(ctx, DbService_CreateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUsersResponse)
	err := c.cc.Invoke(ctx, DbService_ListUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) CreateDocument(ctx context.Context, in *CreateDocumentRequest, opts ...grpc.CallOption) (*v1.Document, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.Document)
	err := c.cc.Invoke(ctx, DbService_CreateDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) GetDocument(ctx context.Context, in *GetDocumentRequest, opts ...grpc.CallOption) (*v1.Document, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.Document)
	err := c.cc.Invoke(ctx, DbService_GetDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) FindDocumentByHash(ctx context.Context, in *FindDocumentByHashRequest, opts ...grpc.CallOption) (*v1.Document, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.Document)
	err := c.cc.Invoke(ctx, DbService_FindDocumentByHash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) ListDocuments(ctx context.Context, in *ListDocumentsRequest, opts ...grpc.CallOption) (*ListDocumentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDocumentsResponse)
	err := c.cc.Invoke(ctx, DbService_ListDocuments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) UpdateDocumentStatus(ctx context.Context, in *UpdateDocumentStatusRequest, opts ...grpc.CallOption) (*UpdateDocumentStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateDocumentStatusResponse)
	err := c.cc.Invoke(ctx, DbService_UpdateDocumentStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) SetDocumentTitle(ctx context.Context, in *SetDocumentTitleRequest, opts ...grpc.CallOption) (*SetDocumentTitleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetDocumentTitleResponse)
	err := c.cc.Invoke(ctx, DbService_SetDocumentTitle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) SetDocumentMeta(ctx context.Context, in *SetDocumentMetaRequest, opts ...grpc.CallOption) (*SetDocumentMetaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetDocumentMetaResponse)
	err := c.cc.Invoke(ctx, DbService_SetDocumentMeta_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) SetDocumentKind(ctx context.Context, in *SetDocumentKindRequest, opts ...grpc.CallOption) (*SetDocumentKindResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetDocumentKindResponse)
	err := c.cc.Invoke(ctx, DbService_SetDocumentKind_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) CreateChat(ctx context.Context, in *CreateChatRequest, opts ...grpc.CallOption) (*v1.Chat, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.Chat)
	err := c.cc.Invoke(ctx, DbService_CreateChat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) GetChat(ctx context.Context, in *GetChatRequest, opts ...grpc.CallOption) (*v1.Chat, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.Chat)
	err := c.cc.Invoke(ctx, DbService_GetChat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) ListChats(ctx context.Context, in *ListChatsRequest, opts ...grpc.CallOption) (*ListChatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListChatsResponse)
	err := c.cc.Invoke(ctx, DbService_ListChats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) AddMessage(ctx context.Context, in *AddMessageRequest, opts ...grpc.CallOption) (*v1.Message, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.Message)
	err := c.cc.Invoke(ctx, DbService_AddMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) ListMessages(ctx context.Context, in *ListMessagesRequest, opts ...grpc.CallOption) (*ListMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMessagesResponse)
	err := c.cc.Invoke(ctx, DbService_ListMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListModelsResponse)
	err := c.cc.Invoke(ctx, DbService_ListModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) CreateKPI(ctx context.Context, in *CreateKPIRequest, opts ...grpc.CallOption) (*v1.KPI, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.KPI)
	err := c.cc.Invoke(ctx, DbService_CreateKPI_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) GetKPI(ctx context.Context, in *GetKPIRequest, opts ...grpc.CallOption) (*v1.KPI, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.KPI)
	err := c.cc.Invoke(ctx, DbService_GetKPI_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) ListKPIs(ctx context.Context, in *ListKPIsRequest, opts ...grpc.CallOption) (*ListKPIsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListKPIsResponse)
	err := c.cc.Invoke(ctx, DbService_ListKPIs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) UpdateKPI(ctx context.Context, in *UpdateKPIRequest, opts ...grpc.CallOption) (*UpdateKPIResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateKPIResponse)
	err := c.cc.Invoke(ctx, DbService_UpdateKPI_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) DeleteKPI(ctx context.Context, in *DeleteKPIRequest, opts ...grpc.CallOption) (*DeleteKPIResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteKPIResponse)
	err := c.cc.Invoke(ctx, DbService_DeleteKPI_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) AttachKpiDocument(ctx context.Context, in *AttachKpiDocumentRequest, opts ...grpc.CallOption) (*AttachKpiDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttachKpiDocumentResponse)
	err := c.cc.Invoke(ctx, DbService_AttachKpiDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) ListKpiDocuments(ctx context.Context, in *ListKpiDocumentsRequest, opts ...grpc.CallOption) (*ListKpiDocumentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListKpiDocumentsResponse)
	err := c.cc.Invoke(ctx, DbService_ListKpiDocuments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) DetachKpiDocument(ctx context.Context, in *DetachKpiDocumentRequest, opts ...grpc.CallOption) (*DetachKpiDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetachKpiDocumentResponse)
	err := c.cc.Invoke(ctx, DbService_DetachKpiDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) CreateCluster(ctx context.Context, in *CreateClusterRequest, opts ...grpc.CallOption) (*v1.Cluster, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.Cluster)
	err := c.cc.Invoke(ctx, DbService_CreateCluster_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) GetCluster(ctx context.Context, in *GetClusterRequest, opts ...grpc.CallOption) (*v1.Cluster, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.Cluster)
	err := c.cc.Invoke(ctx, DbService_GetCluster_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) ListClusters(ctx context.Context, in *ListClustersRequest, opts ...grpc.CallOption) (*ListClustersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListClustersResponse)
	err := c.cc.Invoke(ctx, DbService_ListClusters_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) UpdateCluster(ctx context.Context, in *UpdateClusterRequest, opts ...grpc.CallOption) (*UpdateClusterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateClusterResponse)
	err := c.cc.Invoke(ctx, DbService_UpdateCluster_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) DeleteClusters(ctx context.Context, in *DeleteClustersRequest, opts ...grpc.CallOption) (*DeleteClustersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteClustersResponse)
	err := c.cc.Invoke(ctx, DbService_DeleteClusters_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) CreateHypothesis(ctx context.Context, in *CreateHypothesisRequest, opts ...grpc.CallOption) (*v1.Hypothesis, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.Hypothesis)
	err := c.cc.Invoke(ctx, DbService_CreateHypothesis_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) GetHypothesis(ctx context.Context, in *GetHypothesisRequest, opts ...grpc.CallOption) (*v1.Hypothesis, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.Hypothesis)
	err := c.cc.Invoke(ctx, DbService_GetHypothesis_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) ListHypotheses(ctx context.Context, in *ListHypothesesRequest, opts ...grpc.CallOption) (*ListHypothesesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListHypothesesResponse)
	err := c.cc.Invoke(ctx, DbService_ListHypotheses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) UpdateHypothesis(ctx context.Context, in *UpdateHypothesisRequest, opts ...grpc.CallOption) (*UpdateHypothesisResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateHypothesisResponse)
	err := c.cc.Invoke(ctx, DbService_UpdateHypothesis_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) AddHypothesisRevision(ctx context.Context, in *AddHypothesisRevisionRequest, opts ...grpc.CallOption) (*v1.HypothesisRevision, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.HypothesisRevision)
	err := c.cc.Invoke(ctx, DbService_AddHypothesisRevision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) ListHypothesisRevisions(ctx context.Context, in *ListHypothesisRevisionsRequest, opts ...grpc.CallOption) (*ListHypothesisRevisionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListHypothesisRevisionsResponse)
	err := c.cc.Invoke(ctx, DbService_ListHypothesisRevisions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) ListHypothesisEvidence(ctx context.Context, in *ListHypothesisEvidenceRequest, opts ...grpc.CallOption) (*ListHypothesisEvidenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListHypothesisEvidenceResponse)
	err := c.cc.Invoke(ctx, DbService_ListHypothesisEvidence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) SetLLMUsageDaily(ctx context.Context, in *SetLLMUsageDailyRequest, opts ...grpc.CallOption) (*SetLLMUsageDailyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetLLMUsageDailyResponse)
	err := c.cc.Invoke(ctx, DbService_SetLLMUsageDaily_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) ListLLMUsageDaily(ctx context.Context, in *ListLLMUsageDailyRequest, opts ...grpc.CallOption) (*ListLLMUsageDailyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLLMUsageDailyResponse)
	err := c.cc.Invoke(ctx, DbService_ListLLMUsageDaily_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) ListAppSettings(ctx context.Context, in *ListAppSettingsRequest, opts ...grpc.CallOption) (*ListAppSettingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAppSettingsResponse)
	err := c.cc.Invoke(ctx, DbService_ListAppSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) SetAppSetting(ctx context.Context, in *SetAppSettingRequest, opts ...grpc.CallOption) (*SetAppSettingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetAppSettingResponse)
	err := c.cc.Invoke(ctx, DbService_SetAppSetting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) DeleteAppSetting(ctx context.Context, in *DeleteAppSettingRequest, opts ...grpc.CallOption) (*DeleteAppSettingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAppSettingResponse)
	err := c.cc.Invoke(ctx, DbService_DeleteAppSetting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DbServiceServer is the server API for DbService service.
// All implementations must embed UnimplementedDbServiceServer
// for forward compatibility.
//
// DbService is the only owner of PostgreSQL. NotFound is reported via the
// standard gRPC codes.NotFound status.
type DbServiceServer interface {
	GetUserByUsername(context.Context, *GetUserByUsernameRequest) (*v1.User, error)
	CreateUser(context.Context, *CreateUserRequest) (*v1.User, error)
	ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error)
	CreateDocument(context.Context, *CreateDocumentRequest) (*v1.Document, error)
	GetDocument(context.Context, *GetDocumentRequest) (*v1.Document, error)
	// FindDocumentByHash returns the newest non-failed document with the given
	// content hash, or NotFound — the lookup behind deduplication.
	FindDocumentByHash(context.Context, *FindDocumentByHashRequest) (*v1.Document, error)
	ListDocuments(context.Context, *ListDocumentsRequest) (*ListDocumentsResponse, error)
	UpdateDocumentStatus(context.Context, *UpdateDocumentStatusRequest) (*UpdateDocumentStatusResponse, error)
	SetDocumentTitle(context.Context, *SetDocumentTitleRequest) (*SetDocumentTitleResponse, error)
	SetDocumentMeta(context.Context, *SetDocumentMetaRequest) (*SetDocumentMetaResponse, error)
	SetDocumentKind(context.Context, *SetDocumentKindRequest) (*SetDocumentKindResponse, error)
	CreateChat(context.Context, *CreateChatRequest) (*v1.Chat, error)
	GetChat(context.Context, *GetChatRequest) (*v1.Chat, error)
	ListChats(context.Context, *ListChatsRequest) (*ListChatsResponse, error)
	AddMessage(context.Context, *AddMessageRequest) (*v1.Message, error)
	ListMessages(context.Context, *ListMessagesRequest) (*ListMessagesResponse, error)
	ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error)
	// Hypothesis Factory.
	CreateKPI(context.Context, *CreateKPIRequest) (*v1.KPI, error)
	GetKPI(context.Context, *GetKPIRequest) (*v1.KPI, error)
	ListKPIs(context.Context, *ListKPIsRequest) (*ListKPIsResponse, error)
	UpdateKPI(context.Context, *UpdateKPIRequest) (*UpdateKPIResponse, error)
	// DeleteKPI removes a goal; linked hypotheses survive with kpi_id nulled
	// (FK ON DELETE SET NULL).
	DeleteKPI(context.Context, *DeleteKPIRequest) (*DeleteKPIResponse, error)
	// Goal input documents: many-to-many link between a KPI and uploaded
	// documents that describe the plant's own data for that goal.
	AttachKpiDocument(context.Context, *AttachKpiDocumentRequest) (*AttachKpiDocumentResponse, error)
	ListKpiDocuments(context.Context, *ListKpiDocumentsRequest) (*ListKpiDocumentsResponse, error)
	DetachKpiDocument(context.Context, *DetachKpiDocumentRequest) (*DetachKpiDocumentResponse, error)
	CreateCluster(context.Context, *CreateClusterRequest) (*v1.Cluster, error)
	GetCluster(context.Context, *GetClusterRequest) (*v1.Cluster, error)
	ListClusters(context.Context, *ListClustersRequest) (*ListClustersResponse, error)
	UpdateCluster(context.Context, *UpdateClusterRequest) (*UpdateClusterResponse, error)
	// DeleteClusters removes all of an owner's clusters (auto-reclustering replaces
	// the board: delete-all then re-create). Hypotheses are kept (FK SET NULL).
	DeleteClusters(context.Context, *DeleteClustersRequest) (*DeleteClustersResponse, error)
	CreateHypothesis(context.Context, *CreateHypothesisRequest) (*v1.Hypothesis, error)
	GetHypothesis(context.Context, *GetHypothesisRequest) (*v1.Hypothesis, error)
	ListHypotheses(context.Context, *ListHypothesesRequest) (*ListHypothesesResponse, error)
	UpdateHypothesis(context.Context, *UpdateHypothesisRequest) (*UpdateHypothesisResponse, error)
	AddHypothesisRevision(context.Context, *AddHypothesisRevisionRequest) (*v1.HypothesisRevision, error)
	ListHypothesisRevisions(context.Context, *ListHypothesisRevisionsRequest) (*ListHypothesisRevisionsResponse, error)
	ListHypothesisEvidence(context.Context, *ListHypothesisEvidenceRequest) (*ListHypothesisEvidenceResponse, error)
	// LLM/OpenRouter usage ledger (Metrics dashboard). SetLLMUsageDaily mirrors a
	// running daily total (SET semantics); ListLLMUsageDaily reads a date range.
	SetLLMUsageDaily(context.Context, *SetLLMUsageDailyRequest) (*SetLLMUsageDailyResponse, error)
	ListLLMUsageDaily(context.Context, *ListLLMUsageDailyRequest) (*ListLLMUsageDailyResponse, error)
	// Global runtime overrides for env-style settings (admin "Параметры системы").
	ListAppSettings(context.Context, *ListAppSettingsRequest) (*ListAppSettingsResponse, error)
	SetAppSetting(context.Context, *SetAppSettingRequest) (*SetAppSettingResponse, error)
	DeleteAppSetting(context.Context, *DeleteAppSettingRequest) (*DeleteAppSettingResponse, error)
	mustEmbedUnimplementedDbServiceServer()
}

// UnimplementedDbServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDbServiceServer struct{}

func (UnimplementedDbServiceServer) GetUserByUsername(context.Context, *GetUserByUsernameRequest) (*v1.User, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserByUsername not implemented")
}
func (UnimplementedDbServiceServer) CreateUser(context.Context, *CreateUserRequest) (*v1.User, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedDbServiceServer) ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUsers not implemented")
}
func (UnimplementedDbServiceServer) CreateDocument(context.Context, *CreateDocumentRequest) (*v1.Document, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDocument not implemented")
}
func (UnimplementedDbServiceServer) GetDocument(context.Context, *GetDocumentRequest) (*v1.Document, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDocument not implemented")
}
func (UnimplementedDbServiceServer) FindDocumentByHash(context.Context, *FindDocumentByHashRequest) (*v1.Document, error) {
	return nil, status.Error(codes.Unimplemented, "method FindDocumentByHash not implemented")
}
func (UnimplementedDbServiceServer) ListDocuments(context.Context, *ListDocumentsRequest) (*ListDocumentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDocuments not implemented")
}
func (UnimplementedDbServiceServer) UpdateDocumentStatus(context.Context, *UpdateDocumentStatusRequest) (*UpdateDocumentStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDocumentStatus not implemented")
}
func (UnimplementedDbServiceServer) SetDocumentTitle(context.Context, *SetDocumentTitleRequest) (*SetDocumentTitleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetDocumentTitle not implemented")
}
func (UnimplementedDbServiceServer) SetDocumentMeta(context.Context, *SetDocumentMetaRequest) (*SetDocumentMetaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetDocumentMeta not implemented")
}
func (UnimplementedDbServiceServer) SetDocumentKind(context.Context, *SetDocumentKindRequest) (*SetDocumentKindResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetDocumentKind not implemented")
}
func (UnimplementedDbServiceServer) CreateChat(context.Context, *CreateChatRequest) (*v1.Chat, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateChat not implemented")
}
func (UnimplementedDbServiceServer) GetChat(context.Context, *GetChatRequest) (*v1.Chat, error) {
	return nil, status.Error(codes.Unimplemented, "method GetChat not implemented")
}
func (UnimplementedDbServiceServer) ListChats(context.Context, *ListChatsRequest) (*ListChatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListChats not implemented")
}
func (UnimplementedDbServiceServer) AddMessage(context.Context, *AddMessageRequest) (*v1.Message, error) {
	return nil, status.Error(codes.Unimplemented, "method AddMessage not implemented")
}
func (UnimplementedDbServiceServer) ListMessages(context.Context, *ListMessagesRequest) (*ListMessagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMessages not implemented")
}
func (UnimplementedDbServiceServer) ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListModels not implemented")
}
func (UnimplementedDbServiceServer) CreateKPI(context.Context, *CreateKPIRequest) (*v1.KPI, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateKPI not implemented")
}
func (UnimplementedDbServiceServer) GetKPI(context.Context, *GetKPIRequest) (*v1.KPI, error) {
	return nil, status.Error(codes.Unimplemented, "method GetKPI not implemented")
}
func (UnimplementedDbServiceServer) ListKPIs(context.Context, *ListKPIsRequest) (*ListKPIsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListKPIs not implemented")
}
func (UnimplementedDbServiceServer) UpdateKPI(context.Context, *UpdateKPIRequest) (*UpdateKPIResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateKPI not implemented")
}
func (UnimplementedDbServiceServer) DeleteKPI(context.Context, *DeleteKPIRequest) (*DeleteKPIResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteKPI not implemented")
}
func (UnimplementedDbServiceServer) AttachKpiDocument(context.Context, *AttachKpiDocumentRequest) (*AttachKpiDocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AttachKpiDocument not implemented")
}
func (UnimplementedDbServiceServer) ListKpiDocuments(context.Context, *ListKpiDocumentsRequest) (*ListKpiDocumentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListKpiDocuments not implemented")
}
func (UnimplementedDbServiceServer) DetachKpiDocument(context.Context, *DetachKpiDocumentRequest) (*DetachKpiDocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DetachKpiDocument not implemented")
}
func (UnimplementedDbServiceServer) CreateCluster(context.Context, *CreateClusterRequest) (*v1.Cluster, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCluster not implemented")
}
func (UnimplementedDbServiceServer) GetCluster(context.Context, *GetClusterRequest) (*v1.Cluster, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCluster not implemented")
}
func (UnimplementedDbServiceServer) ListClusters(context.Context, *ListClustersRequest) (*ListClustersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListClusters not implemented")
}
func (UnimplementedDbServiceServer) UpdateCluster(context.Context, *UpdateClusterRequest) (*UpdateClusterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCluster not implemented")
}
func (UnimplementedDbServiceServer) DeleteClusters(context.Context, *DeleteClustersRequest) (*DeleteClustersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteClusters not implemented")
}
func (UnimplementedDbServiceServer) CreateHypothesis(context.Context, *CreateHypothesisRequest) (*v1.Hypothesis, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateHypothesis not implemented")
}
func (UnimplementedDbServiceServer) GetHypothesis(context.Context, *GetHypothesisRequest) (*v1.Hypothesis, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHypothesis not implemented")
}
func (UnimplementedDbServiceServer) ListHypotheses(context.Context, *ListHypothesesRequest) (*ListHypothesesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListHypotheses not implemented")
}
func (UnimplementedDbServiceServer) UpdateHypothesis(context.Context, *UpdateHypothesisRequest) (*UpdateHypothesisResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateHypothesis not implemented")
}
func (UnimplementedDbServiceServer) AddHypothesisRevision(context.Context, *AddHypothesisRevisionRequest) (*v1.HypothesisRevision, error) {
	return nil, status.Error(codes.Unimplemented, "method AddHypothesisRevision not implemented")
}
func (UnimplementedDbServiceServer) ListHypothesisRevisions(context.Context, *ListHypothesisRevisionsRequest) (*ListHypothesisRevisionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListHypothesisRevisions not implemented")
}
func (UnimplementedDbServiceServer) ListHypothesisEvidence(context.Context, *ListHypothesisEvidenceRequest) (*ListHypothesisEvidenceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListHypothesisEvidence not implemented")
}
func (UnimplementedDbServiceServer) SetLLMUsageDaily(context.Context, *SetLLMUsageDailyRequest) (*SetLLMUsageDailyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetLLMUsageDaily not implemented")
}
func (UnimplementedDbServiceServer) ListLLMUsageDaily(context.Context, *ListLLMUsageDailyRequest) (*ListLLMUsageDailyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLLMUsageDaily not implemented")
}
func (UnimplementedDbServiceServer) ListAppSettings(context.Context, *ListAppSettingsRequest) (*ListAppSettingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAppSettings not implemented")
}
func (UnimplementedDbServiceServer) SetAppSetting(context.Context, *SetAppSettingRequest) (*SetAppSettingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetAppSetting not implemented")
}
func (UnimplementedDbServiceServer) DeleteAppSetting(context.Context, *DeleteAppSettingRequest) (*DeleteAppSettingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAppSetting not implemented")
}
func (UnimplementedDbServiceServer) mustEmbedUnimplementedDbServiceServer() {}
func (UnimplementedDbServiceServer) testEmbeddedByValue()                   {}

// UnsafeDbServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DbServiceServer will
// result in compilation errors.
type UnsafeDbServiceServer interface {
	mustEmbedUnimplementedDbServiceServer()
}

func RegisterDbServiceServer(s grpc.ServiceRegistrar, srv DbServiceServer) {
	// If the following call panics, it indicates UnimplementedDbServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DbService_ServiceDesc, srv)
}

func _DbService_GetUserByUsername_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserByUsernameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).GetUserByUsername(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_GetUserByUsername_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).GetUserByUsername(ctx, req.(*GetUserByUsernameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_ListUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).ListUsers(ctx, req.(*ListUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_CreateDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).CreateDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_CreateDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).CreateDocument(ctx, req.(*CreateDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_GetDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).GetDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_GetDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).GetDocument(ctx, req.(*GetDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_FindDocumentByHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindDocumentByHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).FindDocumentByHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_FindDocumentByHash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).FindDocumentByHash(ctx, req.(*FindDocumentByHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_ListDocuments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDocumentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).ListDocuments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_ListDocuments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).ListDocuments(ctx, req.(*ListDocumentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_UpdateDocumentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDocumentStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).UpdateDocumentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_UpdateDocumentStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).UpdateDocumentStatus(ctx, req.(*UpdateDocumentStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_SetDocumentTitle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDocumentTitleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).SetDocumentTitle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_SetDocumentTitle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).SetDocumentTitle(ctx, req.(*SetDocumentTitleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_SetDocumentMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDocumentMetaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).SetDocumentMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_SetDocumentMeta_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).SetDocumentMeta(ctx, req.(*SetDocumentMetaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_SetDocumentKind_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDocumentKindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).SetDocumentKind(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_SetDocumentKind_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).SetDocumentKind(ctx, req.(*SetDocumentKindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_CreateChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).CreateChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_CreateChat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).CreateChat(ctx, req.(*CreateChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_GetChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).GetChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_GetChat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).GetChat(ctx, req.(*GetChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_ListChats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListChatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).ListChats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_ListChats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).ListChats(ctx, req.(*ListChatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_AddMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).AddMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_AddMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).AddMessage(ctx, req.(*AddMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_ListMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).ListMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_ListMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).ListMessages(ctx, req.(*ListMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_ListModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).ListModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_ListModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).ListModels(ctx, req.(*ListModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_CreateKPI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateKPIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).CreateKPI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_CreateKPI_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).CreateKPI(ctx, req.(*CreateKPIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_GetKPI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKPIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).GetKPI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_GetKPI_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).GetKPI(ctx, req.(*GetKPIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_ListKPIs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListKPIsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).ListKPIs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_ListKPIs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).ListKPIs(ctx, req.(*ListKPIsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_UpdateKPI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateKPIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).UpdateKPI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_UpdateKPI_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).UpdateKPI(ctx, req.(*UpdateKPIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_DeleteKPI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteKPIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).DeleteKPI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_DeleteKPI_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).DeleteKPI(ctx, req.(*DeleteKPIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_AttachKpiDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachKpiDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).AttachKpiDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_AttachKpiDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).AttachKpiDocument(ctx, req.(*AttachKpiDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_ListKpiDocuments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListKpiDocumentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).ListKpiDocuments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_ListKpiDocuments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).ListKpiDocuments(ctx, req.(*ListKpiDocumentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_DetachKpiDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetachKpiDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).DetachKpiDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_DetachKpiDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).DetachKpiDocument(ctx, req.(*DetachKpiDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_CreateCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).CreateCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_CreateCluster_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).CreateCluster(ctx, req.(*CreateClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_GetCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).GetCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_GetCluster_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).GetCluster(ctx, req.(*GetClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_ListClusters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListClustersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).ListClusters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_ListClusters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).ListClusters(ctx, req.(*ListClustersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_UpdateCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).UpdateCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_UpdateCluster_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).UpdateCluster(ctx, req.(*UpdateClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_DeleteClusters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteClustersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).DeleteClusters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_DeleteClusters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).DeleteClusters(ctx, req.(*DeleteClustersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_CreateHypothesis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateHypothesisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).CreateHypothesis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_CreateHypothesis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).CreateHypothesis(ctx, req.(*CreateHypothesisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_GetHypothesis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHypothesisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).GetHypothesis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_GetHypothesis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).GetHypothesis(ctx, req.(*GetHypothesisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_ListHypotheses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHypothesesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).ListHypotheses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_ListHypotheses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).ListHypotheses(ctx, req.(*ListHypothesesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_UpdateHypothesis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateHypothesisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).UpdateHypothesis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_UpdateHypothesis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).UpdateHypothesis(ctx, req.(*UpdateHypothesisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_AddHypothesisRevision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddHypothesisRevisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).AddHypothesisRevision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_AddHypothesisRevision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).AddHypothesisRevision(ctx, req.(*AddHypothesisRevisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_ListHypothesisRevisions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHypothesisRevisionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).ListHypothesisRevisions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_ListHypothesisRevisions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).ListHypothesisRevisions(ctx, req.(*ListHypothesisRevisionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_ListHypothesisEvidence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHypothesisEvidenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).ListHypothesisEvidence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_ListHypothesisEvidence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).ListHypothesisEvidence(ctx, req.(*ListHypothesisEvidenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_SetLLMUsageDaily_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetLLMUsageDailyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).SetLLMUsageDaily(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_SetLLMUsageDaily_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).SetLLMUsageDaily(ctx, req.(*SetLLMUsageDailyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_ListLLMUsageDaily_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLLMUsageDailyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).ListLLMUsageDaily(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_ListLLMUsageDaily_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).ListLLMUsageDaily(ctx, req.(*ListLLMUsageDailyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_ListAppSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAppSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).ListAppSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_ListAppSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).ListAppSettings(ctx, req.(*ListAppSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_SetAppSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAppSettingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).SetAppSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_SetAppSetting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).SetAppSetting(ctx, req.(*SetAppSettingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_DeleteAppSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAppSettingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).DeleteAppSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_DeleteAppSetting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).DeleteAppSetting(ctx, req.(*DeleteAppSettingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DbService_ServiceDesc is the grpc.ServiceDesc for DbService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DbService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rag.db.v1.DbService",
	HandlerType: (*DbServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserByUsername",
			Handler:    _DbService_GetUserByUsername_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _DbService_CreateUser_Handler,
		},
		{
			MethodName: "ListUsers",
			Handler:    _DbService_ListUsers_Handler,
		},
		{
			MethodName: "CreateDocument",
			Handler:    _DbService_CreateDocument_Handler,
		},
		{
			MethodName: "GetDocument",
			Handler:    _DbService_GetDocument_Handler,
		},
		{
			MethodName: "FindDocumentByHash",
			Handler:    _DbService_FindDocumentByHash_Handler,
		},
		{
			MethodName: "ListDocuments",
			Handler:    _DbService_ListDocuments_Handler,
		},
		{
			MethodName: "UpdateDocumentStatus",
			Handler:    _DbService_UpdateDocumentStatus_Handler,
		},
		{
			MethodName: "SetDocumentTitle",
			Handler:    _DbService_SetDocumentTitle_Handler,
		},
		{
			MethodName: "SetDocumentMeta",
			Handler:    _DbService_SetDocumentMeta_Handler,
		},
		{
			MethodName: "SetDocumentKind",
			Handler:    _DbService_SetDocumentKind_Handler,
		},
		{
			MethodName: "CreateChat",
			Handler:    _DbService_CreateChat_Handler,
		},
		{
			MethodName: "GetChat",
			Handler:    _DbService_GetChat_Handler,
		},
		{
			MethodName: "ListChats",
			Handler:    _DbService_ListChats_Handler,
		},
		{
			MethodName: "AddMessage",
			Handler:    _DbService_AddMessage_Handler,
		},
		{
			MethodName: "ListMessages",
			Handler:    _DbService_ListMessages_Handler,
		},
		{
			MethodName: "ListModels",
			Handler:    _DbService_ListModels_Handler,
		},
		{
			MethodName: "CreateKPI",
			Handler:    _DbService_CreateKPI_Handler,
		},
		{
			MethodName: "GetKPI",
			Handler:    _DbService_GetKPI_Handler,
		},
		{
			MethodName: "ListKPIs",
			Handler:    _DbService_ListKPIs_Handler,
		},
		{
			MethodName: "UpdateKPI",
			Handler:    _DbService_UpdateKPI_Handler,
		},
		{
			MethodName: "DeleteKPI",
			Handler:    _DbService_DeleteKPI_Handler,
		},
		{
			MethodName: "AttachKpiDocument",
			Handler:    _DbService_AttachKpiDocument_Handler,
		},
		{
			MethodName: "ListKpiDocuments",
			Handler:    _DbService_ListKpiDocuments_Handler,
		},
		{
			MethodName: "DetachKpiDocument",
			Handler:    _DbService_DetachKpiDocument_Handler,
		},
		{
			MethodName: "CreateCluster",
			Handler:    _DbService_CreateCluster_Handler,
		},
		{
			MethodName: "GetCluster",
			Handler:    _DbService_GetCluster_Handler,
		},
		{
			MethodName: "ListClusters",
			Handler:    _DbService_ListClusters_Handler,
		},
		{
			MethodName: "UpdateCluster",
			Handler:    _DbService_UpdateCluster_Handler,
		},
		{
			MethodName: "DeleteClusters",
			Handler:    _DbService_DeleteClusters_Handler,
		},
		{
			MethodName: "CreateHypothesis",
			Handler:    _DbService_CreateHypothesis_Handler,
		},
		{
			MethodName: "GetHypothesis",
			Handler:    _DbService_GetHypothesis_Handler,
		},
		{
			MethodName: "ListHypotheses",
			Handler:    _DbService_ListHypotheses_Handler,
		},
		{
			MethodName: "UpdateHypothesis",
			Handler:    _DbService_UpdateHypothesis_Handler,
		},
		{
			MethodName: "AddHypothesisRevision",
			Handler:    _DbService_AddHypothesisRevision_Handler,
		},
		{
			MethodName: "ListHypothesisRevisions",
			Handler:    _DbService_ListHypothesisRevisions_Handler,
		},
		{
			MethodName: "ListHypothesisEvidence",
			Handler:    _DbService_ListHypothesisEvidence_Handler,
		},
		{
			MethodName: "SetLLMUsageDaily",
			Handler:    _DbService_SetLLMUsageDaily_Handler,
		},
		{
			MethodName: "ListLLMUsageDaily",
			Handler:    _DbService_ListLLMUsageDaily_Handler,
		},
		{
			MethodName: "ListAppSettings",
			Handler:    _DbService_ListAppSettings_Handler,
		},
		{
			MethodName: "SetAppSetting",
			Handler:    _DbService_SetAppSetting_Handler,
		},
		{
			MethodName: "DeleteAppSetting",
			Handler:    _DbService_DeleteAppSetting_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "db/v1/db.proto",
}
