// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: llm/v1/llm.proto

// Package rag.llm.v1 is llm-service's gRPC contract — grounded answer generation
// (hybrid retrieval -> rerank -> generate) called by main-service, plus the
// chunk reader behind the document-preview pane (the indexed chunks ARE the
// platform's canonical extracted content; originals stay in S3).

package llmv1

import (
	context "context"
	v1 "github.com/example/rag-mvp/pkg/genproto/common/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RagService_Answer_FullMethodName         = "/rag.llm.v1.RagService/Answer"
	RagService_DocumentChunks_FullMethodName = "/rag.llm.v1.RagService/DocumentChunks"
)

// RagServiceClient is the client API for RagService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RagServiceClient interface {
	Answer(ctx context.Context, in *v1.RagRequest, opts ...grpc.CallOption) (*v1.RagResponse, error)
	DocumentChunks(ctx context.Context, in *DocumentChunksRequest, opts ...grpc.CallOption) (*DocumentChunksResponse, error)
}

type ragServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRagServiceClient(cc grpc.ClientConnInterface) RagServiceClient {
	return &ragServiceClient{cc}
}

func (c *ragServiceClient) Answer(ctx context.Context, in *v1.RagRequest, opts ...grpc.CallOption) (*v1.RagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.RagResponse)
	err := c.cc.Invoke(ctx, RagService_Answer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragServiceClient) DocumentChunks(ctx context.Context, in *DocumentChunksRequest, opts ...grpc.CallOption) (*DocumentChunksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DocumentChunksResponse)
	err := c.cc.Invoke(ctx, RagService_DocumentChunks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RagServiceServer is the server API for RagService service.
// All implementations must embed UnimplementedRagServiceServer
// for forward compatibility.
type RagServiceServer interface {
	Answer(context.Context, *v1.RagRequest) (*v1.RagResponse, error)
	DocumentChunks(context.Context, *DocumentChunksRequest) (*DocumentChunksResponse, error)
	mustEmbedUnimplementedRagServiceServer()
}

// UnimplementedRagServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRagServiceServer struct{}

func (UnimplementedRagServiceServer) Answer(context.Context, *v1.RagRequest) (*v1.RagResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Answer not implemented")
}
func (UnimplementedRagServiceServer) DocumentChunks(context.Context, *DocumentChunksRequest) (*DocumentChunksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DocumentChunks not implemented")
}
func (UnimplementedRagServiceServer) mustEmbedUnimplementedRagServiceServer() {}
func (UnimplementedRagServiceServer) testEmbeddedByValue()                    {}

// UnsafeRagServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RagServiceServer will
// result in compilation errors.
type UnsafeRagServiceServer interface {
	mustEmbedUnimplementedRagServiceServer()
}

func RegisterRagServiceServer(s grpc.ServiceRegistrar, srv RagServiceServer) {
	// If the following call panics, it indicates UnimplementedRagServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RagService_ServiceDesc, srv)
}

func _RagService_Answer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.RagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).Answer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_Answer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).Answer(ctx, req.(*v1.RagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagService_DocumentChunks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DocumentChunksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).DocumentChunks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_DocumentChunks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).DocumentChunks(ctx, req.(*DocumentChunksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RagService_ServiceDesc is the grpc.ServiceDesc for RagService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RagService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rag.llm.v1.RagService",
	HandlerType: (*RagServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Answer",
			Handler:    _RagService_Answer_Handler,
		},
		{
			MethodName: "DocumentChunks",
			Handler:    _RagService_DocumentChunks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "llm/v1/llm.proto",
}
