# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: llm/v1/llm.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'llm/v1/llm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genproto.common.v1 import common_pb2 as common_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10llm/v1/llm.proto\x12\nrag.llm.v1\x1a\x16\x63ommon/v1/common.proto\">\n\x15\x44ocumentChunksRequest\x12\x13\n\x0b\x64ocument_id\x18\x01 \x01(\t\x12\x10\n\x08owner_id\x18\x02 \x01(\t\"8\n\rDocumentChunk\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05index\x18\x02 \x01(\x05\x12\x0c\n\x04text\x18\x03 \x01(\t\"C\n\x16\x44ocumentChunksResponse\x12)\n\x06\x63hunks\x18\x01 \x03(\x0b\x32\x19.rag.llm.v1.DocumentChunk2\xa6\x01\n\nRagService\x12?\n\x06\x41nswer\x12\x19.rag.common.v1.RagRequest\x1a\x1a.rag.common.v1.RagResponse\x12W\n\x0e\x44ocumentChunks\x12!.rag.llm.v1.DocumentChunksRequest\x1a\".rag.llm.v1.DocumentChunksResponseB6Z4github.com/example/rag-mvp/pkg/genproto/llm/v1;llmv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llm.v1.llm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z4github.com/example/rag-mvp/pkg/genproto/llm/v1;llmv1'
  _globals['_DOCUMENTCHUNKSREQUEST']._serialized_start=56
  _globals['_DOCUMENTCHUNKSREQUEST']._serialized_end=118
  _globals['_DOCUMENTCHUNK']._serialized_start=120
  _globals['_DOCUMENTCHUNK']._serialized_end=176
  _globals['_DOCUMENTCHUNKSRESPONSE']._serialized_start=178
  _globals['_DOCUMENTCHUNKSRESPONSE']._serialized_end=245
  _globals['_RAGSERVICE']._serialized_start=248
  _globals['_RAGSERVICE']._serialized_end=414
# @@protoc_insertion_point(module_scope)
