// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: llm/v1/llm.proto

// Package rag.llm.v1 is llm-service's gRPC contract — grounded answer generation
// (hybrid retrieval -> rerank -> generate) called by main-service, plus the
// chunk reader behind the document-preview pane (the indexed chunks ARE the
// platform's canonical extracted content; originals stay in S3).

package llmv1

import (
	v1 "github.com/example/pdf-parser/internal/platform/genproto/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DocumentChunksRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	DocumentId string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	// Owner scoping mirrors retrieval: a caller may only read chunks of
	// documents that belong to the given owner.
	OwnerId       string `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentChunksRequest) Reset() {
	*x = DocumentChunksRequest{}
	mi := &file_llm_v1_llm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentChunksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentChunksRequest) ProtoMessage() {}

func (x *DocumentChunksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llm_v1_llm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentChunksRequest.ProtoReflect.Descriptor instead.
func (*DocumentChunksRequest) Descriptor() ([]byte, []int) {
	return file_llm_v1_llm_proto_rawDescGZIP(), []int{0}
}

func (x *DocumentChunksRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *DocumentChunksRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

type DocumentChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`        // chunk id (Qdrant point id == OpenSearch _id)
	Index         int32                  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"` // position within the document (chunk_index payload)
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentChunk) Reset() {
	*x = DocumentChunk{}
	mi := &file_llm_v1_llm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentChunk) ProtoMessage() {}

func (x *DocumentChunk) ProtoReflect() protoreflect.Message {
	mi := &file_llm_v1_llm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentChunk.ProtoReflect.Descriptor instead.
func (*DocumentChunk) Descriptor() ([]byte, []int) {
	return file_llm_v1_llm_proto_rawDescGZIP(), []int{1}
}

func (x *DocumentChunk) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DocumentChunk) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *DocumentChunk) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type DocumentChunksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunks        []*DocumentChunk       `protobuf:"bytes,1,rep,name=chunks,proto3" json:"chunks,omitempty"` // ordered by index ascending
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentChunksResponse) Reset() {
	*x = DocumentChunksResponse{}
	mi := &file_llm_v1_llm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentChunksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentChunksResponse) ProtoMessage() {}

func (x *DocumentChunksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llm_v1_llm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentChunksResponse.ProtoReflect.Descriptor instead.
func (*DocumentChunksResponse) Descriptor() ([]byte, []int) {
	return file_llm_v1_llm_proto_rawDescGZIP(), []int{2}
}

func (x *DocumentChunksResponse) GetChunks() []*DocumentChunk {
	if x != nil {
		return x.Chunks
	}
	return nil
}

var File_llm_v1_llm_proto protoreflect.FileDescriptor

const file_llm_v1_llm_proto_rawDesc = "" +
	"\n" +
	"\x10llm/v1/llm.proto\x12\n" +
	"rag.llm.v1\x1a\x16common/v1/common.proto\"S\n" +
	"\x15DocumentChunksRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\"I\n" +
	"\rDocumentChunk\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x05R\x05index\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\"K\n" +
	"\x16DocumentChunksResponse\x121\n" +
	"\x06chunks\x18\x01 \x03(\v2\x19.rag.llm.v1.DocumentChunkR\x06chunks2\xa6\x01\n" +
	"\n" +
	"RagService\x12?\n" +
	"\x06Answer\x12\x19.rag.common.v1.RagRequest\x1a\x1a.rag.common.v1.RagResponse\x12W\n" +
	"\x0eDocumentChunks\x12!.rag.llm.v1.DocumentChunksRequest\x1a\".rag.llm.v1.DocumentChunksResponseB6Z4github.com/example/rag-mvp/pkg/genproto/llm/v1;llmv1b\x06proto3"

var (
	file_llm_v1_llm_proto_rawDescOnce sync.Once
	file_llm_v1_llm_proto_rawDescData []byte
)

func file_llm_v1_llm_proto_rawDescGZIP() []byte {
	file_llm_v1_llm_proto_rawDescOnce.Do(func() {
		file_llm_v1_llm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_llm_v1_llm_proto_rawDesc), len(file_llm_v1_llm_proto_rawDesc)))
	})
	return file_llm_v1_llm_proto_rawDescData
}

var file_llm_v1_llm_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_llm_v1_llm_proto_goTypes = []any{
	(*DocumentChunksRequest)(nil),  // 0: rag.llm.v1.DocumentChunksRequest
	(*DocumentChunk)(nil),          // 1: rag.llm.v1.DocumentChunk
	(*DocumentChunksResponse)(nil), // 2: rag.llm.v1.DocumentChunksResponse
	(*v1.RagRequest)(nil),          // 3: rag.common.v1.RagRequest
	(*v1.RagResponse)(nil),         // 4: rag.common.v1.RagResponse
}
var file_llm_v1_llm_proto_depIdxs = []int32{
	1, // 0: rag.llm.v1.DocumentChunksResponse.chunks:type_name -> rag.llm.v1.DocumentChunk
	3, // 1: rag.llm.v1.RagService.Answer:input_type -> rag.common.v1.RagRequest
	0, // 2: rag.llm.v1.RagService.DocumentChunks:input_type -> rag.llm.v1.DocumentChunksRequest
	4, // 3: rag.llm.v1.RagService.Answer:output_type -> rag.common.v1.RagResponse
	2, // 4: rag.llm.v1.RagService.DocumentChunks:output_type -> rag.llm.v1.DocumentChunksResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_llm_v1_llm_proto_init() }
func file_llm_v1_llm_proto_init() {
	if File_llm_v1_llm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_llm_v1_llm_proto_rawDesc), len(file_llm_v1_llm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_llm_v1_llm_proto_goTypes,
		DependencyIndexes: file_llm_v1_llm_proto_depIdxs,
		MessageInfos:      file_llm_v1_llm_proto_msgTypes,
	}.Build()
	File_llm_v1_llm_proto = out.File
	file_llm_v1_llm_proto_goTypes = nil
	file_llm_v1_llm_proto_depIdxs = nil
}
